### ISSUE TITLE
Is there a way to reorder cards in news feed

### ISSUE THREAD

**Issue by nicolla1003** [Appboy/appboy-ios-sdk#100]
* [x] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 8.0
 SDK Version             | e.g. 3.7.6
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 7.3
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once

**Comment by Wenzhi** [comment]
Hey @nicolla1003,

We don't support reordering news feed cards on the SDK level, but you can reorder them on the dashboard. 

If you want to change the news feed cards' order inside the app, you can create your own custom news feed page to display the cards in your order.

Please let us know if you have more questions :)

Thanks,
Wenzhi

**Comment by briancaw** [comment]
Hi @nicolla1003 

Please feel free to reopen this issue if you have any further questions/comments.  We'll also update when we've got timelines on client side reordering of cards.

Thanks,
Brian
