### ISSUE TITLE
2.26.0-beta SDWebImage version not comparable with SDWebImage github 4.0

### ISSUE THREAD

**Issue by mlloyd** [Appboy/appboy-ios-sdk#101]
Hey @Wenzhi

I have tried the Carthage 2.26.0-beta but the SDWebImage framework isn't working. Comparably with the version built direct from SDWebImage using Carthage.

I believe the issue is due to your zip including, the SDWebImage framework. Which is not the correct module header. It's incorrectly labelled, SDWebImage_umbrella.h Normally the include would be, #import <SDWebImage/SDWebImage.h>

For reference;
https://github.com/rs/SDWebImage/blob/4.0.0/WebImage/SDWebImage.h

Thanks, Martin

**Comment by mlloyd** [comment]
@Wenzhi Let me know if I can assist further.

**Comment by briancaw** [comment]
Hi @mlloyd 

Thanks very much for reporting.  It looks like the artifact that got updated in the 2.26.0-beta release was actually our 2.25.0 SDK (and SDWebImage < 4.0).  We've gone an updated the  beta release zip to be correct - also note you must link FLAnimatedImage framework as well to use this solution.  

If the updated release isn't working, can you let us know a few more details about what the error looks like? e.g. A screenshot of the errant framework files and the build error, steps to reproduce, and any other details that might help us further debug.

Thanks,
Brian

**Comment by briancaw** [comment]
Hi @mlloyd 

Were you able to confirm that the updated artifact fixed things for you?  We're hoping to resolve this for you ASAP and any signal here would be much appreciated.

Thanks,
Brian

**Comment by mlloyd** [comment]
Hi @briancaw 

I don't get as far as last time. 
Using Carthage version 0.19.1

*** Skipped building Appboy-iOS-SDK due to the error:
Dependency "Appboy-iOS-SDK" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Appboy/Appboy-iOS-SDK/issues/new

What results have you seen when building with Carthage?

- Martin

**Comment by briancaw** [comment]
Hi @mlloyd 

We're successfully able to pull the 2.26.0-beta artifact from our repo and build it into a project.  `carthage update` output looks like:

```
carthage update
*** Cloning Appboy-iOS-SDK
*** Downloading Appboy-iOS-SDK.framework binary at "2.26.0-beta"
```

Our Cartfile contains the following line to pull our artifacts:

```
github "Appboy/Appboy-iOS-SDK" "2.26.0-beta"
```

Can you let us know what commands are outputting that error?  And can you retry after clearing your Carthage cache - `rm -rf ~/Library/Caches/org.carthage.CarthageKit`.

Thanks,
Brian

**Comment by mlloyd** [comment]
Hey @briancaw 

Looks good now. Required the cache clean.
I'll continue with my integration.

Thanks, Martin

**Comment by briancaw** [comment]
Hi @mlloyd 

Great to hear things are working - thanks for reporting!  Please feel free to reach out if you have any other issues.

Thanks,
Brian
