### ISSUE TITLE
Support Core Version SDK For Carthage

### ISSUE THREAD

**Issue by Wenzhi** [Appboy/appboy-ios-sdk#103]
Question from https://github.com/Appboy/appboy-ios-sdk/issues/46#issuecomment-283461377:

![image](https://cloud.githubusercontent.com/assets/996652/23525869/f6146afe-ff5d-11e6-9b1a-0e97368e5229.png)

**Comment by hokstuff** [comment]
We have now added support for a core version of the Braze Carthage framework as of release 3.11.0. You can find the core framework zip file [here](https://github.com/Appboy/appboy-ios-sdk/releases) and instructions for how to integrate with it [here](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/carthage_integration/#carthage-integration)
