### ISSUE TITLE
Crash with 2.2.6/Core

### ISSUE THREAD

**Issue by keith** [Appboy/appboy-ios-sdk#104]
We've just upgraded to the Core subspec with 2.2.6 and started seeing this crash:

![image](https://cloud.githubusercontent.com/assets/283886/23808469/d9e4918e-057e-11e7-9ed0-70ff2a4cd498.png)

The Core SDK doesn't require SDWebImage at all, so it probably shouldn't be calling any APIs from it.

**Comment by Wenzhi** [comment]
@keith,

Thanks for letting us know about the crash! In our code, we try to detect`SDWebImageManager` class's existence before continuing the image download process. Do you integrate a different version of SDWebImage framework, or you don't use SDWebImage in your app at all?

Thanks,
Wenzhi

**Comment by keith** [comment]
We do have it right now yes. But this seems extremely risky since when you're doing that there's no way you can verify that we have a version you're compatible with. Meaning the possibility of this crash will always exist.

**Comment by Wenzhi** [comment]
Hi @keith,

I'm adding handling to all SDWebImage related code which will fix the crash. We are also going to work on more robust modularization so that we can ensure to handle this scenario more gracefully. The new version should be released on Monday. We will let you know as soon as we release it.  Thanks very much for reporting and please let us know if you have any further questions/comments.

Thanks,
Wenzhi

**Comment by keith** [comment]
Can you just remove the calls to SDWebImage all together, or add SDWebImage to your required dependencies? It feels extremely fragile to just add more `respondsToSelector` checks. That could even fail if the method signature changed between versions.

**Comment by briancaw** [comment]
Hi @keith 

Thanks again for reporting this.  We plan to release on Monday with code that ensures things won't crash in the Core flavor if any required SDWebImage method signature is missing. 

We plan to release again later in the week with an update that separates out SDWebImage access into the UI subspec.  Please let us know if that timeline doesn't work for you.

Thanks,
Brian

**Comment by Wenzhi** [comment]
Hey @keith,

SDK Version 2.28.0 moved all the calls to SDWebImage into an `ABKSDWebImageProxy` class that exists only in the UI subspec. Please let us know if you have any questions/comments and if this resolves the issue.

Thanks very much for helping improve our SDK!
Wenzhi

**Comment by keith** [comment]
This is probably solved now, so closing.
