### ISSUE TITLE
Slideup inapp message causes status bar to go black

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-ios-sdk#105]
* [x] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.0
 SDK Version             | 2.26.0
 Integration Method      | cocoapods
 Xcode Version           | 8.2
 Repro rate              | 100%
 
## What did you do?

 - Show an inapp slideup message

## What did you expect to happen?

 - Status bar remains the same color than the root view controller's since slideup inapp messages don't show any dimming view or don't really interact with the style of the root view controller.

## What happened instead?

 - Status bar went black

## Steps to reproduce

 - Send any inapp slideup message to yourself
 - Ensure that you're looking at a view controller that has `.lightContent` as the preferred status bar style
 - Status bar goes black

## Code Snippet

N/A

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No

## Project that demonstrates the issue

N/A

### With Notification up

![image](https://cloud.githubusercontent.com/assets/941453/24166295/04d4e3b2-0e30-11e7-80c0-96a5a924a9cc.png)

### Without notification

![image](https://cloud.githubusercontent.com/assets/941453/24166318/1521eb02-0e30-11e7-9897-f89b57b726c4.png)

**Comment by Wenzhi** [comment]
Hey @ldiqual, 

Thanks for reporting the issue! Can I ask more questions for me to reproduce the issue? 
- What's the `Status Bar Style` value in the project settings' `General` tab?
- What value do you set for `View controller-based status bar appearance` in your .plist file?
- Does the status bar's color change back to light after the in-app message is dismissed?

Appboy's in-app messages are displayed within Appboy's UIWindow, and we don't implement `preferredStatusBarStyle` in our in-app message view controllers, so all the in-app messages should display with the status bar style set in the project's "General" tab. Does your app change status bar based on view controller?

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
Hey @ldiqual,

Are there any updates regarding the issue? Do you need more help or other information? Please let us know!

Thanks,
Wenzhi

**Comment by ldiqual** [comment]
@Wenzhi Thanks for getting back to me!

 1. Status bar style is `Default` in the general tab
 2. `UIViewControllerBasedStatusBarAppearance` is true
 3. Yes, the status bar reverts back to its original color after being dismissed

> Does your app change status bar based on view controller?

Yes.

I'm not sure what the proper fix is here, but maybe you could save the previous status bar style from the key window before presenting appboy's, and then revert it when the window goes away. You could also special case that if you detect the `UIViewControllerBasedStatusBarAppearance == true` flag.

Let me know if you have any further questions. Thanks!

**Comment by ldiqual** [comment]
@Wenzhi Any update on this?

**Comment by tiffanylu** [comment]
Hi @ldiqual,

Thank you for your patience here! We are planning to expose our header file for the in-app message window view controller in our next release. You can then create a category to override our window view controller's `preferredStatusBarStyle` depending on your app's internal UI logic. 

We don't have a set release timeline yet, so if you need a solution sooner you can manually add `ABKInAppMessageWindowController.h` to your project to implement the category. Please let us know if this proposed solution works for you.

Best,
Tiff

**Comment by ldiqual** [comment]
@tiffanylu Thanks for following up! I think that would work. Let me know when the change goes out and I'll give it a try. Thanks!

**Comment by tiffanylu** [comment]
Hi @ldiqual,

We just released iOS SDK version 2.29.1, which publicizes `ABKInAppMessageWindowController.h` for customization. Thanks for raising up this issue!

Best,
Tiff

**Comment by camanjj** [comment]
I have run into this exact issue using an all swift (4.0) project. I have tried creating an extension, as an alternative to categories, but my overridden methods were not called. Is there another workaround that you can suggest without adding a category?
