### ISSUE TITLE
AppBoy ‘Core’ subspec without resources

### ISSUE THREAD

**Issue by anna-sakhlyan** [Appboy/appboy-ios-sdk#108]
Hey there,

I have integrated AppBoy into an app via Core subspec. I do not need to use the UI one, since I am doing UI part manually. However, the Core subspec includes sc.resource which imports huge amount of unused resources and makes the app size large. 

Is it possible for you to provide Core subspec without the resources part? This will be great since in case I create my custom podspec, it will not get updated automatically.

Thanks in advance.

**Comment by Wenzhi** [comment]
Hey @anna-sakhlyan,

Thanks for your suggestion! We are currently working on cleaning up the Core subspec to minimize the number of files in the integration, though we don't have a set release timeline right now. I'll comment on this issue as soon as the release time is planned out.

If you need the light weight version sooner, please let us know what's your timeline, and we will try our best to fit in it.

Thanks,
Wenzhi

**Comment by anna-sakhlyan** [comment]
I’ve a temporary solution for this but I’ll greatly appreciate if you’d provide an official fix.
Thanks in advance.

**Comment by joshuafeldman** [comment]
+1 on this. It's silly that to update to the latest Appboy SDK I am required to update SDWebImage to 4.0.0 which is a major release for them and can easily require refactoring. Seems like a poor decision.

**Comment by Wenzhi** [comment]
Hey @anna-sakhlyan, 

We just released the SDK version 2.30.0 which removes the resource bundle from the Core subspec. Could you give it a try? If you still see the bundle resource in the Core subspec, please feel free to reopen this issue, or file a new issue if you have any questions or troubles with the Appboy SDK.

Thanks,
Wenzhi
