### ISSUE TITLE
Where is isAppboyInternalRemoteNotification ???

### ISSUE THREAD

**Issue by tirrorex** [Appboy/appboy-ios-sdk#110]
Appboy sdk v 2.23

Following your documentation i am suppose to track internally whether or not application:willFinishLaunchingWithOptions was triggered by the user or by appboy.
But your documentation doesn't really state how to do that.
It seems there is supposed to be a method called isAppboyInternalRemoteNotification on ABKPushUtils but it is not there.
So, what should i do?

**Comment by Wenzhi** [comment]
Hey @tirrorex ,

The method `isAppboyInternalRemoteNotification` is added to class `ABKPushUtil' in SDK version 2.29.0. You should be able to use it after upgrading the SDK to the latest version.

Please let us know if you still see the issue with the latest version.

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
Hey @tirrorex,

Is this still an issue for you? 

Thanks,
Wenzhi

**Comment by tirrorex** [comment]
Yes, currently doing the migration to swift 3 and preparing the launch in swift 2.3, will update once everything is set.
Don't have the time now to look into this.

**Comment by Wenzhi** [comment]
Hey @tirrorex,

Just following up here - we're fairly certain the updated version will solve this for you.  When you get a chance to test if things aren't working please feel free to re-open.  Closing for now.

Thanks,
Wenzhi
