### ISSUE TITLE
ABKFeedViewControllerDelegate onCardClicked return comment

### ISSUE THREAD

**Issue by sin2** [Appboy/appboy-ios-sdk#111]
In [ABKFeedViewControllerDelegate.h](https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyKit/headers/AppboyKitLibrary/ABKFeedViewControllerDelegate.h), according to the documentation I am supposed to return `YES` if I want Appboy to handle display of the URL. 

However, from my testing this wasn't the case and I had to return `NO`. I just wanted to make sure this is correct, and if so can the documentation be updated.

**Comment by tiffanylu** [comment]
Hi @sin2,

Thank you for raising this to our attention! You are correct: in iOS SDK v.2.29.0 we changed the behavior of the `onCardClicked:feedViewController:` method in `ABKFeedViewControllerDelegate` to let Appboy handle the card click action if the delegate method returns `NO`. This change was made to standardize delegate behavior with `ABKInAppMessageControllerDelegate` and `ABKURLDelegate`.

We've updated our [CHANGELOG](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#2290) and [`ABKFeedViewControllerDelegate.h`](https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyKit/headers/AppboyKitLibrary/ABKFeedViewControllerDelegate.h) to reflect this. Thanks again for opening this issue.

Best,
Tiff
