### ISSUE TITLE
Failing to archive after updating to 2.29.1

### ISSUE THREAD

**Issue by vbrittes** [Appboy/appboy-ios-sdk#112]
I'm using Appboy SDK through Cocoapods, and since I've updated from 2.24.5 to 2.29.1 I'm not able to Archive it anymore. I get a "invalid bitcode version" instead.

Thanks in advance

**Comment by Wenzhi** [comment]
Hey @vbrittes,  

May I ask what version of Xcode are you using? From version 2.29.0, the Appboy iOS SDK requires XCode 8.3. 
If you are using XCode 8.3, could you tell me whether you enable bitcode in your app, and what's your Podfile looks like?

Thanks,
Wenzhi

**Comment by vbrittes** [comment]
I could successfully archive after updating my XCode, thanks for your help.

Cheers
