### ISSUE TITLE
Pulling update for 2.30.0 using Carthage pulls down binary from 2.29.1

### ISSUE THREAD

**Issue by kunal30xi** [Appboy/appboy-ios-sdk#114]
Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | SDK 10.3, deployment target: 9.0
 SDK Version             | 2.29.1
 Integration Method      | carthage
 Xcode Version           | Xcode 8.3.3
 Repro rate              | all the time
 
## What did you do?

Added the following dependency to Cartfile for integration through Carthage.
`github "Appboy/Appboy-iOS-SDK" "2.30.0"`

We are using carthage to pull in the AppBoy iOS SDK. 

## What did you expect to happen?
Framework for 2.30.0 to be pulled down.

## What happened instead?
Framework for 2.29.1 is downloaded instead.

## Steps to reproduce
Add `github "Appboy/Appboy-iOS-SDK" "2.30.0"` to Cartfile
Run `carthage bootstrap platform iOS`
Check APPBOY_SDK_VERSION in `Carthage/Build/iOS/Appboy_iOS_SDK.framework/Headers/Appboy.h`
Also dates/times are from May 11, when they should be from June 16th.

**Comment by Wenzhi** [comment]
Hey @kunal30xi, 

I just updated the Carthage file for version 2.30.0. Could you try to pull it down again and see if the issue still exists?

Thanks,
Wenzhi

**Comment by kunal30xi** [comment]
That was it! Thank you! This ticket can be closed!
