### ISSUE TITLE
Include ABKPushUtils.h in AppboyKit.h

### ISSUE THREAD

**Issue by mathaeus** [Appboy/appboy-ios-sdk#116]
I guess this was just forgotten to be added there? Or is there a reason why it was not added?

**Comment by Wenzhi** [comment]
Hey @mathaeus,

Thank you for informing us! We will add the `ABKPushUtils.h` and all other public headers in the `AppboyKit.h` in the next release. We will let you know when the release comes out.

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
Hey @mathaeus, 

We just released SDK version 2.31.0 with the update in `AppboyKit.h` which should fix this issue. Thanks again for the report! :)

Best,
Wenzhi
