### ISSUE TITLE
Completion handler passed to -[ABKModalWebViewController webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once

### ISSUE THREAD

**Issue by mppray** [Appboy/appboy-ios-sdk#122]
* [x] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11 & 10
 SDK Version             | 3.0.2
 Integration Method      | carthage
 Xcode Version           | Xcode 9
 Repro rate              | 17% of users
 
## What did you do?

Send update notification to mobile app

## What did you expect to happen?

open appstore to update app

## What happened instead?

crash: Fatal Exception: NSInternalInconsistencyException
Completion handler passed to -[ABKModalWebViewController webView:decidePolicyForNavigationAction:decisionHandler:] was called more than once
ABKModalWebViewController.m line 137

## Steps to reproduce

It seems the decisionHandler(WKNavigationActionPolicyCancel / WKNavigationActionPolicyAllow) is called twice in case line 131 **if ([[UIApplication sharedApplication] openURL:navigationAction.request.URL])* succeeds. 

## Code Snippet

- (void)webView:(WKWebView *)webView decidePolicyForNavigationAction:(WKNavigationAction *)navigationAction
decisionHandler:(void (^)(WKNavigationActionPolicy))decisionHandler {
  NSString *urlString = [[navigationAction.request.mainDocumentURL absoluteString] lowercaseString];
  NSArray *stringComponents = [urlString componentsSeparatedByString:@":"];
  if ([stringComponents[1] hasPrefix:@"//itunes.apple.com"]  ||
      (![stringComponents[0] isEqual:@"http"] &&
       ![stringComponents[0] isEqual:@"https"])) {
        // Dismiss the modal web view and let the system handle the deep links
    if ([[UIApplication sharedApplication] openURL:navigationAction.request.URL]) {
      decisionHandler(WKNavigationActionPolicyCancel);
      [self dismissViewControllerAnimated:YES completion:nil];
    }
  }
  decisionHandler(WKNavigationActionPolicyAllow);
}

## Please provide any code snippets that can help us understand or reproduce the issue.

support@appboy.com is our preferred channel for integration issues for several reasons, including: 1) we optimize that channel to solve integration issues so that it is faster and more robust 2) that channel has no risk of leaking sensitive data and integration issues often require logs and other information that could contain private data.

**Comment by Wenzhi** [comment]
Hey @mppray, 

Thanks for letting us know about the issue. The fix will be in our next SDK release, which will be at the end of October. Please let us know if you need the fix before then.

Thanks,
Wenzhi

**Comment by mppray** [comment]
Thanks for the fast reply!

**Comment by Wenzhi** [comment]
Hey @mppray,

Sorry, Github just closed this issue automatically after we merged the fix to the SDK. I'll update this issue thread when the SDK with the fix is released and then I'll close the issue.

Thanks,
Wenzhi

**Comment by jotae85** [comment]
Hi @Wenzhi,

Do you know when this fix is going to be out? I'm getting a lot crashes, specially in the last two days. Is there something we can do to prevent this problem while we wait for the new SDK version?

Thanks,
Juan

**Comment by tiffanylu** [comment]
Hi @jotae85,

We're planning to release the SDK at the end of this month. In the meantime, the code path that causes this crash should only occur if the SDK tries to open a custom scheme deep link inside of our web view (ABKModalWebViewController). To prevent this from happening, you should ensure that all campaigns with deep links are set to use “Redirect to Deep Link” as the click action on the Appboy dashboard. Please let us know if that helps!

Best,
Tiff

**Comment by tiffanylu** [comment]
Hi @mppray and @jotae85,

We just released the fix for this in iOS SDK version 3.1.1. Thanks again for reporting, and please feel free to re-open this issue if the fix isn't working for you.

Best,
Tiff

**Comment by jotae85** [comment]
Thank you @tiffanylu !
