### ISSUE TITLE
Building with Carthage issue

### ISSUE THREAD

**Issue by mppray** [Appboy/appboy-ios-sdk#123]
* [ ] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

We are a growing app that uses AppBoy for multiple proposes.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0
 SDK Version             | 3.0.0
 Integration Method      | carthage
 Xcode Version           | Xcode 9
 Repro rate              | all the time (100%)
 
## What did you do?

*added in the Cartfile (as shown it the Appboy documentation):
github "Appboy/appboy-ios-sdk" "3.0.0"

*and than I run the next terminal command:
carthage update --platform ios --no-use-binarie

## What did you expect to happen?

build AppBoy

## What happened instead?

* Carthage error:
*** Skipped building appboy-ios-sdk due to the error:
Dependency "appboy-ios-sdk" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/Appboy/appboy-ios-sdk/issues/new

## Steps to reproduce

See above ^

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

We just switched from Cocoapods to Carthage

**Comment by Wenzhi** [comment]
Hi @mppray, 

I think the issue can be fixed by not using `--no-use-binaries` in the Carthage command. Could you try it and let us know the result?

Thanks,
Wenzhi

**Comment by mppray** [comment]
Yes it worked! Thanks a lot :)

**Comment by tiffanylu** [comment]
Good to hear, @mppray! Going to close out this issue, as it seems like the problem has been resolved. Free free to reopen if you run into anything else.
