### ISSUE TITLE
Appboy.start(withApiKey:) doesn't always start as expected and causes sharedInstance() to be `nil`.

### ISSUE THREAD

**Issue by AdiAyyakad** [Appboy/appboy-ios-sdk#124]
* [x] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11.0.1
 SDK Version             | 3.1.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | 80% happens
 
## What did you do?

We integrated the latest version of Appboy through Cocoapods and then set up Appboy under `didFinishLaunchingWithOptions` and then called `Appboy.start(withApiKey:...)`. I'll build and launch a new app on a device, subscribe to alerts and then on `didRegister` I get the following after the line `Appboy.sharedInstance().registerPushToken(deviceToken)`:

```
     ********************************************
     **             !! WARNING !!              **
     **     [Appboy sharedInstance] called     **
     **     before Appboy was initialized,     **
     **       returning nil. Please make       **
     ** sure you call [Appboy startWithApiKey] **
     **  before accessing the sharedInstance.  **
     ********************************************
```

## What did you expect to happen?

I expected Appboy to register the device's push token.

## What happened instead?

Appboy's `sharedInstance` was `nil`.

## Code Snippet

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    ....
    let apiKey = apiKey()
    let options = [ABKInAppMessageControllerDelegateKey: self, ABKURLDelegateKey: self]
    Appboy.start(withApiKey: apiKey, in: application, withLaunchOptions: launchOptions, withAppboyOptions: options)
    ...
}
```

```
func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        let deviceToken = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()
        Appboy.sharedInstance()?.registerPushToken(deviceToken)
    }
```

**Comment by Wenzhi** [comment]
Hi @AdiAyyakad,

Could you check if the SDK prints out anything in the console after you call `Appboy.start(withApiKey: apiKey, in: application, withLaunchOptions: launchOptions, withAppboyOptions: options)` and post them here?

Thanks,
Wenzhi

**Comment by AdiAyyakad** [comment]
Hey @Wenzhi,

Thanks for the prompt response. The SDK doesn't print anything out to the console!

Thanks,
Adi

**Comment by Wenzhi** [comment]
Hey @AdiAyyakad,

The SDK should log the error if it's not initialized properly. I wonder if you register for pushes in `didFinishLaunchingWithOptions:` before initializing Appboy? One scenario I can think of is that push registering triggers the `didRegisterForRemoteNotificationsWithDeviceToken` before Appboy is initialized. 

Could you try:
- Check if `Appboy.sharedInstance()` is nil after calling the `start(withApiKey: apiKey, in: application, withLaunchOptions: launchOptions, withAppboyOptions: options)` and log it in the console.
- Run the app and see if the "Appboy is nil warning" shows up before the above log.

Thanks,
Wenzhi

**Comment by AdiAyyakad** [comment]
Hi sorry for the delay.

I've been testing and re-testing and it was pretty consistent that Appboy.sharedInstance was nil at the time. However, I can't seem to recreate it now. After, when I print out the logs, it seems to work.

Thanks for your time,

Sorry for the inconvenience!

Adi
