### ISSUE TITLE
Feature Request: RegisterPushToken as Data 

### ISSUE THREAD

**Issue by dmiluski** [Appboy/appboy-ios-sdk#127]
Problem:
Registering a Device token as String in not intuitive at all

On first inspection of interface, I assumed I needed to initialize a string with encoding. Something like:
```
NSString *str = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
```

Yet, upon viewing the Example
  [[Appboy sharedInstance] registerPushToken:[NSString stringWithFormat:@"%@", deviceToken]];
or in swift
   let deviceTokenString = String(format: "%@", deviceToken as CVarArg)

Instead, perhaps, just expose registerPushToken(_ token: Data) and do whatever transform/manipulation sdk prefers so issues like integration don't get messed up by customers?

* [x] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 8.0
 SDK Version             | e.g. 3.7.6
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 7.3
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once

**Comment by tiffanylu** [comment]
Hi @dmiluski,

Thanks for the suggestion! While our docs provides [sample code](https://www.appboy.com/documentation/iOS/#step-5-register-push-tokens-with-appboy) and our SDK's implementation of `registerPushToken` handles the `token` being passed as `NSData`, I definitely see what you mean about how the method signature could be more intuitive. 

Given that your requested functionality exists within the current method implementation, do you mind if I close this public issue in favor of tracking it internally as an feature request? We'll be sure to prioritize accordingly and keep you updated!

Best,
Tiff

**Comment by tiffanylu** [comment]
Hey @dmiluski,

I'm going to close this issue for now given no movement, but please feel free to re-open if you think it requires revisiting.

Best,
Tiff
