### ISSUE TITLE
Support in App Message for iPhone X

### ISSUE THREAD

**Issue by qclmnt** [Appboy/appboy-ios-sdk#129]
* [X] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11
 SDK Version             | 3.1.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | all the time (100%)
 
## What did you do?

I received in App Message Full Screen on iPhone X Simulator

## What did you expect to happen?

I'm expecting the in app message take place full screen

## What happened instead?

The in app message is only inside Safe Area.
(The view controller where it appears doesn't support safe area for now, if it can help)

## Steps to reproduce

Send a in app message full screen to your app. Inside a view controller that is not supporting safe area for iPhone X ios 11

## Code Snippet

No code snippet needed

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

/

## Project that demonstrates the issue

/

<img width="545" alt="capture d ecran 2017-10-20 a 10 13 56" src="https://user-images.githubusercontent.com/8592324/31811551-3abc2c0e-b580-11e7-815b-deeec8189a42.png">

**Comment by Wenzhi** [comment]
Hi @qclmnt,

It's the default of the full in-app message to display within Safe Area. Given that the Appboy SDK uses custom UIWindow to display the in-app messages, Appboy in-app messages doesn't detect the status of the view controller who displays it.

To display a full-screen in-app message outside of the Safe Area, you can set an in-app message delegate and override the delegate method `beforeInAppMessageDisplayed:`. In that method, you can fetch the in-app message's data model and display the in-app message yourself. Please refer to [our documentation](https://www.appboy.com/documentation/iOS/#customizing-in-app-message-display-behavior) for more detail.

Please let us know if you have more questions.

Thanks,
Wenzhi

**Comment by qclmnt** [comment]
Then it is not anymore a full screen in app message ...

In order to conform iPhone X User Interface Guideline, it would be much appreciate from your customer to follow this : 

> Provide a full-screen experience. Make sure backgrounds extend to the edges of the display, and that vertically scrollable layouts, like tables and collections, continue all the way to the bottom
Source : https://developer.apple.com/ios/human-interface-guidelines/overview/iphone-x/

**Comment by Wenzhi** [comment]
Hi @qclmnt,

Thanks for the suggestion! We released version 2.3.2 which includes some in-app message UI fixes for iPhone X. 

However, the default full in-app message will still show contents in the safe area. If you just want to extend the background color all the way to the top and the bottom, please set the "frame color" to be the same as the background color in your full in-app message campaign and it should solve your issue.
Please let us know if it doesn't work for you or you have any other questions.

Thanks,
Wenzhi

**Comment by XmasRights** [comment]
@Wenzhi 
Sorry to be reviving a dead issue, but can you please provide some guidance regarding how to set the "frame color" parameter.

Also, is there any reason the fix was implemented in this way? Seems to me that not setting the frame color is always undesirable behaviour, and it makes more sense to just lock the view to it's superview instead of the safe area.

**Comment by jefflopes** [comment]
I just started using Braze and ran into this immediately. I agree with @XmasRights. The current defaults don't make a lot of sense to me.
