### ISSUE TITLE
3.2.1 -> not building with App Extension -> Rich Notification

### ISSUE THREAD

**Issue by appcelerate** [Appboy/appboy-ios-sdk#130]
I getting errors by building with 

ABKModalWebViewController.m:30:18: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

and on other places!

I am using Podfile

**Comment by chshapiro** [comment]
Hey @appcelerate,

Are you trying to use our Apppboy-iOS-SDK pod in an app extension? That pod is only compatible with your main app. 
To support rich notifications, please follow our documentation https://www.appboy.com/documentation/iOS/#creating-a-service-extension.

Please let us know if you have any more questions.

Thanks,
Chava

**Comment by chshapiro** [comment]
Hey @appcelerate,

Have you fixed this issue? Please let us know if you don't see this issue anymore or if we can be of any further help.

Thanks,
Chava

**Comment by Wenzhi** [comment]
Hey @appcelerate, 

I'm closing the issue due to lack of activity. Please feel free to re-open it if you still see the issue.

Thanks,
Wenzhi
