### ISSUE TITLE
Getting crash during opening of news feed in version 3.2.2

### ISSUE THREAD

**Issue by ashishsouq** [Appboy/appboy-ios-sdk#134]
* [x] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 8.0
 SDK Version             | e.g. 3.7.6
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 7.3
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 
## Project that demonstrates the issue

[crash.txt](https://github.com/Appboy/appboy-ios-sdk/files/1470804/crash.txt)

**Comment by georgiagh1991** [comment]
Hi there, 

I'm Georgia, your Success Manager here at Appboy. I've been working with members of the Souq team on this issue and have replied to Prakash Gupta on the elements of your NUI styling that are causing this issue. 

Please let me know if you would like to be added to the email thread where we are looking to resolve this 

Best

Georgia
