### ISSUE TITLE
Pre-fetching of in-app message assets

### ISSUE THREAD

**Issue by michaelpace** [Appboy/appboy-ios-sdk#136]
* [√] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

The [Delivery Semantics](https://www.braze.com/documentation/iOS#delivery-semantics) section of the in-app messaging docs says the following:

>Upon delivery, the SDK will pre-fetch assets so that they are available immediately at trigger time, minimizing display latency.

If I am displaying the in-app message in my own UI (by returning `.discardInAppMessage` from `before(inAppMessageDisplayed:withKeyboardIsUp:)`), it seems that I wouldn't benefit from that pre-fetching.

Am I correct in that understanding? If so, is there a way that I could get a reference to the `ABKInAppMessage`s delivered upon app start so that I could pre-fetch the assets myself?

**Comment by Wenzhi** [comment]
Hey  @michaelpace,

You can still be benefitting from the pre-fetching if you don't want to handle the image downloading part. We use the image URL string as the key to store and fetch the image from SDWebImage. You can do the same thing to fetch the downloaded image and display it in your custom in-app message UI. Please check `ABKSDWebImageProxy` class for sample code.

As we don't have public API to expose the in-app messages until they are triggered, there isn't a way for you to pre-fetch the assets yourself right now. Could you share more about your use case and needs?

Thanks,
Wenzhi

**Comment by michaelpace** [comment]
@Wenzhi, thank you! Accessing the image through `ABKSDWebImageProxy` solves my problem.
