### ISSUE TITLE
Possible to not have SDWebImage dependency in InAppMessage subspec?

### ISSUE THREAD

**Issue by sberrevoets** [Appboy/appboy-ios-sdk#138]
With the addition of the InAppMessage subspec, Appboy introduced a dependency on SDWebImage, which wasn't there before. We'd prefer not to install this dependency (which itself has a dependency as well) - is there any chance you can update this new subspec to not have this dependency?

**Comment by Wenzhi** [comment]
Hi @sberrevoets,

The new InAppMessage subspec includes the Braze default in-app message UI, so it needs the SDWebImage and FLAnimatedImage dependencies. 

Could you tell me more about how you are using in-app messages? If you are only getting the in-app message data models and displaying them yourself, you can use the core subpsec to get rid of the dependencies and get the in-app message data by implementing the [beforeInAppMessageDisplayed:](https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyKit/headers/AppboyKitLibrary/ABKInAppMessageControllerDelegate.h#L52) delegate method.

Thanks,
Wenzhi

**Comment by chshapiro** [comment]
@sberrevoets, closing for now. Please reopen the issue if you have any further questions. Thanks!
