### ISSUE TITLE
Appboy-iOS-SDK 3.3.2 does not have i386 as valid architecture

### ISSUE THREAD

**Issue by kunal30xi** [Appboy/appboy-ios-sdk#140]
* [X] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | iPhone 5 Simulator 10.1
 SDK Version             | 3.3.2
 Integration Method      | carthage
 Xcode Version           | Xcode 9.2
 Repro rate              | 100 %
 
## What did you do?

We currently integrate the Appboy-iOS-SDK through Carthage. We were on version Appboy 3.2.3 and were attempting to upgrade to 3.3.2 and ran into a build issue.

`ld: symbol(s) not found for architecture i386`. 
Running `lipo -info Build/iOS/Appboy_iOS_SDK.framework/Appboy_iOS_SDK` of Appboy_iOS_SDK 3.3.2 returns the following architectures: x86_64 armv7 arm64

Running the same command against Appboy_iOS_SDK 3.2.3 returns i386 x86_64 armv7 arm64.

For our app, the minimum deployment target is iOS 10.0 and we still have customers on iPhone 5/5C which is 32 bit. In order for us to run our test suite against the 32 bit architecture and certify our build prior to release we need to be able to link against the i386 architecture as well.

## What did you expect to happen?

Build completes without error.

## What happened instead?

Build fails because it is unable to link against i386 architecture.

## Steps to reproduce

Update carthage dependency to `github "Appboy/Appboy-iOS-SDK" "3.3.2"`

## Code Snippet

n/a

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

n/a

## Project that demonstrates the issue

n/a

**Comment by Bucimis** [comment]
Hi @kunal30xi,

Thanks for raising and apologies for the inconvenience. We've updated our existing `3.3.2` release frameworks to include the `i386` architecture. Updated binaries are available at https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.3.2 as `Appboy_iOS_SDK.framework.zip`.

Please clear your Carthage cache and continue to point to Braze SDK version `3.3.2`. At that point, things should "just work". 

Let us know if the fix works or if you run into issues.

Thanks,
Braze SDK Engineering

**Comment by kunal30xi** [comment]
Hi @Bucimis, cleared Carthage cache `~/Library/Caches/org.carthage.CarthageKit`. Attempts to pull version 3.3.2 of Appboy_iOS_SDK using Carthage hangs. The process hangs indefinitely after attempting to fetch the Appboy-iOS-SDK. All our other dependencies pull down correctly without issue.

```*** No Cartfile.resolved found, updating dependencies
*** Fetching Appboy-iOS-SDK
```

**Comment by kunal30xi** [comment]
👍 Works great. Issue can be closed.

**Comment by shauket** [comment]
Hi, 
This SDK not working on XCode 10.2.1 with iPhone simulator 5 ios 10.0

**Comment by shauket** [comment]
Tried with cocoapod 1.6.1 version and with latest cocoapod version as well.
