### ISSUE TITLE
No Swift support for tvOS

### ISSUE THREAD

**Issue by break2k** [Appboy/appboy-ios-sdk#141]
* [ x ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | tvos
 Platform Version        | 11.2.5
 SDK Version             | 3.2.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.2
 Repro rate              | all the time (100%)
 
## What did you do?

Trying to build the a swift only project with the Appboy tvOS SDK added

## What did you expect to happen?

Project should compile and run on device or simulator. 

## What happened instead?

Compiling works but the processes can not be attached.

## Steps to reproduce

- Add `pod 'Appboy-iOS-SDK'` to the Podspec file.
- Have a Swift only project
- try to run the project after adding the Appboy SDK via Bridging Header because no module can be found if done otherways.

**Comment by briancaw** [comment]
Hi @break2k 

Thanks very much for raising this issue and apologies for the delay.  We've identified the issue and should have a fix out before end of week.  We'll update ASAP with updated timelines and information. 

Thanks,
Braze SDK Engineering

**Comment by Bucimis** [comment]
Hi @break2k,

Our updated `3.3.2` pod should resolve your issue. Please let us know if you're able to build and deploy on your end using `3.3.2`

Thanks,
Braze SDK Engineering

**Comment by Bucimis** [comment]
@break2k closing now, please re-open if this is still an issue for you after updating to `3.3.2`.
