### ISSUE TITLE
No Swift Support for tvOS (2nd iteration)

### ISSUE THREAD

**Issue by break2k** [Appboy/appboy-ios-sdk#143]
As reported in https://github.com/Appboy/appboy-ios-sdk/issues/141
The issue still consists.

* [ x ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | tvos
 Platform Version        | 11.2.5
 SDK Version             | 3.3.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.2
 Repro rate              | all the time (100%)
 
## What did you do?

Trying to build the a swift only project with the Appboy tvOS SDK added

## What did you expect to happen?

Project should compile and run on device or simulator. 

## What happened instead?

Compiling works but the processes can not be attached.

## Steps to reproduce

- Add `pod 'Appboy-tvOS-SDK'` to the Podspec file.
- Have a Swift only project
- try to run the project after adding the Appboy SDK via Bridging Header because no module can be found if done otherways.

**Comment by briancaw** [comment]
Hi @break2k 

The fix is in version 3.3.2 - can you try either updating your spec repo `pod repo update` or updating your Podfile to use 3.3.2 directly `pod 'Appboy-tvOS-SDK', '~> 3.3.2'`?

Thanks,
Braze SDK Engineering

**Comment by break2k** [comment]
We tried to import:
`import Appboy-tvOS-SDK`
`import AppboyTVOSKit`
`import AppboytvOSSDK`
`import AppboyTVOSSDK`

No module found.

**Comment by Bucimis** [comment]
@break2k are you using a bridging header file?

**Comment by Bucimis** [comment]
The bridging header file should `#import <AppboyTVOSKit/AppboyKit.h>`

**Comment by Bucimis** [comment]
@break2k thanks for confirming. You shouldn't need to import anything else at that point, the `Appboy` namespace should already be available to you.

**Comment by break2k** [comment]
Compiles again. Thank you.
