### ISSUE TITLE
Fatal Exception: UIApplicationInvalidInterfaceOrientation iOS 

### ISSUE THREAD

**Issue by jinnamohamed1** [Appboy/appboy-ios-sdk#145]
Fatal Exception: UIApplicationInvalidInterfaceOrientation
preferredInterfaceOrientationForPresentation '(7)' must match a supported interface orientation: 'portrait, landscapeLeft, landscapeRight, portraitUpsideDown'!
-[UIViewController _preferredInterfaceOrientationForPresentationInWindow:fromInterfaceOrientation:]

* [] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11,10
 SDK Version             | 3.3.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.2
 Repro rate              | all the time (100%)
 
## What did you do?
Launched In-App Message campaign through braze dashboard

## What did you expect to happen?
Receive In-App Message on my iOS device

## What happened instead?
After receiving In-App Message on my iOS device. It crashed upon opening the app from the background

## Steps to reproduce

1. Received In-app message on our app
2. Pressed home button without doing any action In-App
3. Opened the app again, then it crashed.

## Code Snippet

Class - ABKInAppMessageWindowController

- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation {
  if (self.inAppMessage.orientation == ABKInAppMessageOrientationPortrait) {
    return self.supportedOrientations & (UIInterfaceOrientationPortrait |
                                         UIInterfaceOrientationPortraitUpsideDown);
  } else if (self.inAppMessage.orientation == ABKInAppMessageOrientationLandscape) {
    return self.supportedOrientations & (UIInterfaceOrientationLandscapeLeft |
                                         UIInterfaceOrientationLandscapeRight);
  }
  return self.supportedOrientations;
}

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

Our app supports only Portrait and mentioned in the info.plist as “UIInterfaceOrientationPortrait” under UISupportedInterfaceOrientations

When I debugged, I found that “preferredInterfaceOrientationForPresentation” function of “ABKInAppMessageWindowController” class returns unsupported interface orientation type on resuming the app from background

**Comment by chshapiro** [comment]
Hi @jinnamohamed1,

By default, our SDK supports all orientations. Because your app only supports Portrait, you are running into this fatal error. To fix this, you can override the `preferredInterfaceOrientationForPresentation`method  and only return the orientation types that you support. 

Please let us know if you have any further questions.

Thanks,
Chava

**Comment by jinnamohamed1** [comment]
Hi Chava

As I have already mentioned in the issue, we have specified "UIInterfaceOrientationPortrait" under UISupportedInterfaceOrientations in info.plist. We didn't have to override the preferredInterfaceOrientationForPresentation method for each and every view controller. 

Is there any way to identify if the current viewcontroller has displayed the in-app message?

Crash happens in the below scenario

 - When we receive an in-app and going to background without dismissing the in-app by pressing home button.
-  Again when we open the app, we show an ad which is a view controller added on top of the app boy in-app message,  when we try to dismiss the ad screen after few seconds, the exception "UIApplicationInvalidInterfaceOrientation" occurs. 

Here I need to fix this by either dismissing the in-app if there is any or not to show the ad screen when there is an in-app in the view controllers stack.

Can you please help on this?

**Comment by artxj** [comment]
Hi @jinnamohamed1,

Thank you again for filing the issue. We have identified a bug that could cause preferredInterfaceOrientationForPresentation to crash. We will release the fix early next week.

Thanks, Artem

**Comment by artxj** [comment]
We have released the fix for this issue in the updated Braze SDK. Thanks for pointing this out!

**Comment by jinnamohamed1** [comment]
Hi
The crash is fixed. But the application view controller stack still has the in-app message overlay on the top. Couldn't do any further action in the application, have to kill and open the app.
