### ISSUE TITLE
Cannot extend ABKNewsFeedTableViewController from swift codebase

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-ios-sdk#151]
I'm trying to override the initialization of `ABKNewsFeedTableViewController` to set `navigationItem.title`. However there is not designated initializer that contains the logic of loading from the appboy storyboard, it's all in `init()` (see: https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyUI/ABKFeedViewController/FeedViewController/ABKNewsFeedTableViewController.m#L16-L22) but that's not overridable.

```
final class CustomNewsFeedVC: ABKNewsFeedTableViewController {
    init() {
        super.init() // not a designated initializer
        super.init(nibName: nil, bundle: nil) // no storyboard logic there
    }
}
```

How do you suggest subclassing in swift for this case?

**Comment by chshapiro** [comment]
Hey @ldiqual,

Can you provide more context as to how you're integrating so we can better investigate this issue? Are you using the NewsFeed subspec or the full SDK? Also, what method are you using for integration and what version of the SDK are you using?

Thanks,
Chava

**Comment by ldiqual** [comment]
We're using cocapods with the full SDK spec:

```
pod 'Appboy-iOS-SDK', '3.5.1'
```

We're subclassing `ABKNewsFeedTableViewController` to migrate away from NUI and customize cards with the table view data source methods. We used to customize with a combination of NUI + `ABKFeedViewControllerModalContext` subclassing.

Let me know if you need anything else

**Comment by ldiqual** [comment]
After looking at the SDK source code, I don't think there is a way to subclass `ABKNewsFeedTableViewController` in Swift. The reason is that the table view controller is backed by a storyboard, but there is no way to subclass view controllers laid out in storyboards unless you apply [this ObjC hack](https://github.com/Appboy/appboy-ios-sdk/blob/master/Samples/NewsFeed/BrazeNewsFeedSample/BrazeNewsFeedSample/CustomFeedTableViewController.m#L14).

What I ended up doing is wrap `ABKNewsFeedTableViewController` in another view controller (as a child), hook on `tableViewController.tableView.delegate`, and forward `UITableViewDataSource` methods from the custom view controller to `tableViewController.tableView`. So composition as opposed to subclassing. It has a chance of breaking if the SDK implements more data source methods, but it works pretty well.

**Comment by matijakregar** [comment]
I'm trying to do the same as @ldiqual described. 

This is basically the same as the `BrazeNewsFeedSample` app in `Appboy-iOS-SDK` Samples, only instead of using Objective-C we like to pretend it's 2018 and want to use Swift.

For the moment I'm using a different kind of hack

```swift
class func construct() -> NewsFeedTableViewController? {
	let vc = ABKNewsFeedTableViewController()
	object_setClass(vc, NewsFeedTableViewController.self)

	guard let newsFeedTableViewController = vc as? NewsFeedTableViewController
	else {
		return nil
	}

	return newsFeedTableViewController
}
```

And instead of `NewsFeedTableViewController()` use `NewsFeedTableViewController.construct()`

**Comment by imbenham** [comment]
Another way around this I found was to just copy the whole storyboard and make a duplicate with different names in my own source. 

`class func getNavigationFeed() -> BrazeNewsFeedController {

        let sb = UIStoryboard(name: "BrazeNewsFeed", bundle: nil)
        let ctlr = sb.instantiateViewController(withIdentifier: "BNFController") as! BrazeNewsFeedController
        ctlr.categories = [.all]

        return ctlr
    }`

This seems to work reasonably well but I agree that this class would be more easily extendable if the storyboard approach was dropped and cell prototype layout was accomplished using nibs.

**Comment by chshapiro** [comment]
Thanks all for sharing your ideas and workarounds. Either of these approaches should work for Swift users hoping to extend ABKNewsFeedTableViewController functionality.

We're going to close this issue. If you have any further questions, feel free to to reopen this issue or open a new issue.

Thanks,
Chava
