### ISSUE TITLE
Cannot access handleCardClick:(ABKCard *)card in Swift

### ISSUE THREAD

**Issue by Stakenborg** [Appboy/appboy-ios-sdk#152]
Implementing the full SDK for version 3.5.1 (or 3.5.0) makes it impossible for Swift to access the `handleCardClick:(ABKCard *)card` method from `ABKNewsFeedTableViewController`.

I assume this also affects the NewsFeed subspec, as it's likely this class is the same, but I haven't checked.

Because the method isn't defined in the header interface, it can't be accessed in a Swift implementation. In your [example](https://github.com/Appboy/appboy-ios-sdk/blob/master/Samples/NewsFeed/BrazeNewsFeedSample/BrazeNewsFeedSample/CustomFeedTableViewController.m#L6), you create a category in Objective-C to expose the method. If this method is to be overriden by clients using the SDK, it should be exposed in the header without the need of a category.

In your example it _works_, but is essentially a **dangerous** hack to expose the `handleCardClick` method. This is demonstrable by simply changing the implementation method on `ABKNewsFeedTableViewController` from `handleCardClick` to `testCardClick` and seeing that the example still builds, but the category and method `handleCardClick` in the subclass no longer function.

I would recommend reverting this to a protocol, which is likely where it belongs to begin with. In my implementation I have no reason to know about what is going on with the news feed other than a card being clicked, so a subclass is a bit overkill as I'd just be using it to fire off a call to a delegate anyway. If everything is dead set on requiring a subclass for some reason, please expose the method in the class interface header.

**Comment by chshapiro** [comment]
Hey @Stakenborg,

We will be exposing the method in the class header. This will be available in the next release coming in the next few weeks.

Please let us know if you have any further questions.

Thanks,
Chava

**Comment by chshapiro** [comment]
Hey @Stakenborg,

We released version 3.6.0 of the SDK which exposes this method in the class header.
Feel free to reopen this issue if you have any further questions.

Thanks,
Chava

**Comment by thepinyo** [comment]
@chshapiro how to custom handle card click, I think you change handle event to delegate. because I need to add your subview in my controller and handle the event by delegate. right now, your library it's hard to use.

**Comment by thepinyo** [comment]
@Stakenborg how you handle card click in swift? can you show example project for me?
