### ISSUE TITLE
Feature request: Being able to do simple font customization on IAM controllers

### ISSUE THREAD

**Issue by eriksundin** [Appboy/appboy-ios-sdk#154]
# Report

In order to do simple customisation of existing In App Message UI, like updating the fonts, currently you need to update a `#define` directive in `ABKInAppMessageViewController.h`

```
// Customize this to set the font for the in-app message message.
#define MessageLabelDefaultFont [UIFont fontWithName:@"Avenir-Medium" size:14.0]
```

or - you need to provide your own fully custom IAM controller.

It would be nice to be able to provide custom fonts in a less intrusive way, by configuration for example. So if you're happy to use the provided view controllers for IAM:s it's just a simple theme:ing callback.

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 SDK Version             | 3.5.1
 Integration Method      | cocoapods

**Comment by Bucimis** [comment]
Hi @eriksundin,

Thanks for filling this issue. While macros and subclassing are our current recommended (post-NUI :P) ways of customizing message font, improving that integration is one of our product priorities over the coming months. Closing this issue for now, but we'll be in further touch as we have more information.

**Comment by lindanordstrom** [comment]
@Bucimis Hey - what's the status on this?

**Comment by Bucimis** [comment]
Hi @lindanordstrom this is still on our product roadmap, but it's been incorporated into a more holistic overhaul of in-app messages. We'll have more details as we're able to release them but for now the workarounds in the original post are still recommended.

**Comment by hiyahiyao** [comment]
Hi @Bucimis , any news about this one ?

**Comment by Bucimis** [comment]
@hiyahiyao thanks for checking in - the previous post is still current. This is on our roadmap but we don't have a release date yet.
