### ISSUE TITLE
In-App Messages not displayed while app is in foregorund.

### ISSUE THREAD

**Issue by cojoj** [Appboy/appboy-ios-sdk#156]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10
 SDK Version             | 3.2.3
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | all the time (100%)
 
## What did you do?

On Braze's website I went to create new IAM Campaign, filled everything. In the meantime I've opened app on my device, so it stays in foreground. After that I've pressd **send test** button on the website.

## What did you expect to happen?

I expected opening the IAM automatically on the screen, so the user won't have to take any additionl action to see it's content.

## What happened instead?

Native push notification dialog was presented:
1. After tapping on it IAM was presented
2. If I didn't react IAM was presented on the nex app run/becoming active

## Steps to reproduce

1. end sample IAM to the application.

## Code Snippet

I know I should be handling this delegate's method in order to have the trigger point, but if I pass here `[]` or don't call completion block at all than I won't receive anything.
```swift
func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
    completionHandler(.alert)
}
```

**Comment by chshapiro** [comment]
Hey @cojoj ,

The test in-app message gets sent through a push notification, so the expected behavior is that you will need to click the push in order to see the in-app message when your app is open.

Please let us know if you have any further questions!

Thanks,
Chava

**Comment by cojoj** [comment]
Hello @chshapiro,

So, what you're saying is that if I create actual campaign the IAM will be delivered without the need to tap on push notifiaction?

**Comment by chshapiro** [comment]
Yes, only the test in-app messages are delivered through a push notification.

**Comment by cojoj** [comment]
Awesome, thank you very much @chshapiro. We can close this issue, as it's no longer relevant, but please add this info to your docs, as it may be confusing for others (as it was for me).

Have a great weekend!

**Comment by AnswerX** [comment]
Hello @chshapiro , 
 In-App Message displayed until clicked alert while app is in active,
how can i know the notification is In-App Message from `userNotificationCenter:willPresentNotification:withCompletionHandler:`
because I don't want alert while the notification is In-App Message

**Comment by Bucimis** [comment]
Hi @AnswerX, are you referring to push notifications or in-app messages? That delegate is a push notification delegate and won't be fired at any point in the in-app message flow

**Comment by AnswerX** [comment]
Hi @Bucimis, it's in-app message, but i have to click alert banner first then i can see in-app message,i don't want alert banner
<img width="440" alt="alert@2x" src="https://user-images.githubusercontent.com/15908913/57744075-400ce800-76fa-11e9-898c-b55a29b1c84d.png">
<img width="440" alt="in-app message" src="https://user-images.githubusercontent.com/15908913/57744087-4602c900-76fa-11e9-8347-2b6615b55172.png">

**Comment by Bucimis** [comment]
@AnswerX those push notification banners only appear when sending Test messages. When actually sending the campaign after navigating through the targeting/segmentation flow, the in-app messages will be displayed without banner notifications appearing at the top.

**Comment by AnswerX** [comment]
Thank you ! @Bucimis

**Comment by AnYiFu** [comment]
@Bucimis  excuse me,Send to Production,the in-app messages can not show as soon as i click the send.restart the app can show it.I want to know how to slow it

**Comment by Bucimis** [comment]
@AnYiFu in-app messages are refreshed by the SDK at session start, which is why you need to background the app after hitting "send" in the campaign composer to see the newly sent messages.

**Comment by AnYiFu** [comment]
think you! @Bucimis That meens I can not see the newly messages as soon as I click the send Isn't it? or have other idea to solve it.

**Comment by Bucimis** [comment]
@AnYiFu currently that's the limitation. You'll need to start a new session by changing user on the SDK or backgrounding/foregrounding before you can see the new messages.

**Comment by AnYiFu** [comment]
@Bucimis Thank you

**Comment by shuzootani** [comment]
@Bucimis is there any schedule for making foreground inApp messaging work?

**Comment by shuzootani** [comment]
thank you @chshapiro 
>  just set up a campaign that triggers off of a session start.

that means all I have to do is create a campaign that triggers off of a session start on dashboard?
Do you care to tell me more about how to do this or any docs?

**Comment by hokstuff** [comment]
Hi @shuzootani,

Yes, you have to create a campaign that triggers off `session start` on the Dashboard and make sure your user is being targeted for the campaign. It is under the `Delivery` tab in the "Create Campaign" flow when you select a new trigger action. Once the campaign is successfully running and your integration is working, the in-app message should be displayed immediately after you launch your app.

Best,
Daniel

**Comment by shuzootani** [comment]
Thanks @hokstuff 
> the in-app message should be displayed immediately after you launch your app.

Let me clarify my question,
Should it be displayed without backgrounding the app while the app is in foreground?

I can see that it's displayed immediately after launching the app, yet I need to background the app and foreground it again to display in-app message. Is that expected behaviour?

**Comment by chshapiro** [comment]
Hey @shuzootani,

What you are seeing is indeed the expected behavior. If you launch a campaign while you have the app open, you will need to background the app and foreground it again in order to display that particular in-app message. We request the in-app messages from the server at the time that the app is opened.

Please let us know if you have any further questions.
Thanks!

**Comment by shuzootani** [comment]
@chshapiro Thanks for answering.
Is there any official way to display in-app message immediately while the app is in foreground without backgrounding the app?

**Comment by chshapiro** [comment]
Hey @shuzootani,

At this time we don't offer that functionality. Can you tell me a little more about your use case? 

Thanks!

**Comment by postmechanical** [comment]
@chshapiro I cannot find anywhere in the docs (https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/overview/) that clearly states that test in-app message sends are sent via push notification and that regular campaign in-app message sends are not. It would be very much appreciated if that very important distinction could be documented clearly.
