### ISSUE TITLE
Error compressing PNG files

### ISSUE THREAD

**Issue by J-Mendes** [Appboy/appboy-ios-sdk#158]
Hi, 

After the update to SDK version 3.8.1 the Xcode is generating an error while compiling saying that the PNG file compressing has encountered an error. 

<img width="1366" alt="screen shot 2018-08-07 at 20 06 13" src="https://user-images.githubusercontent.com/22790910/43797092-22aa1a66-9a7e-11e8-9084-33b5f7f77476.png">

I've found that you have images replicated on 
- AppboyUI/ABKContentCardsViewController/ContentCards_Resources/images/ AppboyUI/ABK
- FeedViewController/Feed_Resources/images

**Comment by artxj** [comment]
Hi, 

Thank you for reporting this! We're investigating the issue. Meanwhile, could you check whether navigating to your main app project in Xcode -> `Build Settings` tab and setting `Compress PNG Files` to `No` solves the issue?

Best, Artem

**Comment by J-Mendes** [comment]
This change alone doesn't solve the issue, I have also set to `No` the `Remove Text Metadata From PNG Files` in order to clear the error.

Thank you

**Comment by Mildwhale** [comment]
<img width="1761" alt="appboy build error" src="https://user-images.githubusercontent.com/3113810/43821960-90c005e0-9b25-11e8-957d-5cc84527ccc4.png">

Hi

I've a same error.
@artxj solution not worked.

**Comment by repomies** [comment]
I have a different PNG-related error. Has happened multiple times over the past two days, and _Clean build folder_ and rebuild seems to resolve it temporarily.
<img width="1168" alt="screenshot 2018-08-08 19 09 40" src="https://user-images.githubusercontent.com/1328614/43849665-a319ae44-9b3e-11e8-94a0-bd5cff796cb6.png">

**Comment by ScottAtIntuit** [comment]
Also running into the same error that repomies reported

**Comment by artxj** [comment]
Hi,

We released version 3.8.2 of the SDK which should resolve this issue.
Feel free to reopen the issue if it recurs.

Thanks, Artem
