### ISSUE TITLE
fatal error: 'AppboyKit.h' file not found

### ISSUE THREAD

**Issue by vitorreis** [Appboy/appboy-ios-sdk#159]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

React Native ios SDK
 
## What did you do?
I am trying to install the ios sdk in a react native app, I'm not an ios programmer sorry if I am missing something obvious in here.

## What did you expect to happen?

I followed all the steps provides by the docs, however I am not sure about the step
>Update the ‘Header Search Paths’ in the AppboyReactBridge Xcode project to reference the headers directory of your installation of the Braze iOS SDK.

I've added the value `$(SRCROOT)/../node_modules/react-native-appboy-sdk/iOS/AppboyReactBridge` to the header search paths, I believe something is wrong here and that's the source of the problem as mentioned in https://github.com/Appboy/appboy-react-sdk/issues/5#issuecomment-260162166

## What happened instead?

I get a compilation error 
```
node_modules/react-native-appboy-sdk/iOS/AppboyReactBridge/AppboyReactBridge/AppboyReactBridge.m:4:9: fatal error: 'AppboyKit.h' file not found
#import "AppboyKit.h"
```

## Steps to reproduce

- `npm run ios`

## Project that demonstrates the issue

https://github.com/vitorreis/react-native-braze-sdk-app
this is the commit that adds the references in the xcode project (following the available docs)
https://github.com/vitorreis/react-native-braze-sdk-app/commit/6db5d3015fcb3666868df033a2d3320afe52d8b6

**Comment by Bucimis** [comment]
Hi @vitorreis,

Please make sure:
1) You've run `pod install` from the `ios` directory of your project (This will download the SDK, including its headers)
2) You have `"${PODS_ROOT}/Headers/Public/Appboy-iOS-SDK"` with `recursive` enabled in your `Header Search Paths’ (This will enable XCode to find the headers from within the pod and tie the native SDK code to the `AppboyReactBridge` code)

**Comment by vitorreis** [comment]
That seems to have worked, thanks

**Comment by cooperjbrandon** [comment]
Is there a way to fix this without doing `pod install`? I'm not using pods in my current react-native project, so to have to start using pods for this one specific library is kind of a pain.

Seems kind of funky that the normal way of linking a react-native library doesn't work.

**Comment by chshapiro** [comment]
Hey @cooperjbrandon,

You are not required to use Cocoapods to use our SDK for React. You  can follow the instructions under the section "iOS without podfile". (https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/ios/sdk_integration/#step-1-get-the-sdk)

Please let us know if you have any further questions.

Thanks,
Chava

**Comment by cooperjbrandon** [comment]
thanks chava.

Unfortunately that's still not working. Even after adding `$(SRCROOT)/AppboyKit/headers/AppboyKitLibrary` into Header Search Paths (note this step isn't in the docs, just trying to do different things to make it work), the error still occurs.

**Comment by Bucimis** [comment]
@cooperjbrandon it appears the Braze iOS library isn't present locally in your project. 

Typically we encourage integrators to use the Cocoapods package manager to handle adding the Braze iOS library seamlessly. You may alternatively install the Braze SDK using the manual integration instructions here https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/manual_integration_options/?redirected=true (See Step 1 of `iOS without podspec` https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/ios/sdk_integration/#initial-sdk-setup).

In essence, the Braze React Native iOS SDK is a small project that depends on the main Braze iOS library. All integration paths require the Braze iOS library to be installed somehow, either through Cocoapods or manually (or potentially through Carthage, if you'd like to try that).

**Comment by cooperjbrandon** [comment]
using pods, the file `AppboyReactUtils` throws a build error because it can't find the `React/RCTLog.h` file. Is there another step in the podfile that I need to take that allows Appboy-ios-sdk to use the react pod? I don't see any documentation that would help me with this.

**Comment by Bucimis** [comment]
Hey @cooperjbrandon, does your project refer to `React.xcodeproj` in its `Libraries` section? When creating a new React Native project, React should automatically take care of linking relevant Xcode projects - see screenshot:
<img width="261" alt="screen shot 2018-12-12 at 12 56 52 pm" src="https://user-images.githubusercontent.com/1174698/49888658-8a1d3500-fe0d-11e8-8869-90c6a5e9bd3c.png">
