### ISSUE TITLE
object_setClass to subclass ABKNewsFeedTableViewController can cause issues

### ISSUE THREAD

**Issue by Stakenborg** [Appboy/appboy-ios-sdk#160]
Attempting to subclass `ABKNewsFeedTableViewController` is not possible in a safe way due to it's initialization via storyboard.

In your [example](https://github.com/Appboy/appboy-ios-sdk/blob/master/Samples/NewsFeed/BrazeNewsFeedSample/BrazeNewsFeedSample/CustomFeedTableViewController.m#L6), we see `object_setClass` invoked to change the `isa` pointer of the class at runtime. I assume this was done to resolve the need to pull the class out of a storyboard, but using this can cause undefined behavior and crashes.

Since we're altering the `isa`, we can't be sure the correct amount of memory has been allocated to the class. If no properties or ivars are added it will _probably_ work, but once you start doing anything else you're staring into a void of weird KVO issues and `EXC_BAD_ACCESS` stuff.

I was able to show an example of what could happen by altering your [example](https://github.com/Appboy/appboy-ios-sdk/blob/master/Samples/NewsFeed/BrazeNewsFeedSample/BrazeNewsFeedSample/CustomFeedTableViewController.m#L6) somewhat.

If we add a couple new `UIView` properties like so:

```
#import "AppboyNewsFeed.h"

@interface CustomFeedTableViewController : ABKNewsFeedTableViewController

@property (nonatomic) UIView *oneView;
@property (nonatomic) UIView *twoView;

@end
```

Then initialize them:

```
- (instancetype)init {
  self = [super init];
  object_setClass(self, [CustomFeedTableViewController class]);
  self.oneView = [[UIView alloc] init];
  self.twoView = [[UIView alloc] init];
  return self;
}
```

You should wind up with an `EXC_BAD_ACCESS` on initialization (this is a bit of an inexact science, but it was reproducing for me consistently vs. the iPhone SE simulator on Xcode 9.4.1)

If you move the initialization of the views above the `object_setClass` call like this:

```
- (instancetype)init {
  self = [super init];
  self.oneView = [[UIView alloc] init];
  self.twoView = [[UIView alloc] init];
  object_setClass(self, [CustomFeedTableViewController class]);
  return self;
}
```

You get a crash because at this point the class is still `ABKNewsFeedTableViewController` and has no idea about these properties.

Finally, as a sanity check, if we drop the `[super init]` and instead use the default initializer `[super initWithStyle: UITableViewStylePlain]` as follows:

```
- (instancetype)init {
  self = [super initWithStyle: UITableViewStylePlain];
  object_setClass(self, [CustomFeedTableViewController class]);
  self.oneView = [[UIView alloc] init];
  self.twoView = [[UIView alloc] init];
  return self;
}
```

Everything works as expected (note, `object_setClass` here is irrelevant since the class knows what it is the entire time, I just left that in for consistency).

I only really see two solutions for this. One would be removing `ABKNewsFeedViewController` from the storyboard and exposing the custom initialization so it can be accessed via subclasses. The other would be to add a protocol to kick out information around the `handleCardClick` method (similar to what was in 3.4.0).

**Comment by chshapiro** [comment]
Hey @Stakenborg,

Unfortunately we were not able to reproduce the issue you are describing - the first way you tried of setting the view after calling `object_setClass` works fine with no crashes. Can you provide more information about how you're integrating?

Thanks,
Chava

**Comment by Stakenborg** [comment]
Hey @chshapiro,

I'm not sure how you implemented your attempt to reproduce this issue, but the key thing to know is that the initialization is allocating the amount of memory necessary for `ABKNewsFeedTableViewController`. `object_setClass` is not going to change the allocated memory, so properties and ivars on `CustomFeedTableViewController` in this instance are not accounted for from a memory perspective. It _might_ work, but you're basically hoping that enough memory was allocated to the `ABKNewsFeedTableViewController` object to handle whatever is added to `CustomFeedTableViewController`.

That is, if only one `UIView` property isn't causing an issue, add one or two or ten more, you should run into trouble eventually. I was also unable to get it to have an issue with just one UIView property, but two did the trick as shown in my example code.

I've added a video showing before (working) and after (crashing) effects of adding and initializing two `UIView` objects in your example code. Bear in mind, I changed the `Podfile` to point to production (the local path it was looking for doesn't exist anyway) so it's using 3.8.3 via Cocoapods.

Here's the [video](https://drive.google.com/file/d/1sIdehqlW-rndMnsxayJGIp6sEBGb1j_q/view?usp=sharing).

As you can see, the crash occurs on the initialization of the **second** `UIView` object.

Let me know if you need any more information from me.

Thanks,

-Brandon

**Comment by Bucimis** [comment]
Hi @Stakenborg,

Thanks for the followup. We generally don't recommend adding additional views when subclassing `ABKNewsFeedTableViewController`, merely changing behaviors of existing methods, such as `handleCardClick`, or adding simple properties. Could you provide us with more particulars on your use case? We may be able to provide a recommendation or workaround.

**Comment by Stakenborg** [comment]
Hey @Bucimis,

The views were just an example, the issue is by changing the `isa` pointer you're only allocating enough memory to handle the parent object, not whatever else is in the subclass. Technically any additional properties added could cause a crash depending on how much memory you're using on that object. Debugging this could be a real pain too because you're not going to get a ton out of the crash logs. 

The `isa` pointer should never be touched for a simple subclass, it's too dangerous and it's not for that.

As for my use case, I have the news feed as part of a `UIPageViewController`. Because of this, I don't want it handling any navigation from the card clicks, I want to bubble that up to the parent class. Ideally I'd do this via delegation, but that was removed in 3.4.0.

I think an easy workaround would be to fire off a notification with the constant you'd be using exposed in the header, but would ideally prefer a delegate solution that would be checked before performing the default `handleCardClick` behavior.

**Comment by tbelote** [comment]
With 4.2.0 you can now subclass the content cards and newsfeed table view controllers as well as table view cells. You can now either directly call alloc and init or use your own storyboard. See the release notes and updated docs for more details.

**Comment by Bucimis** [comment]
Hi @Stakenborg, just a heads up that we have a crashing iOS Content Cards regression in 4.2.0. If you are not using our out-of-the-box Content Cards UI, you won't be affected, but otherwise please stand by for a patch release coming in the next few days.
