### ISSUE TITLE
AppBoy (In-App-Message) WindowLevel not friendly to App Lock screen

### ISSUE THREAD

**Issue by dmiluski** [Appboy/appboy-ios-sdk#163]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report
In general, we try to keep all of our app window's below the status bar to maintain user ability to see the clock (to not require to leave the app) even if our lock screen is on display.

Recently, we found that an In-App Message was showing over our lock screen when returning to our app and was seeing if this could be configurable? Or to better understand why the In-App Message window was so high? Why did it need to be over the status bar?

https://github.com/Appboy/appboy-ios-sdk/blob/6d42abf665cd3e2bfeccd7ef25fea74657ff3bbd/AppboyUI/InAppMessage/ViewControllers/ABKInAppMessageWindowController.m#L31

Otherwise, if there is a way that we can opt out of displaying during this time?
Our lock screen is displayed on Window level:
```
    static let LockScreen: UIWindow.Level = UIWindow.Level.statusBar - 1
```
## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 8.0
 SDK Version             | e.g. 3.7.6
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 7.3
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once

**Comment by chshapiro** [comment]
Hey @dmiluski,

What version of the SDK are you using? As you can see in the [Changelog](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#changed-2), in version 3.8.0 we made a change that in-app messages don't obscure the status bar.

Thanks,
Chava

**Comment by dmiluski** [comment]
I'm currently using:
"3.3.2"


But reading:
https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyUI/InAppMessage/ViewControllers/ABKInAppMessageWindowController.m#L31

off of master, I'm assuming this is still referencing status + 1? I can also experiment with Appboy delegate, which is what I'm currently looking into:
```
extension AppCoordinator: ABKInAppMessageControllerDelegate {
    func before(inAppMessageDisplayed inAppMessage: ABKInAppMessage) -> ABKInAppMessageDisplayChoice {
        // Show later if showing LockScreen?
    }
}
```

**Comment by dmiluski** [comment]
Actually, now that I think about it, I'm still in a bit of a pickle. If a campaign is to appear after launch, but there is a peace case until user resolves their lock screen, when is it appropriate to let Appboy know it's okay again? Or does it retry after x seconds?

**Comment by chshapiro** [comment]
@dmiluski,

Did you figure out how to customize to fit your use case?

Thanks,
Chava

**Comment by dmiluski** [comment]
Not Quite @chshapiro , I'm stepping through how to setup the AppBoy delegate.

We're currently integrating with:
Appboy_iOS_SDK, with helper sdk (mParticle_Appboy)

Which means, by linking alone, our mParticle configurations drive and create the reporting Apply instance. Upon reading that though, I'm not sure how to configure a ABKInAppMessageControllerDelegate given the helper framework sets that up?

Is there a way to configure for this sort of scenario so we can apply our own custom handling?

**Comment by chshapiro** [comment]
Hey @dmiluski,

The delegate can be set once the Appboy instance is created. See https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/customization/#in-app-message-controller-delegate for details.

Thanks!
Chava

**Comment by dmiluski** [comment]
Thanks, experimenting now

**Comment by dmiluski** [comment]
Hi @chshapiro ,

I've been trying but still unsuccessful at integrating with a delegate.

Given we integrated AppBoy, with mParticle helper:
https://github.com/mparticle-integrations/mparticle-apple-integration-appboy

I attempted to leverage MPKitAppboy
```MPKitAppboy.setInAppMessageControllerDelegate(self)```

But I haven't been getting delegate callbacks via:
```
extension AppCoordinator: ABKInAppMessageControllerDelegate {
    func before(inAppMessageDisplayed inAppMessage: ABKInAppMessage) -> ABKInAppMessageDisplayChoice {
        switch authenticationQueue.operations.isEmpty {
        case true: return ABKInAppMessageDisplayChoice.displayInAppMessageLater
        case false: return ABKInAppMessageDisplayChoice.displayInAppMessageNow
        }
    }
}
```

**Comment by dmiluski** [comment]
Note ^ This style was suggested after I attempted to use the swift style mentioned in AppBoy docs (similar to objective-c), which Xcode mentioned similar, but not the same as delegate .... which I then tapped to autoUpdate to what's in the comment above.

So far, I'm not getting a delegate callback

**Comment by chshapiro** [comment]
Hey @dmiluski,

Can you try setting the delegate natively without setting it through mParticle by just using the line `Appboy.sharedInstance().inAppMessageController.delegate = self` from the documentation I linked above?

Thanks,
Chava

**Comment by dmiluski** [comment]
Hi Chava,I tried that as well without success. 

Upon investigating I noticed that the shared instance of appBoy is not yet initialized at the time I attempted to set it? With a big visible note in the console as feedback.

Likely, i’m Assuming, this is setup eventually after the mParticle Config is downloaded after <t> time per that helper sdk

**Comment by dmiluski** [comment]
@chshapiro in the event you are also familiar with the mParticle integration?
https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/pull/20

As I'm not sure of a hook for setting at some other time?

**Comment by dmiluski** [comment]
Okay, so I'm observing the delegate now by updating that delegate on kit notification. But now I'm also looking to dismiss any message given we are about to lock.

        `Appboy.sharedInstance()?.inAppMessageController.inAppMessageUIController?.hideCurrent(inAppMessage: true)`
![Uploading Screen Shot 2018-11-07 at 9.52.25 AM.png…]()

The swift api transition here isa. bit weird so perhaps I'm missing something?

**Comment by dmiluski** [comment]
Turns out all of the protocol methods for iinAppMessageUIController were optional, which was why swift threw up.

Able to solve by:
```
Appboy.sharedInstance()?.inAppMessageController.inAppMessageUIController?.hideCurrent?(inAppMessage: true)
```

**Comment by Bucimis** [comment]
@dmiluski thanks for following up - confirmed on our end that that's correct

**Comment by chshapiro** [comment]
Hey @dmiluski,

Have you solved this issue?

Thanks,
Chava

**Comment by dmiluski** [comment]
Yes and no. I can now dismiss a message if lock screen is presented, or delay until after a lock screen is dismissed.

Unfortunately, that has still left us in a bit of a situation in which upon showing:
1. Even if a user doesn't take an action, it's recorded as an impression (even though it may be difficult for them to see or retry that event again)
2. Given we delay presenting if there is event, a user would still need to trigger that event again elsewhere. As to when that was, it leaves us in a strange position where early launch events could be problematic to trigger against.

**Comment by chshapiro** [comment]
Hey @dmiluski,

As we've solved your original issue and this thread is getting very specific to your custom integration, I would suggest that we close this issue and you can email support@braze.com with your questions and we can help you that way.

Thanks,
Chava
