### ISSUE TITLE
wiping user data and creating new instance

### ISSUE THREAD

**Issue by gasparuff** [Appboy/appboy-ios-sdk#166]
In my app I have a function which deletes the user's account. On invocation, I'm calling `Appboy.wipeDataAndDisableForAppRun()` and then I show the regular login screen of the app again. But now I want to create a new Braze session, which I usually did in the appdelegate by calling `Appboy.start(...)` passing the arguments that I get in my Appdelegate's `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool`. But in my case, I want to invoke this manually. I know how I can get the `UIApplication` singleton, but what about the `launchOptions`? Shall I just pass nil in that case? Since there is no way of invoking the `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool` manually.

**Comment by Bucimis** [comment]
Hi @gasparuff, thanks for getting in contact. As far as our SDK is concerned, its safe to call `Appboy.start(...)` with a null `launchOptions` object, as long as you pass in a valid API key and all relevant appboy options.

**Comment by Bucimis** [comment]
@gasparuff closing now - feel free to open another issue if necessary
