### ISSUE TITLE
Braze News Feed Cards - logCardImpression

### ISSUE THREAD

**Issue by pangers** [Appboy/appboy-ios-sdk#169]
Hi, I am building a custom Braze News Feed using both the iOS and Android SDKs for their respective platforms. I have a question around the method `ABKCard.logCardImpression()`. As can be seen in the iOS Example [here](https://github.com/Appboy/appboy-ios-sdk/blob/9cb272c9b7b560fb9b5a58c08f58de01930a9cb5/AppboyUI/ABKFeedViewController/FeedViewController/ABKNewsFeedTableViewController.m#L165), the card logs an impression in the `UITableViewDatasource.willDIsplayCell` method, which means every time the cell goes off screen and comes back into view, an impression will be logged for it.

However, looking at the Android example [here](https://github.com/Appboy/appboy-android-sdk/blob/9b445008c4d588d7e99a79865a9566507043ff43/android-sdk-ui/src/com/appboy/ui/adapters/AppboyListAdapter.java#L32), it explains that a card should only log an impression **once**, until the ListView is closed and reopened again.

Was this discrepancy intentional? Or does the iOS SDK do something internally in `ABKCard.logCardImpression()` that will only log an impression once for a card, no matter how many times the card is viewed?

Thanks for the clarification

**Comment by chshapiro** [comment]
Hey @pangers,

This discrepancy does indeed exist and is a long-standing one. This isn't necessarily the case for a custom integration, and we suggest implementing consistency with Android in a custom integration.

Please let us know if you have any further question.

Thanks,
Chava

**Comment by hokstuff** [comment]
Hey @pangers,

We have made the impression behavior on iOS consistent with Android in our recent release. You can find it [here](https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.12.0).

Thanks!
Daniel
