### ISSUE TITLE
ABKNewsFeedCardStoryboard.storyboard Misplaced View Warnings 3.11.0

### ISSUE THREAD

**Issue by mcevob** [Appboy/appboy-ios-sdk#174]
* [X] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12
 SDK Version             | 3.11.0
 Integration Method     | cocoapods
 Xcode Version           | Xcode 10
 Repro rate              | all the time (100%)
 
## What did you do?

Integrated Braze via Cocoapods

## What did you expect to happen?

Braze storyboards do not have misplaced views

## What happened instead?

ABKNewsFeedCardStoryboard.storyboard has misplaced views. 
- See `News Feed Scene > Table View > ABKNFCaptionedMessageCardCell > Content View > Root View > Description` (in Interface Builder)
- See `News Feed Scene > News Feed > View` (Connection Error View)

## Steps to reproduce

1) Add `pod 'Appboy-iOS-SDK'` to `Podfile` (issue observed on v3.11.0 of SDK)
2) Run `pod install`
3) Open `ABKNewFeedCardStoryboard.storyboard`
4) Observe the misplaced view error in the News Feed Scene

## Code Snippet

N/A

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No related customizations

## Project that demonstrates the issue

Version 3.11.0 of the SDK

## Potential Resolution

The first issue can be resolved by increasing the `Vertical Content Hugging Priority` on the description label to 251 or above.

The second issue can be resolved by running the `Update frames` command on the view

**Comment by Bucimis** [comment]
Hi @mcevob, thanks for filing this issue and apologies for our late response. We're currently investigating this issue and we'll let you know when we have an update. In the meantime, to get rid of the warning, you can update the code directly or submit a pull request.

**Comment by hokstuff** [comment]
Hey @mcevob,

We just implemented the fix that you described and you should see it in our next release. Thanks!
