### ISSUE TITLE
no new line symbol in German translation text

### ISSUE THREAD

**Issue by Speakus** [Appboy/appboy-ios-sdk#175]
please change inside:
Pods/Appboy-iOS-SDK/AppboyUI/ABKNewsFeed/Resources/de.lproj/AppboyFeedLocalizable.strings

from
"Appboy.feed.no-card.text" = "Derzeit sind keine Updates verfügbar. Bitte später noch einmal versuchen.";

to
"Appboy.feed.no-card.text" = "Derzeit sind keine Updates verfügbar.\nBitte später noch einmal versuchen.";

(replace space to new line symbol)

English version is fine already.
Thanks

**Comment by Bucimis** [comment]
Hi @Speakus, thanks for bringing this to our attention. These will be fixed in our next release.

**Comment by Bucimis** [comment]
@Speakus this is now released!
