### ISSUE TITLE
Cocoapods 1.6.1 fails with Appboy-Push-Story

### ISSUE THREAD

**Issue by pangers** [Appboy/appboy-ios-sdk#177]
* [Yes ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.1
 SDK Version             | 3.12.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.1
 Repro rate              | all the time (100%)

## What did you expect to happen?
Project to compile successfully

## What happened instead?
Project compilation failed

## Steps to reproduce
1) Have `Appboy-iOS-SDK` and `Appboy-Push-Story` installed in project via Cocoapods 1.5.2
2) Update Cocoapods to 1.6.1
3) Run `pod install`
4) Compile project
5) Error occured
![screen shot 2019-02-23 at 5 51 16 pm](https://user-images.githubusercontent.com/7816958/53283067-ca494e00-3794-11e9-8200-d03573de5a71.png)

Reverting Cocoapods to 1.5.2 allows the project to successfully compile

**Comment by chshapiro** [comment]
Hey @pangers,

Are you including `use_frameworks!` in your Podfile?

Thanks,
Chava

**Comment by pangers** [comment]
@chshapiro yes we are

**Comment by chshapiro** [comment]
Hey @pangers,

Thank you! Can you try removing this `Copy Files` build phase and see if you're able to build your project and receive Push Stories after that?

![image](https://user-images.githubusercontent.com/20050276/53501337-f9540e00-3a79-11e9-8287-b88b93ed445a.png)

Thanks,
Chava

**Comment by pangers** [comment]
@chshapiro Yes that seems to solve the issue. I removed the `Copy Files` build phase and tested sending a Push Story and it worked

**Comment by chshapiro** [comment]
Thank you for testing! We're going to update our documentation to reflect this integration step for those using `use_frameworks!` and using Cocoapods 1.6.1.

**Comment by mineschan** [comment]
As per today the documentation is not yet updated.
Lucky that I've came across this issue.

**Comment by Bucimis** [comment]
@mineschan thanks for the heads up & apologies for the extra hunting. we'll fix our docs shortly
