### ISSUE TITLE
Missing nullability leads to error in Xcode 10.2 Beta 4 when "treat warnings as errors" build setting is enabled

### ISSUE THREAD

**Issue by PatrickDotStar** [Appboy/appboy-ios-sdk#178]
# Report

When building your SDK with Xcode 10.2 Beta 4 with enabled "treat warnings as errors" build setting (`GCC_TREAT_WARNINGS_AS_ERRORS`) build setting, Xcode 10.2 will now throw an error saying that some properties in the header files are missing nullability attributes when the `Appboy_iOS_SDK` is imported in the swift bridging header. Using the current version of Xcode (10.1) works fine for now but it looks like that Xcode 10.2 will treat these warnings as errors.

The only solution I found at the moment is to turn off the "treat warnings as errors" build setting but this is no proper solution.

Please add the missing nullability attributes to the folliwing header files

**ABKContentCard.h**

	@property (readonly) NSString *idString
	(BOOL)hasSameId:(ABKContentCard *)card

**ABKClassicContentCard.h**

	@property (copy) NSString *title
	@property (copy) NSString *cardDescription
	
**ABKCaptionedImageContentCard.h**

	@property (copy) NSString *image
	@property (copy) NSString *title
	@property (copy) NSString *cardDescription

![appboymissingnullability](https://user-images.githubusercontent.com/10392878/53885606-735a3900-401e-11e9-9340-2bbda5690421.png)

## Environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.2 Beta 4
 SDK Version             | 3.12.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.2 Beta 4
 Repro rate              | all the time (100%)

**Comment by hokstuff** [comment]
Hi @PatrickDotStar,

These errors that you described will be fixed with the next release. Thanks for pointing them out!

**Comment by PatrickDotStar** [comment]
Any plans yet when you will make the next release? @hokstuff

**Comment by chshapiro** [comment]
Hey @PatrickDotStar,

This was included included in our last release 3.14.0.

**Comment by PatrickDotStar** [comment]
> Hey @PatrickDotStar,
> 
> This was included included in our last release 3.14.0.

Are you sure? :) I still don't see the missing nullability attributes for all the properties I pointed out in 3.14.0. Or did you fix it by another way?
![nullability](https://user-images.githubusercontent.com/10392878/55177664-0997ff80-5184-11e9-9402-138a18ebfa64.png)

**Comment by Bucimis** [comment]
@PatrickDotStar we used macros to mark fields in ambiguous regions as nullable or non-nullable as appropriate. See https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/designating_nullability_in_objective-c_apis for more information.

Are you still seeing errors in XCode?

**Comment by PatrickDotStar** [comment]
Ah yeah sorry my bad I have completely overseen this🤦🏻‍♂️
I just tried it out and it works now :)
Thanks for your time

**Comment by Bucimis** [comment]
@PatrickDotStar glad to hear that! thanks for letting us know about the issue & let us know if there's anything else we can do
