### ISSUE TITLE
Property Description In Cards Doesn't auto-synthesis in Xcode 6 beta 4

### ISSUE THREAD

**Issue by Wenzhi** [Appboy/appboy-ios-sdk#18]
From Xcode 6 beta 4, clang fails when trying to auto-synthesize the property "description" in following cards:
ABKTextAnnouncementCard
ABKClassicCard
ABKCaptionedImageCard

We are aware of the issue and monitoring it closely. If it looks like this will continue to be an issue in the final release of XCode 6 (which is likely), we'll be making a breaking change to the card interfaces in order to accommodate these new rules.

**Comment by briancaw** [comment]
Fixed in 2.9.3.
