### ISSUE TITLE
In-app messages is not compatible with SDWebImage 4.2.1

### ISSUE THREAD

**Issue by jafework** [Appboy/appboy-ios-sdk#181]
* [x ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 12.1
 SDK Version             | e.g. 3.10.0
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 10.1
 Repro rate              | e.g. all the time (100%)
 
## What did you do?

1. Added `pod "Appboy-iOS-SDK/InAppMessage"` to our project
2. Cocoapod pulls in SDWebImage 4.2.1 (latest) by default. 
3. When trying to build the application get the attached build error.

## What did you expect to happen?
Project should build with latest SDWebImage 4.2.1 

## What happened instead?
Project fails to build, looks like ABKSDWebImageProxy is not source compatible with latest SDWebImage 4.2.1+. 

## Steps to reproduce
1. Added `pod "Appboy-iOS-SDK/InAppMessage"` to our project
2. Cocoapod pulls in SDWebImage 4.2.1 (latest) by default. 
3. When trying to build the application get the attached build error.

<img width="744" alt="Screen Shot 2019-03-13 at 5 43 26 PM" src="https://user-images.githubusercontent.com/6447211/54323647-796c8e80-45b7-11e9-95ae-ad47c5ec9ba4.png">
<img width="588" alt="Screen Shot 2019-03-13 at 5 20 26 PM" src="https://user-images.githubusercontent.com/6447211/54323649-7a052500-45b7-11e9-9beb-0ebe6fc01f35.png">

**Comment by chshapiro** [comment]
Hey @jafework,

The latest SDWebImage version is 4.4.6. Can you pull that in and see if that fixes your issue? We are unable to repro these errors.

Thanks,
Chava
