### ISSUE TITLE
SDK size

### ISSUE THREAD

**Issue by sjrmanning** [Appboy/appboy-ios-sdk#183]
Hi, we've been looking at using Braze for push notifications, marketing, some analytics, etc. but after taking a look at the iOS integration we've run into a pretty major issue.

Including this SDK brings our app size from ~9 mb to over 140 mb, I'm guessing because of this giant 96mb static library `libAppboyKitLibrary.a`. What on earth is in this?! Is there a way to register a device token with Braze outside of using this SDK? Because if not we're probably not feasibly going to be able to use Braze and will need to look for another provider. ☹️

**Comment by Bucimis** [comment]
Hi @sjrmanning, our static library is large for similar reasons as addressed in this post: https://github.com/realm/realm-cocoa/issues/4450#issuecomment-267818165 - similar to Realm, we ship multiple architectures (specifically five - `armv7 i386 x86_64 arm64 arm64e`) with bitcode enabled. However, once bitcode gets compiled to the target machine architecture and the rest of your app gets thinned when distributing to users, the real impact on app size should be much smaller, in the 1-2mb range.

Could you let us know what the final effect of adding the sdk is on "thinned .ipa" size (see https://developer.apple.com/library/archive/qa/qa1795/_index.html)? That should give a better picture of the real-world effect of adding the sdk

**Comment by sjrmanning** [comment]
Hey @Bucimis, thanks for your response. After some more testing with this it seems that the eventual App Store ipa size isn't as bad as we originally saw. We'll just need to be careful about keeping the .a outside of our repo, but the app download size has only increased about 2mb as you mentioned.

Thanks again! Closing this :)
