### ISSUE TITLE
UIWebView is deprecated

### ISSUE THREAD

**Issue by borut-t** [Appboy/appboy-ios-sdk#185]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.2
 SDK Version             | 3.14.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.2
 Repro rate              | all the time (100%)
 
## What did you do?

Updated Xcode to the latest version.

## What did you expect to happen?

No warning.

## What happened instead?

`/Pods/Appboy-iOS-SDK/AppboyUI/ABKInAppMessage/ViewControllers/ABKInAppMessageHTMLViewController.h:10:38: 'UIWebView' is deprecated: first deprecated in iOS 12.0 - No longer supported; please adopt WKWebView.`

`UIWebView` has been legacy for a few years now. You should switch to `WKWebView` instead.

## Steps to reproduce

Update Xcode and build the project.

## Code Snippet

n/a

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

no

## Project that demonstrates the issue

n/a

**Comment by Bucimis** [comment]
Hi @borut-t, thanks for the call out. Using WKWebView is on our product roadmap but we don't currently have a timeline. We'll update as more information becomes available.

Thanks again!

**Comment by miquelalvarado** [comment]
Hi, we've started receiving iTunes warnings from Apple notifying that they'll soon start rejecting apps that use `UIWebView`, so it would be appreciated if you reopen this issue and prioritize again the task 🙏
