### ISSUE TITLE
Braze SDK 1.14.0 related warnings showing up on Xcode 10.2 / Swift 5

### ISSUE THREAD

**Issue by Nonnus** [Appboy/appboy-ios-sdk#187]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report
Braze SDK 1.14.0 related warnings are showing up on Xcode 10.2 / Swift 5

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | not applicable
 SDK Version             | 3.14.0
 Integration Method      | carthage
 Xcode Version           | Xcode 10.2
 Repro rate              | all the time (100%)
 
## What did you do?

Build the app

## What did you expect to happen?

No Braze SDK warnings to be shown

## What happened instead?

Braze SDK related warnings are showing up:
<img width="379" alt="Screenshot 2019-04-04 at 13 44 13" src="https://user-images.githubusercontent.com/54864/55556005-d2c36b80-56e6-11e9-85a8-44429541d800.png">
<img width="382" alt="Screenshot 2019-04-04 at 13 43 58" src="https://user-images.githubusercontent.com/54864/55556006-d2c36b80-56e6-11e9-8bb8-41e04edc9a9a.png">

## Steps to reproduce

- Add `github "Appboy/appboy-ios-sdk"` to the cartfile file.
- Open app root folder on Terminal.app and run `carthage update appboy-ios-sdk --platform ios` command
- Run the app.

**Comment by hokstuff** [comment]
Hi @Nonnus,

Thanks for reaching out. These errors should have been fixed in SDK version 3.14.0, as per adding nullability macros [here](https://github.com/Appboy/appboy-ios-sdk/issues/178). Could you send what is in your Cartfile.resolved to confirm you're on the latest version?

**Comment by Nonnus** [comment]
@hokstuff you are absolutely correct, even though I had rebuilt braze sdk it looks like Xcode was still using some cached version that was showing the same warnings. After restarting it now the warnings are gone, thanks a lot!
