### ISSUE TITLE
Braze 3.14.0 NewsFeed crash on Xcode 10.2 / iOS 12.2

### ISSUE THREAD

**Issue by kunal30xi** [Appboy/appboy-ios-sdk#188]
* [X ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

When accessing the NewsFeed receiving a crash with the following output in the console: `objc[34051]: Attempt to use unknown class 0x600003b088c0.`

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.2
 SDK Version             | 3.14.0
 Integration Method      | Carthage
 Xcode Version           | Xcode 10.2
 Repro rate              | 100%
 
## What did you do?

Updated from Braze 3.11.0 to 3.14.0
We currently subclass ABKNewsFeedTableViewController mostly because we need the ability to customize behavior in the `handleCardClick` method as well as customize the state of the navigation bar in viewWillAppear / viewWillDisappear.

As recommended in the [example | https://github.com/Appboy/appboy-ios-sdk/blob/master/Samples/NewsFeed/BrazeNewsFeedSample/BrazeNewsFeedSample/CustomFeedTableViewController.m#L6], we instantiate the subclass and call `object_setClass` on the instance to set the type.

This works without issue Braze 3.11.0, however in 3.14.0, it causes a crash with the following message logged to the console:

`objc[34051]: Attempt to use unknown class 0x600003b088c0.`

I tried downgrading to `3.12.0` which is one minor version higher than the version we are currently on and experienced the same issue.

## What did you expect to happen?

News feed is displayed as expected without crashes.

## What happened instead?

Crash is received with the following message logged to the console:

`objc[34051]: Attempt to use unknown class 0x600003b088c0.`

**Comment by Stakenborg** [comment]
Definitely related to [this](https://github.com/Appboy/appboy-ios-sdk/issues/160).

**Comment by kunal30xi** [comment]
Issue appears to be resolved after updating to Xcode 10.2.1
