### ISSUE TITLE
Failed to find or create execution context for description IBCocoaTouchPlatformToolDescription

### ISSUE THREAD

**Issue by mikhaelmina** [Appboy/appboy-ios-sdk#193]
I get the following build error **after updating to Xcode 10.3**
![Screenshot 2019-07-23 13 39 36](https://user-images.githubusercontent.com/33283577/61709434-8c565300-ad4f-11e9-81e4-da53b9a90b41.png)

**Appboy-iOS-
SDK/AppboyUI/ABKInAppMessage/Resources/ABKInAppMessageHTMLFullViewController.xib: - 1 : Failed to find or create execution context for description '<IBCocoaTouchPlatformToolDescription: 0x7fb388fd3750> System content for IBCocoaTouchFramework-EightAndLater <IBScaleFactorDeviceTypeDescription: 0x7fb388fe3120> scaleFactor=2x'. These intermediate objects were non-nil**

Appreciate your help!
Thanks
Mina

**Comment by hokstuff** [comment]
Hi @mikhaelmina,

Thanks for filing a ticket - This can be resolved by restarting your computer or by just restarting `CoreSimulatorService`. Here's a link to the [Stackoverflow post describing the issue](https://stackoverflow.com/questions/36533720/failed-to-find-or-create-execution-context-for-description-ibcocoatouchplatform).

Let me know if this fixes the error!

**Comment by mikhaelmina** [comment]
Thanks, @hokstuff yes that fixed it
