### ISSUE TITLE
Fail to Compile 3.17.0 with Carthage Installation

### ISSUE THREAD

**Issue by joeydong** [Appboy/appboy-ios-sdk#197]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.4
 SDK Version             | 3.16.0
 Integration Method      | carthage
 Xcode Version           | Xcode 10.3
 Repro rate              | all the time (100%)
 
## What did you do?

Attempted to update Braze through Carthage from `3.16.0` to `3.17.0`

## What did you expect to happen?

Successful compilation

## What happened instead?

Swift compilation error when using `3.17.0`. Using our existing `3.16.0` compiles successfully!

<img width="252" alt="Screen Shot 2019-08-21 at 3 04 20 PM" src="https://user-images.githubusercontent.com/434294/63471909-62af4b00-c425-11e9-86f3-ef2cfeea12f6.png">

## Steps to reproduce

- Install `Braze 3.17.0` with Carthage: `binary "https://raw.githubusercontent.com/Appboy/appboy-ios-sdk/master/appboy_ios_sdk_core.json"`
- Cmd+B

**Comment by Bucimis** [comment]
@joeydong are you referencing `ABKAppboyEndpointDelegate` anywhere in your code? That class was removed in `3.17.0`.

**Comment by joeydong** [comment]
we are not. i believe this is an Xcode safeguard which throws an error if a framework has a header file but it's not included in the umbrella header? did your CI successfully completely remove any `ABKAppboyEndpointDelegate.h` files before generating the the `3.17.0` release?

**Comment by joeydong** [comment]
https://stackoverflow.com/questions/32923483/umbrella-header-for-module-myframework-does-not-include-header-otherframework

https://github.com/mixpanel/mixpanel-iphone/issues/619

**Comment by chshapiro** [comment]
Hey @joeydong,

Thanks for raising this issue! We have updated the frameworks fro 3.17.0. Can you try again and let us know if you're still running into any issues?

**Comment by joeydong** [comment]
Thanks it works now! What was the issue? I was thinking as I was leaving the office yesterday that the pre-built binary probably had a stray `ABKAppboyEndpointDelegate.h` header file that needed to be removed but maybe you found some other problem?

**Comment by chshapiro** [comment]
That was it! Thank you for reporting!
