### ISSUE TITLE
Xcode 10.1 invalid bitcode version

### ISSUE THREAD

**Issue by PirateIsHere** [Appboy/appboy-ios-sdk#199]
Report
We are trying to update Appboy iOS SDK to v3.20.1 It works well in debug, but when we try to archive our app in release mode with Xcode 10.1, we got this error:could not reparse object file in bitcode bundle: ’Invalid bitcode version (Producer: ‘1001.0.46.4.0_0’ Reader: ‘1000.11.45.5_0’)’, using libLTO version ‘LLVM version 10.0.0, (clang-1000.11.45.5)’ for architecture arm64
Migration to Xcode 10.2 or 10.3 right now is not an option for us. Would it be possible to build the next release with Xcode 10.1 to ensure compatibility for us?

Environment.

 Info                                   | Value                               |
-------------------------|------------------------|
 Platform Name                | iOS
 Platform Version             | N/A
 SDK Version                    | 3.20.1
 Integration Method        | cocoapods
 Xcode Version                | xCode 10.1
 Repro rate                       | all the time (100%)
 
## What did you do?

import Braze through Cocoapods.

## Code Snippet

target '...' do
    use_frameworks!

pod 'Appboy-iOS-SDK', '~>3.20.1'

end

**Comment by polqf** [comment]
We're having the same issue here. Furthermore, we are relying on Braze for Push Notifications.
Since the release of iOS 13 is around the corner, and support for it starts on version 3.20.0, and it also has the problem, we are in a tough situation. Can you please provide a solution?

If we don't update to an iOS 13 version of the SDK, we're losing Push Notifications, which is a CORE part of our business.

**Comment by chshapiro** [comment]
Hey @polqf,

Are you also using Xcode 10.1?

**Comment by polqf** [comment]
Yes, I am

**Comment by chshapiro** [comment]
Hey @PirateIsHere and @polqf,

We're unable to repro this on 10.3, and we've seen signal that this effects only 10.1 and below. Given the pending iOS 13 release, our recommendation is to upgrade your Xcode version to solve this. If you are unable to do so, you can fix the push issue without updating your SDK by replacing the code in `didRegisterForRemoteNotificationsWithDeviceToken` with the code in this [Github gist](https://gist.github.com/Bucimis/21b0258d65827a83cf20d4d8f030a9f6).

Please let us know if you have further questions! Thanks!

**Comment by PirateIsHere** [comment]
The latest version that we can use it in Xcode 10.1 is 3.16.0. If we try to apply the patch from the provided link above, notifications are still not working on iOS 13.

We are aware of technical debt we have here and we are working on it, but this change has come in last moment before the release of iOS 13 and we are unable to finish our refactoring to new Xcode and new Swift.

That’s why we need your help and support.

**Comment by lijithvipin** [comment]
We are also facing the same issue. Any update on this?
Environment:
Xcode: 10.1
Swift version: 3.0

**Comment by chshapiro** [comment]
Hey @lijithvipin,

If you can't update your Xcode version, please use the workaround linked above. 

Thanks!

**Comment by chshapiro** [comment]
Hey all,

Please keep using the workaround until you can update your Xcode version. If you have any further questions, feel free to reopen the issue.

Thanks!
