### ISSUE TITLE
Feature request: support `nullable` view controller returned from `ABKInAppMessageUIDelegate` method `-inAppMessageViewControllerWithInAppMessage:`

### ISSUE THREAD

**Issue by postmechanical** [Appboy/appboy-ios-sdk#200]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 12.4.1
 SDK Version             | 3.20.1
 Integration Method      | carthage
 Xcode Version           | Xcode 10.2.1
 Repro rate              | N/A
 
Currently customization of in-app messages is all or nothing. As an implementer of `ABKInAppMessageUIDelegate`, I want to be able to return a `nil` instance from `-inAppMessageViewControllerWithInAppMessage:` depending on the given `ABKInAppMessage` instance. In the event a `nil` view controller is returned, then `ABKInAppMessageUIController` should follow its [existing code path](https://github.com/Appboy/appboy-ios-sdk/blob/ed4ef31e51fb81bd2ee882c8ae2b8138d0431754/AppboyUI/ABKInAppMessage/ABKInAppMessageUIController.m#L75-L87) and thereby alleviate implementers of `ABKInAppMessageUIDelegate` of the need to duplicate existing SDK code.

**Comment by chshapiro** [comment]
Hey @postmechanical,

Thanks for your suggestion! We've raised this request to our product team and will continue to track internally.
