### ISSUE TITLE
Integration doesn't work with Carthage

### ISSUE THREAD

**Issue by ketzusaka** [Appboy/appboy-ios-sdk#202]
* [X] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

Attempting to upgrade Braze SDK from 3.6.0 to 3.20.2. I'm getting an error:

```
Carthage/Build/iOS/Appboy_iOS_SDK.framework/Headers/ABKBannerContentCardCell.h:3:9: error: 'SDWebImage/SDAnimatedImageView+WebCache.h' file not found
#import <SDWebImage/SDAnimatedImageView+WebCache.h>
        ^
[FILE REDACTED] error: could not build Objective-C module 'Appboy_iOS_SDK'
import Appboy_iOS_SDK
```

Nothing has changed code-wise except updating the function call to resolve the breakage on iOS 13 for push:

```
- Appboy.sharedInstance()?.registerPushToken(String(format: "%@", deviceToken as CVarArg))
+ Appboy.sharedInstance()?.registerDeviceToken(deviceToken)
```

SDWebImage is also a Carthage dependency. It is at version 4.3.3.

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.4
 SDK Version             | 3.20.2
 Integration Method      | carthage
 Xcode Version           | Xcode 10.2.1
 Repro rate              | all the time (100%)
 
## What did you do?

Upgraded the SDK

## What did you expect to happen?

It to compile.

## What happened instead?

It doesn't compile.

## Steps to reproduce

1. Upgrade Carthage dependencies 
2. Try to build.

## Code Snippet

Only code change is written above.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No

## Project that demonstrates the issue

If this must be done I'll try to do it, but this sounds like a common thing for people to do and I'm hoping there will be a basic tip on what to do with header search files or something to have it locate SDWebImage properly that isn't described on your integration guides.

**Comment by ketzusaka** [comment]
I've verified this happens with a fresh project setup with Carthage. Changes from initial commit:

```
diff --git a/Cartfile b/Cartfile
index 2447206..bbba212 100644
--- a/Cartfile
+++ b/Cartfile
@@ -1,2 +1,2 @@
-github "Appboy/Appboy-iOS-SDK" "3.6.0"
+github "Appboy/Appboy-iOS-SDK" ~> 3.20.2
 github "rs/SDWebImage" "4.3.3"
diff --git a/Cartfile.resolved b/Cartfile.resolved
index 2447206..1537d78 100644
--- a/Cartfile.resolved
+++ b/Cartfile.resolved
@@ -1,2 +1,2 @@
-github "Appboy/Appboy-iOS-SDK" "3.6.0"
+github "Appboy/Appboy-iOS-SDK" "3.20.2"
 github "rs/SDWebImage" "4.3.3"
```

**Comment by Bucimis** [comment]
@ketzusaka do you have other dependencies that are causing the dependency resolver to use SDWebImage 4.3.3? v3.20.2 of the Braze iOS SDK requires SDWebImage 5+

**Comment by ketzusaka** [comment]
Nah, we can update. That fixed it. Thank you very much!

If possible, in the future it would be ideal not to break clients in minor versions. This appears to be the second breaking change in the 3.x line..
