### ISSUE TITLE
No swift module defined for tvOS sdk

### ISSUE THREAD

**Issue by mdyson** [Appboy/appboy-ios-sdk#203]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  tvos
 Platform Version        |  13.1
 SDK Version             | 3.17
 Integration Method      | cocoapods
 Xcode Version           |  Xcode 11.1
 Repro rate              | all the time (100%)
 
## What did you do?

The tvOS build of the Appboy framework is missing the module file to properly import the framework into swift. 

This is an example from the PushStory of what is missing: https://github.com/Appboy/appboy-ios-sdk/blob/master/Appboy-Push-Story/AppboyPushStory.framework/Modules/module.modulemap

## What did you expect to happen?

I expect this file to exist to properly use the modulemap in swift

## What happened instead?

It doesn't exist and I need to import Appboy into my tvOS app using a obj-c bridging header which adds all the imports to all the swift files and slows down compile time.

## Steps to reproduce

- Add `pod 'Appboy-tvOS-SDK'` to the Podspec file for tvOS
- in a swift file add `import AppboyTVOSKit`
- see compiler error

## Code Snippet

Just add this to fix the issue:
```
framework module AppboyTVOSKit {
  umbrella header "AppboyKit.h"

  export *
  module * { export * }
}
```

**Comment by chshapiro** [comment]
Hey @mdyson,

Thank you for bringing this to our attention. We will add this to our product roadmap and continue to track internally. 

Thanks!

**Comment by mdyson** [comment]
Thanks @chshapiro! If it helps out at all I have the fix in my own fork of your repo and I'm happy to open up a pull request: https://github.com/Appboy/appboy-ios-sdk/compare/master...mdyson:mdyson/fix-missing-module?expand=1
