### ISSUE TITLE
Absurdly slow Carthage clone/fetch

### ISSUE THREAD

**Issue by edulpn** [Appboy/appboy-ios-sdk#204]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

Carthage hangs on `Cloning/Fetching appboy-ios-sdk` (download rates super low, bouncing everywhere), doesn't happen to any of my other dozen-ish dependencies. Also, due to not exposing a shared scheme, I cannot run with `--no-use-binaries`, so I need to create alternate flows on my CI pipelines (but this is, for now, minor).

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 SDK Version             | 3.20.3
 Integration Method      | Carthage
 Xcode Version           | Xcode 10.3
 Repro rate              | all the time, latelly
 
## What did you do?

Cartfile
```github "Appboy/appboy-ios-sdk" ~> 3.20```

Carthage command
`carthage bootstrap appboy-ios-sdk --platform iOS --cache-builds` 

## What did you expect to happen?

Clone, resolve version and build/download prebuilt binary.

## What happened instead?

Hangs on cloning/fetching the repo

**Comment by edulpn** [comment]
I forked this repo and, to my awe, it sums up to . 1.18GB. It actually makes sense this thing is taking ages to clone.

**Comment by hokstuff** [comment]
Hi @edulpn,

Depending on your internet connection, it may take a little while to clone/fetch the repo. Please let us know if you have any additional questions or concerns.

Thank you,
Daniel
