### ISSUE TITLE
"[Appboy sharedInstance] called before Braze was initialized" after tapping on in-app message notification

### ISSUE THREAD

**Issue by SpriggyDesmond** [Appboy/appboy-ios-sdk#206]
Platform Name           iOS
 Platform Version        13.1.3
 SDK Version               3.20.
 Integration Method      cocoapods
 Xcode Version           Xcode 11.1
 Repro rate              all the time (100%)
 
In `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?)` I ran `Appboy.start(withApiKey: apiKey, in: self.appboyApplication, withLaunchOptions: launchOptions, withAppboyOptions: [:])`. And I checked right after that, `Appboy.sharedInstance()` is not nil.

Now I can receive push notifications. But we I try to tap a in-app message push notification, I will see warning below:
```
2019-10-30 13:32:54.929732+0800 MyApp Test[15964:2784642] 6.10.0 - [Firebase/Messaging][I-FCM019001] Analytics logging is disabled. Do not log event.
2019-10-30 13:32:54.929811+0800 MyApp Test[15964:2784642] 6.10.0 - [Firebase/Messaging][I-FCM006000] Received message missing local start time, dropped.
2019-10-30 13:32:58.222535+0800 MyApp Test[15964:2784803] 6.10.0 - [Firebase/Messaging][I-FCM019001] Analytics logging is disabled. Do not log event.
2019-10-30 13:32:58.222698+0800 MyApp Test[15964:2784803] 6.10.0 - [Firebase/Messaging][I-FCM006000] Received message missing local start time, dropped.
2019-10-30 13:32:58.817122+0800 MyApp Test[15964:2784399] 6.10.0 - [Firebase/Performance][I-PRF100009] Recording network trace: https://sdk.iad-03.braze.com/api/v3/data
2019-10-30 13:32:58.829198+0800 MyApp Test[15964:2784144] [APPBOY] 
     ********************************************
     **             !! WARNING !!              **
     **     [Appboy sharedInstance] called     **
     **      before Braze was initialized,     **
     **       returning nil. Please make       **
     ** sure you call [Appboy startWithApiKey] **
     **  before accessing the sharedInstance.  **
     ********************************************
2019-10-30 13:33:01.074682+0800 MyApp Test[15964:2784642] [] tcp_input [C48.1:2] flags=[R.] seq=15339, ack=2946889513, win=65535 state=LAST_ACK rcv_nxt=15339, snd_una=2946889482
```

I got same warnings when I try to load content card via `ABKContentCardsTableViewController`.

**Comment by Bucimis** [comment]
@SpriggyDesmond is your call to `startWithApiKey` in `didFinishLaunchingWithOptions` gated or asynchronous in any way? You should add breakpoints or logging to verify that `startWithApiKey` is indeed getting run before the push handling/content card code is run.

**Comment by hokstuff** [comment]
@SpriggyDesmond I'm going to close this issue out due to inactivity. Please reopen it if you are still are experiencing issues with this.

Thanks!
Daniel

**Comment by Saulenco** [comment]
Hi, i have the same issue with AppBoy 4.4.4.
after `Appboy.start(withApiKey: apiKey, in: application, withLaunchOptions: options, withAppboyOptions: appboyOptions)` if i print `po Appboy.sharedInstance()` i have a valid instance of  Appboy.

and when i send a in app message from braze app and i receive it and in `userNotificationCenter(center: didReceive:withCompletionHandler)` i call 
`Appboy.sharedInstance()?.userNotificationCenter(center,  didReceive: response, withCompletionHandler: completionHandler)
` it fails saying 
```
     ********************************************
     **             !! WARNING !!              **
     **     [Appboy sharedInstance] called     **
     **      before Braze was initialized,     **
     **       returning nil. Please make       **
     ** sure you call [Appboy startWithApiKey] **
     **  before accessing the sharedInstance.  **
     ********************************************
```

even if i had a valid instance `Appboy.sharedInstance()`

**Comment by Bucimis** [comment]
@Saulenco are you using either of `disableSDK()` or `wipeDataAndDisableForAppRun()` in your app?

**Comment by franz-ruggiero-ck** [comment]
@Bucimis I have the same issue. I am using `disableSDK()` function in the app.

**Comment by Saulenco** [comment]
@Bucimis Hi , i don't use none of this functions, only function that i use is `Appboy.sharedInstance()?.requestImmediateDataFlush()`

**Comment by Bucimis** [comment]
@franz-ruggiero-ck @Saulenco are you calling `Appboy.start` in your `didFinishLaunching`? You must initialize Braze (using `Appboy.start`) before Braze's `userNotificationCenter` delegates are called, since they rely on the shared instance.

**Comment by Saulenco** [comment]
@Bucimis as mentioned before, I call `Appboy.start` in didFinishLaunching and after that if i print `Appboy.sharedInstance()` there is a valid instance. All good, and when i send a push or in app message campaign from Braze dashboard i receive that error.

**Comment by Bucimis** [comment]
@Saulenco could you reach out to support@braze.com with the same issue, we'll likely need to take a peek at your code.
