### ISSUE TITLE
Device Token Registration is not working as expected

### ISSUE THREAD

**Issue by kuyazee** [Appboy/appboy-ios-sdk#207]
[ * ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 SDK Version             | 3.20.4
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.1
 Repro rate              | all the time (100%) 

### App Group 1 
 
 Device                 | Platform       | Repro rate
-----------------|-------------|------------|
 iPhone 6s plus   | ios 12.2         | 100% 
 iPhone 6s plus   | ios 13.1 beta | 100%
 iPhone 7              | ios 13.1.3      | 0%
 iPhone 7              | ios 12.1.4      |  100%
 iPhone 7 plus     | ios 12.3.1       | 100%
 iPhone 7 plus     | ios 13.1.3       | 100%

### App Group 2
 
 Device                 | Platform       | Repro rate
-----------------|-------------|------------|
 iPhone 6s plus   | ios 12.2         | 100% 
 iPhone 6s plus   | ios 13.1 beta | 100%
 iPhone 7              | ios 13.1.3      | 100%
 iPhone 7              | ios 12.1.4      |  100%
 iPhone 7 plus     | ios 12.3.1       | 100%
 iPhone 7 plus     | ios 13.1.3       | 0%

## What did you do?

Integrate Braze through Cocoapods and register the device token data.

Even tried the ff:
- Restart the phone
- Force Restart the phone
- Force exit the app
- Keep app on foreground
- Keep app on background

Example Log:

```bash
2019-11-06 15:36:35.672786+0800 APPNAMEHERE[3061:702556] <Appboy: 0x281b90900>:registerDeviceToken: Method called with token: {length = 32, bytes = 0x9e8e9b7c b94f1524 f799f1ac da502539 ... 45e94650 e8601666 }
```

## What did you expect to happen?

- To have the device's token be registered for push notifications
- To have the same issue reproduced for both app groups but it doesn't seem to be the case.

## What happened instead?

Most devices' tokens are not being registered

## Steps to reproduce

Just followed the installation steps via the Documentation. We've been using braze for a while now and it worked well pre sdk version 3.19.0

## Code Snippet

N/A

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

N/A

## Project that demonstrates the issue

https://apps.apple.com/us/app/swiperx/id1146367948

**Comment by Bucimis** [comment]
@kuyazee thanks for reporting. Are you seeing tokens not get sent up/registered at all, or tokens get sent up that subsequently bounce when you try to send push to them?

**Comment by kuyazee** [comment]
> @kuyazee thanks for reporting. Are you seeing tokens not get sent up/registered at all, or tokens get sent up that subsequently bounce when you try to send push to them?

Well, according to the SDK's logs the tokens are getting sent up to the server. I'm not sure what happens server side, is there a way I can log if they bounce?

PS: Our other push notification services work, example
- Manual push using APNS
- Firebase Push
- etc.

**Comment by chshapiro** [comment]
Hey @kuyazee,

In what format do you see them getting sent up the server? Can you send us your device logs that show this? You can email them to support@braze.com if you don't want to post them publicly.

Thank you!

**Comment by kuyazee** [comment]
Hello @chshapiro it's in this format

```
2019-11-06 15:36:35.672786+0800 APPNAMEHERE[3061:702556] <Appboy: 0x281b90900>:registerDeviceToken: Method called with token: {length = 32, bytes = 0x9e8e9b7c b94f1524 f799f1ac da502539 ... 45e94650 e8601666 }
```

**Comment by chshapiro** [comment]
Hey @kuyazee,

Can you [enable verbose logging](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/optional_idfa_collection/#verbose-logging) and send us the logs from when you run your app? This will allow us to see how the token is being sent to the server? Can you do this for a version where push is working and for a version where push is not working? You can paste the logs here or email them to support@braze.com.

Thank you!

**Comment by kuyazee** [comment]
Hello again @chshapiro I don't have access to the devices right now but I'll get back to you with this by next week. Have a good evening Cheers 🍻

**Comment by chshapiro** [comment]
Hey @kuyazee,

I took a look at the logs that you sent over to our Support team. Everything in the logs looks good - the push token is being sent to our servers in the proper format. Are you unable to receive push on the device? Was push working on the device before you updated to version 3.20.4 of the SDK? When you look at the user profile on the dashboard, is the user opted in for push?

Thank you!

**Comment by kuyazee** [comment]
@chshapiro 

> Are you unable to receive push on the device? 

Yes

> Was push working on the device before you updated to version 3.20.4 of the SDK?

Yes

> When you look at the user profile on the dashboard, is the user opted in for push?

No

When trying to send test push notifications this also appears

<img width="565" alt="Screen Shot 2019-11-13 at 3 32 02 PM" src="https://user-images.githubusercontent.com/17846698/68742294-cadb8a80-062a-11ea-9a64-47b9e73ab03a.png">

**Comment by kuyazee** [comment]
Hello @chshapiro any update on this?

**Comment by chshapiro** [comment]
Hey @kuyazee ,

When you create a new user on one of the devices where push is not working, can you check the user profile before trying to send a push and check what it says about whether or not the user is registered for push. Does that value change after you try to send a push? We're guessing this may be a signing or push certificate issue because your logs show that the push token is being sent in the correct version.

Thanks!

**Comment by hokstuff** [comment]
Since this thread has been inactive for some time, I'm going to close it out. Feel free to reopen if you are still experiencing issues. Thanks!
