### ISSUE TITLE
Undocumented behaviour change introduced in 3.16.0, `changeUser(_)` triggering an automatic data flush.

### ISSUE THREAD

**Issue by paulo-depop** [Appboy/appboy-ios-sdk#208]
* [X] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11, 12, 13
 SDK Version             | 3.16.0 or newer
 Integration Method      | carthage
 Xcode Version           | Xcode 11.1
 Repro rate              | all the time (100%)
 
## What did you do?
```
appboy.requestProcessingPolicy = .manualRequestProcessing
appboy.changeUser(my_user_id)
appboy.user.setCustomAttributeWithKey("my_custom_key", andBOOLValue: true)
appboy.flushDataAndProcessRequestQueue()
appboy.requestProcessingPolicy = .automaticRequestProcessing
```

## What did you expect to happen?

Because I set requestProcessingPolicy to .manualRequestProcessing, I expect that my code will batch `changeUser` and `setCustomAttributeWithKey` in one request on the next manual data flush.

## What happened instead?

After updating to 3.16.0 or newer, an automatic data flush occurs when calling `changeUser` .
**This doesn't happens in 3.15.0**

## Steps to reproduce

1. Integrate SDK
2. Copy code from `What did you do?` section
3. Observe that an automatic data flush occurs just after `changeUser` is called.

## Code Snippet

Check `What did you do?`

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No

**Comment by hokstuff** [comment]
Hi @paulo-depop,

Thank you for pointing this out in our documentation. We have now planned a documentation update to communicate this functionality change to our integrators.

Best,
Daniel
