### ISSUE TITLE
Can you change handleCardClick to delegate protocol in swift ?

### ISSUE THREAD

**Issue by thepinyo** [Appboy/appboy-ios-sdk#209]
Can you change handleCardClick to delegate protocol in swift? and please update your document and example project more. I want to add subview to my view controller and custom handle card click event and custom cellForRow delegate. 

please help me because we have plan to release app in this week (15 Nov 2019).

**Comment by thepinyo** [comment]
i want to this ABKContentCardsTableViewController. and how to access cards list?

**Comment by hokstuff** [comment]
Hi @thepinyo,

Regarding your second question, in our latest release 3.21.0 we have added `cards` as a public property of ABKContentCardsTableViewController. You can view it [here](https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyUI/ABKContentCards/ViewControllers/ABKContentCardsTableViewController.h#L20).

For your initial question - thank you for the feedback. We are looking into adding more functionality with a card click delegate, but we currently do not have a timeline for it yet.

Thanks!

Best,
Daniel

**Comment by thepinyo** [comment]
@hokstuff do you have example project for my use case in swift? currently i try to handle click but it not work.

**Comment by hokstuff** [comment]
Hi @thepinyo,

Right now the only way to do custom handling with card clicks are to create a subclass for `ABKContentCardsTableViewController` and then override the `handleCardClick` method. We don't have an example in Swift, but we have an example of that in Objective-C [here](https://github.com/Appboy/appboy-ios-sdk/blob/4206104547ba541d1b95edf3ec9fced91c59527c/Samples/ContentCards/BrazeContentCardsSampleApp/BrazeContentCardsSampleApp/CustomContentCardsTableViewController.m#L34).

Let me know if you have any other questions.

Best,
Daniel

**Comment by hokstuff** [comment]
We are currently tracking this feature internally and have added it to our roadmap, so I will close out this ticket. Thanks!
