### ISSUE TITLE
Deprecated API usage

### ISSUE THREAD

**Issue by WojciechTrzasko** [Appboy/appboy-ios-sdk#210]
Hi,

Because of `UIApplication` API deprecations introduced with iOS 13, we investigated our project and its dependencies and find out that you use two deprecated properties:
* [statusBarOrientation](https://developer.apple.com/documentation/uikit/uiapplication/1623026-statusbarorientation)
* [statusBarFrame](https://developer.apple.com/documentation/uikit/uiapplication/1622937-statusbarframe)

In such a case I would like to ask, do you plan to resolve those in the near future?

Best regards!

**Comment by hokstuff** [comment]
Hi @WojciechTrzasko,

Thanks for pointing out the deprecated APIs. We are currently investigating replacing the references to these properties but do not have a timeline for when that will be done.

Best,
Daniel

**Comment by WojciechTrzasko** [comment]
Hi @hokstuff,
Thanks for the quick reply. 

In general, we are preparing our app for MVP release in the middle of December. This is a very crucial date for us. We are also aware that Apple already started to return errors or warnings about usage of deprecated UIWebView API and we are a little bit afraid that similar situations could happen with the above deprecations. This is why we are trying to reduce such risks.

Do you think that you will be able to resolve this before the middle of December?

PS. At the same time, I'm very sorry that we can't offer you our help with some PR to the repository, but unfortunately, we are just overwhelmed by the work in the project 😞 .

**Comment by hokstuff** [comment]
Hi @WojciechTrzasko,

I agree with your perspective that there is an inherent risk with using deprecated APIs, and we are actively working on this issue with high priority. However, we aren't able to give any specific deadlines for when this will be released. When we do fix this issue, we will be sure to let you know.

Thanks for your patience.

Best,
Daniel

**Comment by hokstuff** [comment]
Hi @WojciechTrzasko,

We have fixed this issue in our latest release. You can find it here: https://github.com/Appboy/Appboy-ios-sdk/releases

Thanks!
