### ISSUE TITLE
Incorrect Container Controller Lifecycle

### ISSUE THREAD

**Issue by k0nserv** [Appboy/appboy-ios-sdk#211]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | All
 SDK Version             | 3.20.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.2
 Repro rate              | all the time (100%)
 
## What did you do?

Implemented a custom view controller for IAM display

## What did you expect to happen?

For the view of my controller to have its layout specified by the parent view controller and for the parent view controller to correctly handle the container view controller lifecycle.

## What happened instead?

The view of my custom view controller was not laid out by its parent view controller and the parent view controller did not correctly perform container view controller lifecycle.

## Steps to reproduce

Create a project with custom view controller for IAM observe that `view.superview` is  not set until `viewDidAppear` and there is no layout specified for `view`.

**Comment by k0nserv** [comment]
As explained in [Apple's Documentation](https://developer.apple.com/library/archive/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html) on container view controllers the order of actions that parent view controllers should take when adding a child view controller are:

1. Call the addChildViewController: method of your container view controller. 
1. Add the child’s root view to your container’s view hierarchy. 
1. Add any constraints for managing the size and position of the child’s root view.
1. Call the didMoveToParentViewController: method of the child view controller. 

What Braze does is the following:

1. Call the addChildViewController: method of your container view controller. 
1. Call the didMoveToParentViewController: method of the child view controller. 
1. Add the child’s root view to your container’s view hierarchy. 
1. ~Add any constraints for managing the size and position of the child’s root view.~

This means that in `didMoveToParentViewController:` `view.superview` is still `nil`. Further it would be more reasonable if the parent view controller(`ABKInAppMessageWindowController`) was responsbile for laying out the message view controller's root view.

**Comment by hokstuff** [comment]
Hi @k0nserv,

Thank you for reaching out and filing this issue with these technical details. We are now tracking this ticket internally.

Best,
Daniel

**Comment by hokstuff** [comment]
Hi @k0nserv,

Thanks for filing this issue about our SDK. I'm updating here because we are planning to address this more holistically in our upcoming Swift SDK. Please reference [this thread to sign up for our early access program](https://github.com/Appboy/appboy-ios-sdk/issues/325) and stay tuned for additional updates regarding the new SDK!

Since there are no immediate follow ups for this issue, I am closing it out. Thank you for understanding!
