### ISSUE TITLE
Version 3.21.0 missing arm64 symbols

### ISSUE THREAD

**Issue by kylefinley** [Appboy/appboy-ios-sdk#212]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | NA
 SDK Version             | 3.21.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 10.2.1 
 Repro rate              | 100%
 
## What did you do?

Use AppFlow to build the iOS .ipa

## What did you expect to happen?

The build to succeed.

## What happened instead?

A build error:

```
▸ Linking Appboy_iOS_SDK

❌  ld: symbol(s) not found for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

[03:44:40]: ▸ ❌  ld: symbol(s) not found for architecture arm64
[03:44:40]: ▸ ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

## Steps to reproduce

- Add `pod 'Appboy-iOS-SDK', '= 3.21.0'` to the Podspec file.
- `pod install`
- `xcodebuild -showBuildSettings -workspace /path-to-workspace -scheme App`

**Comment by Bucimis** [comment]
@kylefinley we weren't able to reproduce this on our end, either through XCode or using `xcodebuild`. Could you potentially dry deleting derived data, updating the local pods repo, cleaning the build, and trying again?

**Comment by LiberAC** [comment]
I'm seeing the problem described as well, specifically 

> Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      -[Appboy registerDeviceToken:] in libAppboyKitLibrary.a(Appboy.o)
      +[ABKURLUtilities openURL:] in libAppboyKitLibrary.a(ABKURLUtilities.o)
      +[ABKUtilityFunctions dynamicColorForLightColor:darkColor:] in libAppboyKitLibrary.a(ABKUtilityFunctions.o)
      ___60+[ABKPushSettings readAndStoreCurrentPushSettingsWithFlush:]_block_invoke in libAppboyKitLibrary.a(ABKPushSettings.o)
      +[ABKPushSettings storePushAuthStatus:withFlush:] in libAppboyKitLibrary.a(ABKPushSettings.o)
      +[ABKPushSettings readAndStoreCurrentPushDisplayOptions:withFlush:] in libAppboyKitLibrary.a(ABKPushSettings.o)
ld: symbol(s) not found for architecture x86_64

> 

I tried delete all the derived data, update the local repo, clean and try again

**Comment by Bucimis** [comment]
@LiberAC what version of XCode are you using?

**Comment by LiberAC** [comment]
> @LiberAC what version of XCode are you using?

Version 10.2.1 (10E1001)

**Comment by Bucimis** [comment]
Hi @LiberAC,

Thanks for the followup. We built 3.21.0 with XCode 11 (prior versions were built on 10) and some of our version gating code caused XCode 11 to insert symbols that XCode 10 doesn't recognize. Going forward, we expect to continue to build and release with XCode 11, so to upgrade to 3.21+, you will need to upgrade your XCode version to 11. Our apologies for not including this in our changelog entry, we'll be adding that soon.

**Comment by hokstuff** [comment]
Hi @LiberAC,

Please let us know if you are still experiencing these issues after updating to Xcode 11. We will include a note about this in the Changelog in our next release. I'm going to close out this issue - feel free to reopen if you have any concerns.
