### ISSUE TITLE
Nothing showing if UIWindowSceneDelegate enabled

### ISSUE THREAD

**Issue by dolzhenko-tony** [Appboy/appboy-ios-sdk#213]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios
 Platform Version        | e.g. 13.2.2
 SDK Version             | e.g. 3.21.0
 Integration Method      | e.g. cocoapods
 Xcode Version           | e.g. Xcode 11.2.1
 Repro rate              | e.g. all the time (100%)
 
## What did you do?

- Use slideup code from example: https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery/#real-time-in-app-message-creation--display

## What did you expect to happen?

Slideup with "YOUR_CUSTOM_SLIDEUP_MESSAGE" message appear and disappear after 2.5 secs.

## What happened instead?

No slideup shown. And actually no other popups showing if UIWindowSceneDelegate introduced in iOS13 implemented.

## Steps to reproduce

- Add `pod 'Appboy-iOS-SDK'` to the Podspec file and install via Cocoapods
- Add `Appboy.start(withApiKey: key, in: application, withLaunchOptions: launchOptions)` method in 
- implement `func application(_ application: UIApplication, configurationForConnecting connectingSceneSession: UISceneSession, options: UIScene.ConnectionOptions) -> UISceneConfiguration` in Appdelegate: `func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool`
- Add UIApplicationSceneManifest key into Info.plist
- Add class conforming UIWindowSceneDelegate

## Code Snippet

```let customInAppMessage = ABKInAppMessageSlideup.init()
    customInAppMessage.message = "YOUR_CUSTOM_SLIDEUP_MESSAGE"
    customInAppMessage.duration = 2.5
    customInAppMessage.extras = ["key": "value"]
    Appboy.sharedInstance()!.inAppMessageController.add(customInAppMessage)
    Appboy.sharedInstance()!.inAppMessageController.displayNextInAppMessage(with: nil)```

**Comment by hokstuff** [comment]
Hi @dolzhenko-tony,

Thanks for pointing this out. We currently don't support `UIWindowSceneDelegate`. We are investigating adding support for it but right now we don't have a timeline for a release.

Regards,
Daniel

**Comment by mdyson** [comment]
Will there be support for this on your roadmap any time soon? This is breaking in app messages for my team and we are not planning on reverting code to the deprecated way to support this feature.

**Comment by hokstuff** [comment]
Hi @mdyson,

We have recently re-prioritized this issue and are planning on tackling it on the sooner side, but we are not sure how long that will take.

Thank you for making a PR for a temporary fix! Our plan is to make a more involved change in the future, but it seems like yours may be sufficient to work for your situation in the meantime :)

Best,
Daniel

**Comment by hokstuff** [comment]
Hi @dolzhenko-tony and @mdyson,

We have released an update adding support for `UIWindowSceneDelegate` in our latest release 3.23.0 found [here](https://github.com/appboy/appboy-ios-sdk/releases). Please let us know if you have any issues - thank you!
