### ISSUE TITLE
In-app message do not trigger any webview

### ISSUE THREAD

**Issue by juliensechaud** [Appboy/appboy-ios-sdk#215]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.2 / 13.1.3 / 12.4.1 / 10.3
 SDK Version             | 3.20.2
 Integration Method      | carthage
 Xcode Version           | Xcode 10.3
 Repro rate              | 100%
 
## What did you do?

I created a in-app message campaign with an URL within the html (a href)

## What did you expect to happen?

The in app is presented with correct content
A web view is presented when touching the link

## What happened instead?

Nothing happens. The in app closes but there is not any web view presenting

## Steps to reproduce

Just create a in app message campaign with link inside. Run it on 10.3 for example. The web view is not presenting when touching in app

**Comment by Bucimis** [comment]
Hi @juliensechaud, thanks for getting in contact. Would you be able to contact support@braze.com with a link to the campaign in question and full steps to repro? I want to take a look at how the deep links/IAM were constructed.

**Comment by hokstuff** [comment]
Due to inactivity on this thread, I am closing it out. If you have any further questions, feel free to contact support@braze.com or re-open this issue.
