### ISSUE TITLE
SDK not working on the tvOS, even with the example project

### ISSUE THREAD

**Issue by gurhub** [Appboy/appboy-ios-sdk#217]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | tvos
 Platform Version        | 13.3.1
 SDK Version             | 3.21.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.3.1
 Repro rate              | all the time (100%)
 
## What did you do?

Integrate Braze through Cocoapods.

## What did you expect to happen?

Braze SDK is integrated properly and creating sessions. And able to see ChangeUser method work.

## What happened instead?

Braze SDK doesn't create any sessions for the test user. Unable to see anything with my userID on Dashboard even after hours.

## Steps to reproduce

Example:
- Add `pod 'Appboy-tvOS-SDK'` to the Podspec file.
- Add `[Appboy startWithApiKey:inApplication:withLaunchOptions:];` method in `application:didFinishLaunchingWithOptions:` method in `AppDelegate.m`.
- Add '[[Appboy sharedInstance] changeUser:@"123456"];' method when user logged in, at the 'SomeViewController.m'
- Run the app.
- Also, I downloaded the example tvOS application from 'https://github.com/Appboy/appboy-ios-sdk/tree/master/Example/tvOS_Stopwatch' 
- Created a new API Key at the Dashboard 
- Added new API Key in the example project
- Changed project's bundleIdentifier with mine to Run on the real device
- Run the app
- Only tried the ChangeUser button. 

## Code Snippet

No need the share code, cause I used the example project from 'https://github.com/Appboy/appboy-ios-sdk/tree/master/Example/tvOS_Stopwatch' 

## Project that demonstrates the issue

https://github.com/Appboy/appboy-ios-sdk/tree/master/Example/tvOS_Stopwatch

**Comment by Bucimis** [comment]
@gurhub did you specify your cluster per https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/cocoapods/#step-5-specify-your-data-cluster? If you enable verbose logging (see https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/optional_idfa_collection/#verbose-logging), you should be able to see requests flowing to the Braze backend with explanatory error messages when they don't succeed.

**Comment by gurhub** [comment]
Hi Bucimis, 

Thank you for your help, specifying the data cluster fixed my issue. Now it works. Thank you very much for your help.

Best Regards
