### ISSUE TITLE
can you create demo for inApp message in swift 4.0?

### ISSUE THREAD

**Issue by Chandanjee** [Appboy/appboy-ios-sdk#218]
* [ ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 12.1
 SDK Version             | e.g. 3.10.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 10.1
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once

**Comment by Bucimis** [comment]
Hi @Chandanjee, which use case are you looking for examples for? Our Hello Swift app contains examples for certain in-app message use cases https://github.com/Appboy/appboy-ios-sdk/blob/master/HelloSwift/HelloSwift/AppDelegate.swift

**Comment by hokstuff** [comment]
I'm closing out this thread due to inactivity. Please re-open if there are any further questions on this topic.
