### ISSUE TITLE
ASWebAuthenticationSession web view abruptly closed when the keyboard is shown

### ISSUE THREAD

**Issue by n-p-s** [Appboy/appboy-ios-sdk#221]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12
 SDK Version             | 3.21.1
 Integration Method      | CocoaPods
 Xcode Version           | Xcode 11.3.1
 Repro rate              | All the time
 
## What did you do?

- Show an in-app message (either manually or through a campaign)
- Try authenticating via [`ASWebAuthenticationSession`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession) with the in-app message still shown on the screen
- Tap on a text field or do an action to show the keyboard

## What did you expect to happen?

- The embedded web view stays opened and the keyboard is shown.

## What happened instead?

- As soon as the keyboard is shown, the embedded web view is abruptly closed.

## Steps to reproduce

- Show an in-app message
- Initialize a new [`ASWebAuthenticationSession#init`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/2990952-init) 
  - Third party authentication server URL can be used i.e. `(https://github.com/login/oauth/authorize?client_id={clientId)`
- Load the webpage via [`ASWebAuthenticationSession#start`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/2990953-start)
- Tap on a text field or do an action to show the keyboard

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No.

This issue seems to be originating from [`ABKInAppMessageWindowController#keyboardWasShown`](https://github.com/Appboy/appboy-ios-sdk/blob/009d613978b33d5120e82ee47471fbc5928cb855/AppboyUI/ABKInAppMessage/ViewControllers/ABKInAppMessageWindowController.m#L223). 
- When starting the authentication process, the view controller hosting the web view is launched within the in-app message window. 
- Tapping on a field in the authentication form causes the keyboard to be shown, which in turn hides the entire window.

![InAppMessageBug](https://user-images.githubusercontent.com/6024770/76615302-dd80b480-6575-11ea-9bae-74ad7033e7e7.png)

Sidenote: I was able to work around this issue in iOS 13 by utilizing a new property ([`presentationContextProvider`](https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession/3237232-presentationcontextprovider)) that tells the system in which `UIWindow` to show the embedded web view in.

**Comment by hokstuff** [comment]
Hey @n-p-s,

We recommend to avoid displaying an in-app message and running a web authentication session simultaneously. You may be able to use in-app message delegate methods to work around this issue or can use the workaround you already provided.

Thanks,
Daniel
