### ISSUE TITLE
Empty content cards screen message overflows

### ISSUE THREAD

**Issue by J-Mendes** [Appboy/appboy-ios-sdk#222]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 13.3
 SDK Version             | 3.21.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.3.1
 Repro rate              | all the time (100%)
 
## What did you do?
Open the content cards screen with no cards when the phone language is fr-FR.

## What did you expect to happen?
The no card text will fit inside the visible screen area splitting into multiple lines as needed.

## What happened instead?
The no card text only has 1 line and is overflowing on the sides making it not completely readable.

## Steps to reproduce
Open the content cards screen with no cards when the phone language is fr-FR. There's a screenshot in attachment so you can see the issue.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
No.

## Attachment
![Image from iOS](https://user-images.githubusercontent.com/22790910/76785872-186d2d00-67ae-11ea-95c4-65e1c67f3e3d.png)

**Comment by hokstuff** [comment]
Hi @J-Mendes,

Thanks for pointing out this bug. We have reproduced it on our end and will be tracking this ticket internally.

Best,
Daniel

**Comment by hokstuff** [comment]
We have now fixed this in our [latest 3.22.0 release](https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.22.0). Please let us know if you still are experiencing this issue - thanks!
