### ISSUE TITLE
ABKModalViewController doesn't fullScreen 

### ISSUE THREAD

**Issue by AdrianaCarelli** [Appboy/appboy-ios-sdk#225]
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        | 12 - 13
 SDK Version             | 3.21.3
 Integration Method      |  cocoapods 
 Xcode Version           |  Xcode 11.3
 Repro rate              |  all the time (100%) 
 
## What did you do?

In an inAppMessage popup which then has to open a full screen web page

## What did you expect to happen?

the web page must be full screen

## What happened instead?

the web page is not full screen and the navigationBar is missing which is transparent

## Steps to reproduce

- Create an InAppMessage with a button whose action is Redirect to Web Url.

- Write a url

- Flag the Open WebView inside App

- Sent campaign

- It opens a webView not full screen and with the transparent navigationBar.

**Comment by AdrianaCarelli** [comment]
![IMG_0434](https://user-images.githubusercontent.com/13485239/78899349-93f09000-7a75-11ea-9a49-1a459008caba.jpeg)

**Comment by hokstuff** [comment]
Hi @AdrianaCarelli,

We are unable to reproduce this issue. Are you doing any customizations for our in-app messages, and is this happening for all types of in-app messages or just for modal ones? Also, if you can send over a screenshot of your view hierarchy, that would be helpful as well.

If you don't want to post this directly on Github, you can contact support@braze.com and we can continue the conversation on that thread.

Thanks,
Daniel

**Comment by bstillitano** [comment]
This is due to the new model style presentation in iOS 13. Compiling with the latest version of Xcode reliably reproduces this.

**Comment by hokstuff** [comment]
Are you doing any customization for your UI? On SDK version 3.21.3, iOS 13.3.1, and using the latest Xcode 11.4, I am seeing the default gray background behind the "Done" button, as shown in this image when opening a web url inside the app.
https://i.stack.imgur.com/BPuWH.png

**Comment by hokstuff** [comment]
Are you still experiencing this issue @AdrianaCarelli @bstillitano?

**Comment by AdrianaCarelli** [comment]
@hokstuff Yes, I was unable to solve it.

**Comment by hokstuff** [comment]
@AdrianaCarelli Can you send any customization that you may be doing for the UI? Also, can you send a screenshot of your view hierarchy so we can investigate the issue you're experiencing?

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. Please contact our Support team with more details if you want us to investigate further - thanks!
