### ISSUE TITLE
NSSecureCoding usage to avoid unsafe serialization API

### ISSUE THREAD

**Issue by maru-kulkova-earnin** [Appboy/appboy-ios-sdk#227]
# Report
There are a few classes in Appboy iOS SDK that use `NSCoding` protocol. However, this protocol does not verify the type of object upon deserialization. Thus, it is vulnerable to object substitution attacks. A maliciously crafted payload which is deserialized via the `NSCoding` protocol can result in attacker-controlled code being executed.

Apple provides the [`NSSecureCoding` protocol](https://developer.apple.com/documentation/foundation/nssecurecoding?language=objc) which is robust against this type of attack.
`NSSecureCoding` protects against object substitution attacks by requiring the programmer to declare the expected type of object before deserialization completes. Thus, if an invalid
object is deserialized, the error can be handled safely.

## Code Snippet
Example of NSSecureCoding usage

```
// Declare that your class conforms to NSSecureCoding
@interface MySecureObject : NSObject <NSSecureCoding>
@property (nonatomic, retain) NSDictionary *myData;
@end

@implementation MySecureObject
+ (BOOL)supportsSecureCoding {
    // Must override this class delegate method to reture YES
    return YES;
}

- (id)initWithCoder:(NSCoder *)decoder {
    if ((self = [super init])) {
        // When decoding sub-objects, use @selector(decodeObjectOfClass:forKey:)
        // This method will throw an exception if the deserialized object's class doesn't match the expected class
        self.myData = [decoder decodeObjectOfClass:[NSDictionary class] forKey:@"myData"];
    }
    return self;
}

- (void)encodeWithCoder:(NSCoder *)encoder {
    [encoder encodeObject:self.myData forKey:@"myData"];
}
@end
```

## Request 
Could the Appboy iOS SDK be updated to utilize the `NSSecureCoding` protocol?

**Comment by lowip** [comment]
Hi @maru-kulkova-earnin,

Thank you for reaching out and filing this issue with these technical details. We are now tracking this ticket internally.

Best,
Louis

**Comment by maru-kulkova-earnin** [comment]
@lowip great, thank you👍
