### ISSUE TITLE
Get Rid of APPBoy Logs in XCOde

### ISSUE THREAD

**Issue by deepak4u2006** [Appboy/appboy-ios-sdk#228]
2020-04-30 XX:XX:XX.XXXXXX+0530 MYAppName[XXXX:XXXXX] [APPBOY][DEBUG] +[ABKPushSettings storePushAuthStatus:withFlush:] Stored push auth status was already authorized. Not updating persistent storage.

In My Xcode debug area is filled with these kind of logs, And the useful logs are very difficult to locate.
Can you pls guide to avoid this.

Sorry for posting it here as issue but I didn't got any help, anywhere else.

Thanks in Advance!!

**Comment by Bucimis** [comment]
Hi @deepak4u2006 To disable logging, add a dictionary named `Appboy` to your Info.plist file. Inside the `Appboy` Dictionary, add the `LogLevel` String subentry and set the value to `8`.

Example `Info.plist` contents:
```
<key>Appboy</key>
<dict>
	<key>LogLevel</key>
	<string>8</string>
</dict>
```

**Comment by deepak4u2006** [comment]
> Hi @deepak4u2006 To disable logging, add a dictionary named `Appboy` to your Info.plist file. Inside the `Appboy` Dictionary, add the `LogLevel` String subentry and set the value to `8`.
> 
> Example `Info.plist` contents:
> 
> ```
> <key>Appboy</key>
> <dict>
> 	<key>LogLevel</key>
> 	<string>8</string>
> </dict>
> ```

Thanks!!, Working .
Closing the issue.
