### ISSUE TITLE
.strings files are not accessible (via Carthage)

### ISSUE THREAD

**Issue by anaglik** [Appboy/appboy-ios-sdk#231]
[*] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

When SDK is integrated via Carthage, localization files are not accessible. (Although Appboy.bundle is properly located inside framework). When e.g error occurs, string key is displayed instead of translated text. (e.g APPBOY.NO-CONNECTION.MESSAGE). In documentation you mentioned _"For your convenience, our CocoaPod integrates the .strings files for the aforementioned languages"_. How to integrate .strings files when using Carthage? What is preferred way to do that?

## Environment

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | all
 SDK Version             | 3.21.3
 Integration Method      | Carthage
 Xcode Version           | Xcode 11.4
 Repro rate              | all the time (100%)

**Comment by Bucimis** [comment]
@anaglik thanks for bringing this to our attention. Are you accessing our string values programmatically for display in your own view controller or are the string values in the Appboy UI (for example, `ABKContentCardsTableViewController`) displaying incorrectly?

**Comment by anaglik** [comment]
@Bucimis Thanks for quick response. Missing strings are coming from Appboy UI. (in my case In-App Message feature)
<img width="515" alt="screenshot-appboy" src="https://user-images.githubusercontent.com/845465/81570237-9c9ff300-93a0-11ea-8558-47cf7ce30b5a.png">

**Comment by Bucimis** [comment]
@anaglik thanks - for context, which language did you use to test?

**Comment by anaglik** [comment]
Screenshot above is from simulator running English. I was also testing other languages (e.g Polish) on real device and it works the same way.

**Comment by chshapiro** [comment]
Hey @anaglik,

We were unable to repro the issue you are using. Can you send a sample app that repros the issues? If you're not comfortable posting it here, you can email it to support@braze.com.

Thanks!

**Comment by anaglik** [comment]
Hey @chshapiro,

Issue was caused by "Show non-localized strings" feature turned on for debug scheme. When it is turned off all work as expected. Let's close that ticket now. Once again, thanks for quick responses.
