### ISSUE TITLE
[Question] About change External ID

### ISSUE THREAD

**Issue by taehyun-park-woowahan** [Appboy/appboy-ios-sdk#232]
Hi there,
I'm asking because the External ID setting is not working.

First of all, this is the current situation.
Previously, External ID was being used as the ID used in the service.
(use `changeUser` function)

After, Changed to a spec that requires sending push even logged-out users, so I tried to change the External ID from the ID used in the service to the Device UUID, but it is not set properly.
(Using `UIDevice.current.identifierForVendor?.uuidString`)

If you know anything about the cause of the failure to set, please reply.

**Comment by hokstuff** [comment]
Hi @taehyun-park-woowahan,

It sounds like your question is a better fit for our Support team. They will be able to work with your specific situation to answer any questions you have - please reach out to them at support@braze.com so they can assist you.

Thanks!
