### ISSUE TITLE
IAM is never shown when keyboard is presented - ABKDisplayInAppMessageLater is never shown

### ISSUE THREAD

**Issue by danielCarlosCE** [Appboy/appboy-ios-sdk#237]
* [√] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report
IAMs are not shown when the keyboard is still presented. 20% of our uses are not getting IAM because of this problem. 

We're now waiting for the keyboard and screen to be dismissed before sending the event to the SDK. 

Here's your own log:
```
Initially setting in-app message display choice to ABKDisplayInAppMessageLater due to visible keyboard.
[ABKInAppMessageController handleExistingInAppMessagesInStackWithDelegate:] handleExistingInAppMessagesInStackWithDelegate:: ABKDisplayInAppMessageLater received. Returning in-app message to the stack.
```

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13.3.1
 SDK Version             | 3.24.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 11.5 
 Repro rate              | all the time for our QA; 20% for our users
 
## What did you do?

Set a campaign with triggers based on events. 
Send the event from the app through SDK.

## What did you expect to happen?

Show the IAM from the campaign we set

## What happened instead?

IAM didn't show

**Comment by hokstuff** [comment]
Hi @danielCarlosCE,

We explicitly do not display an IAM when the keyboard is presented on iOS because the rendering is undefined. To customize this behavior, please reference [our docs here](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/customization/#overriding-in-app-messages-before-display). Thanks!

**Comment by danielCarlosCE** [comment]
I would suggest adding this to your troubleshooting page and making sure your support is aware of it.
