### ISSUE TITLE
Is there a way to force a Sync Down?

### ISSUE THREAD

**Issue by danielCarlosCE** [Appboy/appboy-ios-sdk#238]
We're updating the user attributes via our backend. We want to trigger sync down to the SDK so it has the right campaigns based on the new attribute.

**Comment by Bucimis** [comment]
Hi @danielCarlosCE, thanks for getting in touch. Manual trigger syncs aren't currently available due to various technical and product considerations. I've logged your product feedback and will stay in touch as the landscape changes here, but I'll be closing the issue for now.
