### ISSUE TITLE
iOS 14 Crash - ABKInAppMessageWindowController.m line 301

### ISSUE THREAD

**Issue by ardiansyahrkt** [Appboy/appboy-ios-sdk#239]
* [ ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report
We have crashed on IOS 14 related to appboy.
This is the crash report we get from crashlytics.

<img width="982" alt="Screenshot 2020-07-07 at 9 18 33 AM" src="https://user-images.githubusercontent.com/55971968/86684177-e1f53f80-c034-11ea-9456-5363565d917a.png">

<img width="982" alt="Screenshot 2020-07-07 at 9 18 33 AM" src="https://user-images.githubusercontent.com/55971968/86682437-28499f00-c033-11ea-8976-d70cec37740c.png">

Full stack trace of the crash:
<pre>
<code>
Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0x1a1270344 __abort_with_payload + 8
1  libsystem_kernel.dylib         0x1a1274b20 <redacted> + 104
2  libsystem_kernel.dylib         0x1a1274ab8 abort_with_reason + 30
3  libobjc.A.dylib                0x1a11b18ec <redacted> + 108
4  libobjc.A.dylib                0x1a11b1880 <redacted> + 30
5  libobjc.A.dylib                0x1a11ad558 <redacted> + 350
6  libobjc.A.dylib                0x1a11af388 objc_storeWeak + 340
7  UIKitCore                      0x1a59d8ae0 <redacted> + 120
8  UIKitCore                      0x1a59d8b60 <redacted> + 88
9  UIKitCore                      0x1a5eccc18 <redacted> + 412
10 UIKitCore                      0x1a5eccf64 <redacted> + 476
11 UIKitCore                      0x1a5ecceb4 <redacted> + 300
12 UIKitCore                      0x1a5ecceb4 <redacted> + 300
13 UIKitCore                      0x1a5ecceb4 <redacted> + 300
14 UIKitCore                      0x1a5ecceb4 <redacted> + 300
15 UIKitCore                      0x1a5ecceb4 <redacted> + 300
16 UIKitCore                      0x1a5ecceb4 <redacted> + 300
17 UIKitCore                      0x1a5ecceb4 <redacted> + 300
18 UIKitCore                      0x1a5ecceb4 <redacted> + 300
19 UIKitCore                      0x1a5ecceb4 <redacted> + 300
20 UIKitCore                      0x1a5647900 <redacted> + 928
21 UIKitCore                      0x1a5645c2c <redacted> + 1036
22 UIKitCore                      0x1a56bf720 <redacted> + 40
23 UIKitCore                      0x1a5188844 <redacted> + 248
24 UIKitCore                      0x1a5188b44 <redacted> + 136
25 UIKitCore                      0x1a51881c0 <redacted> + 220
26 UIKitCore                      0x1a5bd3e9c <redacted> + 64
27 UIKitCore                      0x1a5bbba6c <redacted> + 88
28 UIKitCore                      0x1a5bba4b0 <redacted> + 132
29 UIKit                          0x1ddeea390 <redacted> + 368
30 Appboy_iOS_SDK                 0x10181a674 -[ABKInAppMessageWindowController hideInAppMessageWindow] + 301 (ABKInAppMessageWindowController.m:301)
31 UIKitCore                      0x1a608c3c0 <redacted> + 724
32 UIKitCore                      0x1a605f9a4 <redacted> + 248
33 UIKitCore                      0x1a605fed8 <redacted> + 248
34 UIKit                          0x1ddee5744 <redacted> + 204
35 QuartzCore                     0x1a90105d0 <redacted> + 280
36 libdispatch.dylib              0x1a1116394 <redacted> + 20
37 libdispatch.dylib              0x1a11236ec _dispatch_main_queue_callback_4CF + 836
38 CoreFoundation                 0x1a13f6bf0 <redacted> + 16
39 CoreFoundation                 0x1a13f11d0 <redacted> + 1936
40 CoreFoundation                 0x1a13f0630 CFRunLoopRunSpecific + 564
41 GraphicsServices               0x1ad1ca818 GSEventRunModal + 164
42 UIKitCore                      0x1a5b7da38 <redacted> + 1072
43 UIKitCore                      0x1a5b83928 UIApplicationMain + 1876
44 mudah.my                       0x100c41ec8 main + 21 (AppDelegate.swift:21)
45 libdyld.dylib                  0x1a127c38c <redacted> + 4
</code>
</pre>
## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 14
 SDK Version             | 3.24.1
 Integration Method      | cocoapods
 Xcode Version           | 11.4
 Repro rate              | sometimes
 
## What did you do?
We were not able to reproduce it.

## What did you expect to happen?
Not crash

## What happened instead?
In crashlytics it show sometimes user facing this crash.

## Steps to reproduce
We are not able to reproduce it.

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
we are not doing any kind of customization.

**Comment by chshapiro** [comment]
Hey @ardiansyahrkt,

Thank you for reporting this issue! We don't yet fully support iOS 14 but we are preparing for its upcoming release and are looking into this crash. Are you only seeing the crash happening on iOS 14 or also on earlier versions? Do you still see the crashes happening on the latest Xcode and iOS 14 betas?

Thanks!

**Comment by hokstuff** [comment]
Closing this out due to inactivity. Please reopen if you are still seeing issues when using the 3.27.0 beta releases, or check back soon when we release our official support for iOS 14. Thanks!
