### ISSUE TITLE
duplicate symbol compile error

### ISSUE THREAD

**Issue by ryanfitz** [Appboy/appboy-ios-sdk#24]
I'm installing the SDK using cocoapods and get the following error when attempting to compile my project after installing the sdk.

```
duplicate symbol _OBJC_METACLASS_$_ABKIdentifierForAdvertisingProvider in:
    /Users/fitz/Library/Developer/Xcode/DerivedData/cinch-bsigrzsqyxpxnvhdxwmrkscdlhbt/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-cinch-Appboy-iOS-SDK.build/Objects-normal/x86_64/ABKIdentifierForAdvertisingProvider-1DCF61E52A8AB26B.o
duplicate symbol _OBJC_CLASS_$_ABKIdentifierForAdvertisingProvider in:
    /Users/fitz/Library/Developer/Xcode/DerivedData/cinch-bsigrzsqyxpxnvhdxwmrkscdlhbt/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-cinch-Appboy-iOS-SDK.build/Objects-normal/x86_64/ABKIdentifierForAdvertisingProvider-1DCF61E52A8AB26B.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm using cocoapods 0.37.2 on an iOS 8 only app, my podfile is using the `use_frameworks!` directive.

**Comment by Wenzhi** [comment]
Hi Ryan,

Thank you for reporting the issue! I can reproduce the issue and the problem is that our podspec doesn't support `use_framworks!` right now. 

I can provide the content of an updated podspec file. You just need to create a `Appboy-iOS-SDK.podspec` file with the content, and use that podspec in your Podfile with `pod 'Appboy-iOS-SDK', :podspec => '/You_Appboy_Podspec_Path/Appboy-iOS-SDK.podspec'`. The support will also be added in our next release. 

Here is the new podspec:
```
Pod::Spec.new do |s|
  s.name         = "Appboy-iOS-SDK"
  s.version      = "2.11.3"
  s.summary      = "This is the Appboy iOS SDK for Mobile Marketing Automation"
  s.homepage     = "http://www.appboy.com"
  s.license      = { :type => 'Commercial', :text => 'Please refer to https://github.com/Appboy/appboy-ios-sdk/blob/master/LICENSE'}
  s.author       = { "Appboy" => "http://www.appboy.com" }
  s.source       = { :git => 'https://github.com/Appboy/appboy-ios-sdk.git', :tag => s.version.to_s}
  s.platform = :ios
  s.ios.deployment_target = '6.0'
  s.requires_arc = false
  s.documentation_url = 'http://documentation.appboy.com/'
  s.frameworks = 'SystemConfiguration', 'QuartzCore', 'CoreImage', 'CoreText'
  s.weak_framework = 'CoreTelephony', 'Social', 'Accounts', 'AdSupport', 'StoreKit'
  s.source_files = 'AppboyKit/headers/AppboyKitLibrary/*.h', 'AppboyKit/*.m'
  s.exclude_files = 'AppboyKit/**/*.txt'
  s.resource = 'AppboyKit/Appboy.bundle'
  s.preserve_paths = 'AppboyKit/**/*.*'
  s.vendored_libraries = 'AppboyKit/libAppboyKitLibrary.a'
  s.dependency 'SDWebImage', '~>3.7.0'
end
```

We’ll update with information regarding the timeline of the next release when it becomes available, but it should be sometime in the near future.

Please let me know if it doesn't work for you, or you have any other questions.

**Comment by ryanfitz** [comment]
thanks @Wenzhi I created a [fork](https://github.com/ryanfitz/appboy-ios-sdk/tree/dynamic_framework) with the podspec updates and everything is working.

**Comment by ryanfitz** [comment]
Im running into a runtime error when attempting to load up the feedback view controller.

```
2015-06-09 11:12:04.943 cinch[82294:8637474] [APPBOY] Couldn't find /Appboy.bundle/ or /ABKFramework2.framework/
2015-06-09 11:12:04.944 cinch[82294:8637474] [APPBOY] Found at /private/var/mobile/Containers/Bundle/Application/576C75DA-FCE9-49D2-8367-14B5CC8C5B9B/cinch.app
2015-06-09 11:12:04.949 cinch[82294:8637474] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </private/var/mobile/Containers/Bundle/Application/576C75DA-FCE9-49D2-8367-14B5CC8C5B9B/cinch.app> (loaded)' with name 'ABKFeedbackContentView''
```

Seems like a framework isn't getting properly setup with the current podspec

**Comment by Wenzhi** [comment]
Hi Ryan,

It seems that by using `use_framework!`, Cocoapods not only converts our SDK from a library to a framework, but also changes the path of the bundle. It requires an SDK update to fix the issue.

If you have to use the `use_framework!`, I would suggest you to do a manual integration for now.  We’ll update this issue with the release timeline when it becomes available, which we expect to be early next week.

**Comment by Clifton-Roberts** [comment]
Hi @Wenzhi - any word on this issue?

**Comment by briancaw** [comment]
Hi @Clifton-Roberts 

We're investigating the runtime path error today and we'll update before the end of day (EST) with information regarding our plans/timeline for fixing (which I suspect should be tomorrow, barring complications).

Thanks,
Brian

**Comment by Wenzhi** [comment]
Hi @ryanfitz and @Clifton-Roberts 

We just released Appboy SDK version 2.12.0 with the fix of this issue. Now the SDK supports dynamic framework and swift apps. Please let us know if you have any other issues :)

**Comment by ryanfitz** [comment]
Thanks @Wenzhi! I updated my app and its working great

**Comment by Clifton-Roberts** [comment]
@Wenzhi Perfect! Thanks for addressing this.
