### ISSUE TITLE
Use CocoaPod's resource_bundle

### ISSUE THREAD

**Issue by k0nserv** [Appboy/appboy-ios-sdk#241]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

Braze causes apps that integrate it to look like they support all localizations that Braze supports because of `s.resources` and the copy bundle resource step. Per https://github.com/CocoaPods/CocoaPods/issues/1930 the issue should solve itself if the pod uses `s.resource_bundle` instead of `s.resources`.

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | All
 SDK Version             | All
 Integration Method      | cocoapods
 Xcode Version           | All
 Repro rate              | 100%
 
## What did you do?

Integrate Braze through CocoaPods

## What did you expect to happen?

Braze not to modify the langauges listed as supported by my app.

## What happened instead?

Braze's localisation support causes my app to seem like it supports languages it doesn't support. 

## Steps to reproduce

- Create an example app
- Integrate Braze with CocoaPods(Not using `use_frameworks!`)
- Build and install the app
- Observe that the app professes to support all languages that Braze supports

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-07-15 at 10 59 42](https://user-images.githubusercontent.com/1333960/87531917-4f831a80-c68a-11ea-9290-5aabb65ec925.png)

## Project that demonstrates the issue

[BrazeLocalizationIssue.zip](https://github.com/Appboy/appboy-ios-sdk/files/4924395/BrazeLocalizationIssue.zip)

**Comment by hokstuff** [comment]
Hi @k0nserv,

Thanks for the detailed steps to repro and a suggestion for the fix! We are investigating and will let you know when the fix is ready.

**Comment by lucas-mancini** [comment]
Any workarounds for this? I have the same issue.

**Comment by hokstuff** [comment]
Hi @lucas-mancini,

Apologies for the late reply! We are verifying a fix for this issue, which should be ready relatively soon. We will keep you updated for when it gets released.

Thanks for your patience!

**Comment by hokstuff** [comment]
Hi @k0nserv and @lucas-mancini,

We have released [SDK version 3.31.1](https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.31.1) which fixes this issue. Please let us know if you are still experiencing problems - thanks!

**Comment by k0nserv** [comment]
Excellent, thanks for addressing it 🎉

**Comment by lucas-mancini** [comment]
Thank you so much!!
