### ISSUE TITLE
Push notifications setup for Braze sandbox

### ISSUE THREAD

**Issue by danielCarlosCE** [Appboy/appboy-ios-sdk#242]
We're trying to test some push notifications on sandbox but it seems it only works if we use a different bundle identifier. 

When we test with the same bundle identifier as in production, `didRegisterForRemoteNotificationsWithDeviceToken` won't be called at all and the user won't have a token. 

Is there any way around this? Going through the troubleshooting page didn't help us.

**Comment by chshapiro** [comment]
Hey @danielCarlosCE,

Did you make sure your push certificates are set up correctly? Are you using a .p8 or .p12 certificate?

Thanks!

**Comment by danielCarlosCE** [comment]
We're using .p8. It's working fine on prod and it works on sandbox if we run the app from Xcode with a different bundle identifier.
What we want is the same bundle identifier and an ad-hoc build to distribute to the team.

**Comment by danielCarlosCE** [comment]
I got it working. We're signing the build with `distribution` certificate
