### ISSUE TITLE
Support for iOS 14 release version through carthage

### ISSUE THREAD

**Issue by bharathnagarajrao** [Appboy/appboy-ios-sdk#248]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios 
 Platform Version        | 14.0
 SDK Version             | v3.27
 Integration Method      | carthage
 Xcode Version           | Xcode 12 beta 4
 Repro rate              | all-time
 
## What did you do?

As per this integration document, for iOS 14 compatibility, we would like to update  appboy SDK to beta version, ie 3.27
https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/ios_14/#upgrade-summary

## What did you expect to happen?

As per this integration document, for iOS 14 compatibility, we would like to update  appboy SDK to beta version, ie 3.27
https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/ios_14/#upgrade-summary

## What happened instead?

Since we use carthage, v3.27* is not available here 
https://raw.githubusercontent.com/Appboy/appboy-ios-sdk/master/appboy_ios_sdk_core.json

## Steps to reproduce

Paste this link in a browser & observe
https://raw.githubusercontent.com/Appboy/appboy-ios-sdk/master/appboy_ios_sdk_core.json

If this is not the right link to add iOS 14 related versions through carthage, could you please share the right link ?

## Code Snippet
-

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
-

## Project that demonstrates the issue
-

**Comment by chshapiro** [comment]
Hey @bharathnagarajrao,

Unfortunately, due to Carthage restrictions, we are unable to release full Carthage support for our beta versions of the SDK. However, we have attached the frameworks to the [release page](https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.27.0-beta3) and you can integrate those into your app.

Please let us know if you have any further questions. Thank you!

**Comment by bharathnagarajrao** [comment]
@chshapiro Thanks for your response. 
There are other [frameworks](https://raw.githubusercontent.com/mParticle/mparticle-apple-sdk/master/mParticle_Apple_SDK.json) which provide beta versions (`8.0.0-beta1`) through carthage. Could we explore that option ? 
Also, may I know if we can expect carthage support once Xcode 12 GM version is released ?

**Comment by chshapiro** [comment]
Hey @bharathnagarajrao,

According to the [Carthage docs](https://github.com/Carthage/Carthage#tag-stable-releases), `Tags without any version number, or with any characters following the version number (e.g., 1.2-alpha-1) are currently unsupported, and will be ignored.` For the future, we can try to investigate what other frameworks are doing to make it work. 

We will release version 3.27.0 of the SDK within a few days of the Xcode 12 GM release, and that will include full Carthage support.

**Comment by bharathnagarajrao** [comment]
Thanks @chshapiro. Appreciate your quick response

**Comment by chshapiro** [comment]
Hey @bharathnagarajrao,

Last week we released version 3.27.0 of the SDK which included Carthage support for iOS 14.
Feel free to reopen if you run into any further issues. Thanks!

**Comment by bharathnagarajrao** [comment]
Thanks @chshapiro. 
We were able to update `3.27.0` through Carthage
