### ISSUE TITLE
Update SDWEBImage to last release to support iOS 14 

### ISSUE THREAD

**Issue by IsmailSafadi** [Appboy/appboy-ios-sdk#249]
We have a conflict in our project we have a last version of SDWebImage 5.9.1 and it supported iOS 14 and resolved some problems with new iOS , and the last version 3.27.0 it supported old version , can you update SDwebimage to last version
<img width="522" alt="Screenshot 2020-09-17 at 15 21 14" src="https://user-images.githubusercontent.com/12133278/93469822-ae1e7c00-f8f9-11ea-85ca-311edbee81de.png">

**Comment by chshapiro** [comment]
Hey @IsmailSafadi,

We're going to update this in an upcoming release. In the meantime, can you pin your app to `~>5.8` in order to fix the conflict?

Thanks!

**Comment by IsmailSafadi** [comment]
no I can not because we support gif image and it has problems in ~>5.8 and it fixed in 5.9 and Animated image it is working correctly in 5.9.1

**Comment by Bucimis** [comment]
@IsmailSafadi thanks for the feedback. We have a fix but would need time to validate it and run through our QA/release process - would early next week work in terms of timeline?

**Comment by romandragan** [comment]
The same for us. We're using latest SDWebImage 5.9.1 to work properly.

**Comment by IsmailSafadi** [comment]
> @IsmailSafadi thanks for the feedback. We have a fix but would need time to validate it and run through our QA/release process - would early next week work in terms of timeline?

Thanks , We wait you

**Comment by hokstuff** [comment]
Hi @IsmailSafadi @romandragan,

We just released [iOS SDK 3.28.0](https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.28.0) which will be compatible with SDKWebImage version `5.9.x`. Thanks!
