### ISSUE TITLE
Option to disable logging

### ISSUE THREAD

**Issue by fluidsonic** [Appboy/appboy-ios-sdk#25]
I'm always happy if a framework logs relevant information which helps with debugging.
But logging should not be enabled for release builds. Unfortunately Appboy directly uses `NSLog` without any option to disable the logging, either through a property or through a compile-time flag.

Please add that, thanks!

PS: The following info is also annoying since it is repeated a lot instead of just printing it once:

```
2015-06-11 12:47:46.958 App[10805:1369245] [APPBOY] ASI code block enabled.
2015-06-11 12:47:46.960 App[10805:1369245] [APPBOY] ASI code block enabled.
2015-06-11 12:47:56.965 App[10805:1369245] [APPBOY] ASI code block enabled.
2015-06-11 12:47:56.965 App[10805:1369245] [APPBOY] ASI code block enabled.
```

**Comment by briancaw** [comment]
Hi @fluidsonic 

We currently change logging behavior between debug and release builds, filtering out all non-critical messaging for release mode.  If there are particular log statements you find noisy and not useful in release builds, please let us know and we can alter their behavior if appropriate.  We'll also reevaluate our current behavior to see if there's logging we find not appropriate for release builds. 

For the particular line you mentioned - we agree that that is noisy as implemented, and we will fix that in the near future.  Thanks for reporting this.

**Comment by Wenzhi** [comment]
Hi @fluidsonic, the 2.12.1 SDK removes the logging of 
```
2015-06-11 12:47:46.958 App[10805:1369245] [APPBOY] ASI code block enabled.
```

Please let us know if you have any other questions.
