### ISSUE TITLE
Crash when clicking on a newsfeed card without clicking behaviour

### ISSUE THREAD

**Issue by carlosnaguilera** [Appboy/appboy-ios-sdk#251]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13.7 and 14.00
 SDK Version             | 3.22 and higher
 Integration Method      | cocoapods 
 Xcode Version           | Xcode 11.5 and 12.0
 Repro rate              | always
 
## What did you do?

Clicked on a news from newsfeed without clicking behaviour

## What did you expect to happen?

App should do nothing, remain in newsfeed and keep working

## What happened instead?

App crashed

## Steps to reproduce

-Create a news in news feed without clicking behaviour
-Try to open that news

## Comments

This is a big issue for us as now we are forced to update to 3.27 in order to be able to release our iOS 14 version

**Comment by chshapiro** [comment]
Hey @carlosnaguilera,

Are you doing any customization on the news feed and are you implementing the `ABKURLDelegate`?

Thanks!

**Comment by carlosnaguilera** [comment]
Braze Support "official" Case #: 00053653

**Comment by carlosnaguilera** [comment]
Hi @chshapiro,

No customisation of news feed
Yes, we implement `ABKURLDelegate`

**Comment by chshapiro** [comment]
Hey @carlosnaguilera can you send us the stack trace? If you don't want to add it to this public issue, you can email it to support@braze.com. It would also be helpful to see your implementation of `ABKURLDelegate`.
Thanks!

**Comment by carlosnaguilera** [comment]
I've forwarded the information you asked and some more to support@braze.com. Thank you!

**Comment by chshapiro** [comment]
@carlosnaguilera, thank you for sending that information over. We have identified the issue and will be releasing a fix early next week.

**Comment by hokstuff** [comment]
Hi @carlosnaguilera,

We've released [iOS SDK 3.28.0](https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.28.0) which should fix the issue you were seeing. Please reopen if you have any further issues - thank you!
