### ISSUE TITLE
Installing via CocoaPods as of version 3.27.0 results in error on PhaseScriptExecution [CP] Embed Pods Frameworks

### ISSUE THREAD

**Issue by hkellaway** [Appboy/appboy-ios-sdk#253]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 12.4+ (likely affects lower, this is the version i caught it on)
 SDK Version             | 3.27.0+
 Integration Method      | CocoaPods
 Xcode Version           | Xcode 11.5
 Repro rate              | 100%
 
## What did you do?

First encountered when running a routine `pod update`. The `Appboy-iOS-SDK` pod resolved to version `3.28.0` (up from `3.26.1`). Afterwards, simply building the project in Xcode fails.

## What did you expect to happen?

Updating the `Appboy-iOS-SDK` pod should leave the application in a state where it can successfully build.

## What happened instead?

The application no longer successfully builds. Build error in Issue Navigator:

```
Command PhaseScriptExecution failed with a nonzero exit code
```

Error message:

```
Showing Recent Messages
/.../AppboyDemo/Pods/Target Support Files/Pods-AppboyDemo/Pods-AppboyDemo-frameworks.sh: line 144: ARCHS[@]: unbound variable
```

## Steps to reproduce

* Create new Xcode project
* Create Podfile (e.g. run `pod init`)
* Add `pod Appboy-iOS-SDK` to Podfile
* Run `pod install`
* Open `.xcworkspace`
* Run the app
* 💥

**Comment by chshapiro** [comment]
Hey @hkellaway,

Version 3.27.0+ of the SDK is [not compatible with Xcode 11](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#3270). If you're still using Xcode 11, you should continue using 3.26.1 until you upgrade to Xcode 12.

**Comment by hkellaway** [comment]
got it - thanks!
