### ISSUE TITLE
Getting data

### ISSUE THREAD

**Issue by IgorGalimski** [Appboy/appboy-ios-sdk#254]
Hi! How can I get a notification's data?
https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/customization/#extracting-data-from-push-notification-key-value-pairs
<img width="1049" alt="Screen Shot 2020-09-27 at 11 02 55" src="https://user-images.githubusercontent.com/19680568/94359599-0f400f80-00b1-11eb-9e6d-42dbca736727.png">

**Comment by hokstuff** [comment]
Hi @IgorGalimski,

You can see the push payload by looking at the `userInfo` object [(like in our sample app here)](https://github.com/Appboy/appboy-ios-sdk/blob/master/Example/Stopwatch/Sources/AppDelegate.m#L122), and the resulting payload will look like the [sample payload here](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/customization/#sample-braze-apple-push-payload). Depending on your integration and how you are testing, there may be other areas to extract the info - if you have any further questions, please forward them to support@braze.com.

Thanks!
