### ISSUE TITLE
Unexpected duplicate tasks - Build error when AppboyKit integrated through SPM

### ISSUE THREAD

**Issue by bharathnagarajrao** [Appboy/appboy-ios-sdk#261]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.0
 SDK Version             | 3.29.1
 Integration Method      | Swift Package Manager (SPM)
 Xcode Version           | e.g. Xcode 12.0 (12A7209)
 Repro rate              | all the time (100%)
 
## What did you do?

I forked [Appboy](https://github.com/Appboy/appboy-ios-sdk) repo into our enterprise Github & tried adding it as dependency through **Swift Package Manager** pointing to the commit Id _75647ca863868b46fe4015124456381b58ac491a_
<img width="798" alt="appboy" src="https://user-images.githubusercontent.com/37772020/97948162-b18c9a80-1db5-11eb-8faf-47b1c21af3b2.png">

If I build the project, i am seeing this build error

```
Unexpected duplicate tasks:
1) Target 'MyProject' (project 'MyProject') has copy command from '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/SourcePackages/artifacts/Appboy_iOS_SDK/AppboyKitLibrary.xcframework/ios-arm64_i386_x86_64-simulator/libAppboyKitLibrary.a' to '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/Build/Products/Debug-iphonesimulator/MyProject.framework/Frameworks/libAppboyKitLibrary.a'
2) Target 'MyProject' (project 'MyProject') has copy command from '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/SourcePackages/artifacts/Appboy_iOS_SDK/AppboyKitLibrary.xcframework/ios-arm64_i386_x86_64-simulator/libAppboyKitLibrary.a' to '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/Build/Products/Debug-iphonesimulator/MyProject.framework/Frameworks/libAppboyKitLibrary.a'
```

## What did you expect to happen?

Build Appboy through SPM

## What happened instead?

```
Unexpected duplicate tasks:
1) Target 'MyProject' (project 'MyProject') has copy command from '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/SourcePackages/artifacts/Appboy_iOS_SDK/AppboyKitLibrary.xcframework/ios-arm64_i386_x86_64-simulator/libAppboyKitLibrary.a' to '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/Build/Products/Debug-iphonesimulator/MyProject.framework/Frameworks/libAppboyKitLibrary.a'
2) Target 'MyProject' (project 'MyProject') has copy command from '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/SourcePackages/artifacts/Appboy_iOS_SDK/AppboyKitLibrary.xcframework/ios-arm64_i386_x86_64-simulator/libAppboyKitLibrary.a' to '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/Build/Products/Debug-iphonesimulator/MyProject.framework/Frameworks/libAppboyKitLibrary.a'
```

## Steps to reproduce

Add Appboy as dependency through **Swift Package Manager** pointing to the commit Id _75647ca863868b46fe4015124456381b58ac491a_
<img width="798" alt="appboy" src="https://user-images.githubusercontent.com/37772020/97948162-b18c9a80-1db5-11eb-8faf-47b1c21af3b2.png">
## Code Snippet

None

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No

## Project that demonstrates the issue

It's internally hosted

**Comment by lowip** [comment]
Hi @bharathnagarajrao,

Could you verify that you included only either `AppboyKit` or `AppboyUI`. `AppboyUI` already includes `AppboyKit` and so it is not necessary to include both in your project.

**Comment by bharathnagarajrao** [comment]
Hi @lowip,
I followed the instructions from [Braze documentation ](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager/#step-1-adding-the-dependency-to-your-project)
```
Make sure you select either AppboyKit or AppboyUI. Including both packages can lead to undesired behavior.
```
When it prompted with `AppboyKit`(static library) & `AppboyUI`, I chose `AppboyKit`

**Comment by hokstuff** [comment]
Hi @bharathnagarajrao,

It appears that the duplicate tasks are the same exact commands from the the same paths. Can you delete the local `Appboy-iOS-SDK` files thru SPM and try again? If that doesn't work, try to clean build folder / delete DerivedData and see if that helps.

If you are still having issues, please email support@braze.com to get further assistance - thank you!

**Comment by hokstuff** [comment]
Just checking if you are still experiencing issues @bharathnagarajrao?

**Comment by bharathnagarajrao** [comment]
@hokstuff Thanks for following up. 
I haven't had chance to get back on this. I switched to carthage for our integration.
We can close this issue for now.

**Comment by hokstuff** [comment]
Thanks, I'll close this out - feel free to reopen if you run into the same issue in the future.

**Comment by bharathnagarajrao** [comment]
Hi @hokstuff, 
I tried to migrate our Braze integration from carthage to SPM using the version [4.3.0](https://github.com/braze-inc/braze-ios-sdk/releases/tag/4.3.0) and ended up seeing the same error which was mentioned earlier. ie,

```
Unexpected duplicate tasks:
1) Target 'MyProject' (project 'MyProject') has copy command from '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/SourcePackages/artifacts/Appboy_iOS_SDK/AppboyKitLibrary.xcframework/ios-arm64_i386_x86_64-simulator/libAppboyKitLibrary.a' to '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/Build/Products/Debug-iphonesimulator/MyProject.framework/Frameworks/libAppboyKitLibrary.a'
2) Target 'MyProject' (project 'MyProject') has copy command from '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/SourcePackages/artifacts/Appboy_iOS_SDK/AppboyKitLibrary.xcframework/ios-arm64_i386_x86_64-simulator/libAppboyKitLibrary.a' to '/Users/abcd/Library/Developer/Xcode/DerivedData/MyProject-gabocuueqjhikmfwifcdmskcjmzw/Build/Products/Debug-iphonesimulator/MyProject.framework/Frameworks/libAppboyKitLibrary.a'
```
Appreciate any help on this.

**Comment by lowip** [comment]
Hi @bharathnagarajrao,

Could you send us the full Xcode build logs at support@braze.com.

You can retrieve the logs by selecting the export button in Xcode:
![jrYXi](https://user-images.githubusercontent.com/503337/132365097-4bb88556-0d8a-4fdf-8feb-867f0e54ff81.png)

Thanks,
