### ISSUE TITLE
Unable to build app in Xcode 12.3 

### ISSUE THREAD

**Issue by laurenmarshallVS** [Appboy/appboy-ios-sdk#268]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |ios
 Platform Version        |Xcode 12.3
 SDK Version              |3.31.1
 Integration Method   |Rome
 Xcode Version           |Xcode 12.3
 Repro rate                 |100%
 
## What did you do?

I upgraded our project from Xcode 12.2 to 12.3 and I got the following error:

`
Building for iOS Simulator, but the linked and embedded framework 'Appboy_iOS_SDK.framework' was built for iOS + iOS Simulator.
`
This is preventing our project from building.

## What did you expect to happen?

The SDK to compile without any errors.

## What happened instead?

This is preventing our project from building.

## Steps to reproduce

- Add `pod 'Appboy-iOS-SDK'` to the Podfile.
- Run `pod install`
- Try to build the project

**Comment by laurenmarshallVS** [comment]
See Apple's response [here](https://developer.apple.com/forums/thread/669411?answerId=652663022#652663022)

**Comment by hokstuff** [comment]
Hi @laurenmarshallVS,

We have not yet been able to reproduce this on our end using Xcode 12.3. However, can you try a temporary workaround and set `Validate Workspace = YES` in the Build Settings? If that doesn't work, we do have a [4.0.0-beta1 release](https://github.com/Appboy/appboy-ios-sdk/releases/tag/4.0.0-beta1) that is distributed using XCFrameworks which should help with the issue.

Thanks!
