### ISSUE TITLE
Received 'BadDeviceToken' sending error to b047c809e82c709587ac346cdca4e9ae251fcd732426d6efdf31a407cbffe89a

### ISSUE THREAD

**Issue by haitrieu223** [Appboy/appboy-ios-sdk#271]
Hi there,
I have configured push notification as per the [documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/) but when I test push notification with the api:
{
    "external_user_ids":["testUser2"],
    "messages":{
    "apple_push":{
        "alert":"Test push"
        }
    }
}

result: 
{
    "dispatch_id": "77e0a95312fd7156640e2c6261489303",
    "message": "success"
}

but I check on the Message Activity Log page it says **Received 'BadDeviceToken' sending error to b047c809e82c709587ac346cdca4e9ae251fcd732426d6efdf31a407cbffe89a**

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  ios
 Platform Version        |  13.0
 SDK Version             |  3.31.1
 Integration Method      | cocoapods
 Xcode Version           | Xcode 12.2
 Repro rate              | all the time (100%) 

Please support me, it took me quite a long time with this problem. Hope to receive help from you

**Comment by lowip** [comment]
Hi @haitrieu223 ,

It sounds like your question is a better fit for our Support team. They will be able to work with your specific situation to answer any questions you have - please reach out to them at support@braze.com so they can assist you.

Thanks!
