### ISSUE TITLE
Breaking changes on patch 3.31.1

### ISSUE THREAD

**Issue by vitormf** [Appboy/appboy-ios-sdk#274]
Hello, when upgrading from version 3.31.0 to 3.31.1 a breaking change was made:
`ABKUIUtils.getSDWebImageProxyClass()` no longer exists and it causes compilation issues.

That was not supposed to be made on a [patch version](https://semver.org/).

**Comment by lowip** [comment]
Hi @vitormf, thanks for contacting us about this issue.

We apologize for that breaking change in a patch version. We are in the process of making our image loading system more flexible and this public api change slipped through our review process.

In the meantime, you can still import the proxy if needed:

```objc
#import "ABKSDWebImageProxy.h"
```

**Comment by lowip** [comment]
We updated the changelog and the release. Closing this issue.
