### ISSUE TITLE
Provisional pushes/Critical alerts

### ISSUE THREAD

**Issue by noorulain17** [Appboy/appboy-ios-sdk#277]
Does Braze support Provisional pushes and/or critical alerts?

**Comment by hokstuff** [comment]
Hi @noorulain17,

Yes, Braze supports both provisional pushes and critical alerts. Please reference [our public documentation ](https://www.braze.com/docs/user_guide/message_building_by_channel/push/ios/notification_options/#provisional-push-authentication--quiet-notifications) for more information about those features.

Thanks!
