### ISSUE TITLE
IAM Modal Background Does Not Dismiss

### ISSUE THREAD

**Issue by lustig-bakkt** [Appboy/appboy-ios-sdk#278]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

Sending an IAM Modal message is functional, but does not dismiss properly. If relevant, we have attached a deeplink to Button 1. FWIW this is a `react-native` integration and we are using version `1.26.0` with iOS SDK version `3.31.2`.

GIF:

![2523 fix ios deeplinking iam working, braze modal broken](https://user-images.githubusercontent.com/73849817/107827872-a2729c80-6d55-11eb-8289-ccb8f6212189.gif)

### Relevant Information

_Pods_
```
  - Appboy-iOS-SDK (3.31.2):
    - Appboy-iOS-SDK/UI (= 3.31.2)
  - Appboy-iOS-SDK/ContentCards (3.31.2):
    - Appboy-iOS-SDK/Core
    - SDWebImage (< 6, >= 5.8.2)
  - Appboy-iOS-SDK/Core (3.31.2)
  - Appboy-iOS-SDK/InAppMessage (3.31.2):
    - Appboy-iOS-SDK/Core
    - SDWebImage (< 6, >= 5.8.2)
  - Appboy-iOS-SDK/NewsFeed (3.31.2):
    - Appboy-iOS-SDK/Core
    - SDWebImage (< 6, >= 5.8.2)
  - Appboy-iOS-SDK/UI (3.31.2):
    - Appboy-iOS-SDK/ContentCards
    - Appboy-iOS-SDK/Core
    - Appboy-iOS-SDK/InAppMessage
    - Appboy-iOS-SDK/NewsFeed
```
_NPM library_

` "react-native-appboy-sdk": "1.26.0"`

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  react-native / ios
 Platform Version        |  14
 SDK Version             | 3.31.2
 Integration Method      |  cocoapods
 Repro rate              | all the time (100%) 
 
## What did you do?

Sent IAM Modal with deep link and attempted to dismiss modal through accessing deep link (deep link functions) but the modal background is not dismissed.

## What did you expect to happen?

The modal background to dismiss.

## What happened instead?

The modal background did not dismiss.

**Comment by chshapiro** [comment]
Hey @lustig-bakkt,

Are you doing any customization for your in-app messages?

**Comment by lustig-bakkt** [comment]
> Hey @lustig-bakkt,
> 
> 
> 
> Are you doing any customization for your in-app messages?

I have added a deeplink to one of the buttons and added a key value pair. 

One interesting thing to note is that this is a React Native application and when run through the command line is when I saw this bug. If run through Xcode, it did not happen.

**Comment by chshapiro** [comment]
Hey @lustig-bakkt,

Are you still experiencing this issue?

**Comment by lustig-bakkt** [comment]
I think the issue is resolved but I forgot what we did to do so

**Comment by chshapiro** [comment]
👍 I'm going to close out the issue. Feel free to open a new one if you run into anything else.
