### ISSUE TITLE
Latest 3.33.0 version cannot resolve AppboyPushStory when using SwiftPM

### ISSUE THREAD

**Issue by Nonnus** [Appboy/appboy-ios-sdk#280]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.4
 SDK Version             | 3.33.0
 Integration Method      | SwiftPM
 Xcode Version           | Xcode 12.4
 Repro rate              | all the time (100%)
 
## What did you do?

Integrate Braze through SwiftPM

## What did you expect to happen?

Integration should be successful (as it is / was on version 3.32.0)

## What happened instead?

SwiftPM could not resolve AppboyPushStory:
<img width="729" alt="Screenshot 2021-02-22 at 02 42 26" src="https://user-images.githubusercontent.com/54864/108647155-3b24bd00-74b8-11eb-8bdb-e349e76fb6a2.png">

## Steps to reproduce 

1. create new project
2. add SwiftPM dependency, point to https://github.com/Appboy/appboy-ios-sdk
<img width="729" alt="Screenshot 2021-02-22 at 02 52 58" src="https://user-images.githubusercontent.com/54864/108647583-53490c00-74b9-11eb-949f-66f020367741.png">

4. integration fails right away if resolving version 3.33.0 (if I point to exact 3.32.0 version dependency resolves fine)
<img width="729" alt="Screenshot 2021-02-22 at 02 42 26" src="https://user-images.githubusercontent.com/54864/108647155-3b24bd00-74b8-11eb-8bdb-e349e76fb6a2.png">

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

no

## Project that demonstrates the issue

If I point to version 3.33.0 cannot integrate braze into sample project, so I would only be able to send you an empty project
The only way I can send a sample project is to point braze dependency to version 3.32.0 but my report is about latest 3.33.0 version...

**Comment by lowip** [comment]
Hi @Nonnus 

Thank you for this report, we have a release planned tomorrow that fixes this issue. 
I will make sure to ping you on this thread as soon as the new version is available.

**Comment by Nonnus** [comment]
wow, that was an impressive fast response! and with awesome news!
thanks a lot @lowip

**Comment by lowip** [comment]
@Nonnus 

We have released [3.33.1](https://github.com/Appboy/appboy-ios-sdk/releases/tag/3.33.1) which fixes that issue. Thank you for the report!

**Comment by Nonnus** [comment]
thanks a lot for the update @lowip
