### ISSUE TITLE
Unable to integrate Braze on a Mac Catalyst app via SPM

### ISSUE THREAD

**Issue by isisnaomi** [Appboy/appboy-ios-sdk#282]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. macOS
 Platform Version        | e.g. 11.0.1 
 SDK Version             | e.g. 3.34.0
 Integration Method      | e.g. SPM
 Xcode Version           | e.g. Xcode 12.2
 Repro rate              | e.g. all the time (100%)
 
## What did you do?

Integrate Braze through SMP with Mac Catalyst.

## What did you expect to happen?

Braze SDK is integrated properly 

## What happened instead?

Got a code signing error when trying to run the app on Mac. (The SDK is working correctly on iOS)
```
/Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-maccatalyst/App.app: code object is not signed at all
In subcomponent: /Users/.../Library/Developer/Xcode/DerivedData/.../Build/Products/Debug-maccatalyst/App.app/Contents/Frameworks/libAppboyKitLibrary.a
Command CodeSign failed with a nonzero exit code
```

## Steps to reproduce

- Followed all steps on [Swift Package Manager Integration Guidelines](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/swift_package_manager/#step-2-configuring-your-project)
- Run on Mac

**Comment by hokstuff** [comment]
Hi @isisnaomi,

We have not been able to repro this error on our end, so I would double check a few things.

- If you delete your `DerivedData` folder and select `Update to Package Latest Versions` in Xcode, do you still see the error? 
- Have you verified that your Apple Certificate is the correct one for your app? If your certificate is under one of the `iOS` options (see image below), it would not be able to run on Mac Catalyst. If you are having issues with this portion, please reference [the Apple developer docs](https://developer.apple.com/tutorials/mac-catalyst/turning-on-mac-catalyst) for more information on how to set up Mac Catalyst in your app.
<img width="504" alt="Screen Shot 2021-03-08 at 6 51 46 PM" src="https://user-images.githubusercontent.com/4797040/110397590-1bf16800-8040-11eb-87bb-8d29ea73627e.png">

**Comment by hokstuff** [comment]
@isisnaomi Thanks for the additional info! We're now able to see the same issue you were experiencing. We will investigate further for a long-term solution or recommendation, but for now the `--deep` flag should be sufficient to allow you to build. When we have more details, we'll update this thread 👍

**Comment by smawpaw** [comment]
Thanks @hokstuff 

The deep flag does allow us to build, and continue our remaining integration tasks, but we do not want to _ship_ with it in place. Looking forward to a proper fix here 🙏

**Comment by hokstuff** [comment]
Hi @isisnaomi @smawpaw,

Sorry for the delay on this thread! After investigation, it appears that the updates in Xcode 12.5 beta 3 ([release notes here](https://developer.apple.com/documentation/xcode-release-notes/xcode-12_5-beta-release-notes)) have fixed the signing errors for Mac Catalyst when importing through SPM. I was able to build and run on my Mac without the `--deep` flag using the latest version `4.0.1`. Can you try the Xcode beta and let me know if it solves the issue on your end?

Thank you!

**Comment by hokstuff** [comment]
Hi @isisnaomi @smawpaw,

[Xcode 12.5 has been released today](https://developer.apple.com/news/releases/), and it looks to have fixed the issue when running on Mac Catalyst with our SDK integrated via SPM. Feel free to reopen if you are still experiencing problems - thank you!
