### ISSUE TITLE
Warning:

### ISSUE THREAD

**Issue by jesusmateos1234** [Appboy/appboy-ios-sdk#286]
* [X ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | e.g. 12.1
 SDK Version             | 4.0.0
 Integration Method      | cocoapods
 Xcode Version           | e.g. Xcode 12.4
 Repro rate              |  100% 
 
Warning in iOS SDK

Pods/Appboy-iOS-SDK/AppboyUI/ABKInAppMessage/Resources/ABKInAppMessageSlideupViewController.xib:ag0-Xc-EWA: warning: Automatically Adjusts Font requires using a Dynamic Type text style [9]

**Comment by LeffelMania** [comment]
Also seeing this after upgrading from 3.29.0 to 4.0.0 today.

**Comment by chshapiro** [comment]
Hey @jesusmateos1234 and @LeffelMania,

Thank you for reporting! Our next release will include a change that will remove this warning.

**Comment by chshapiro** [comment]
Hey all,

We just released version 4.0.1 of the SDK which removes these warnings.
