### ISSUE TITLE
Making concurrent request to Braze contentCard make my UI stuck for a while till the response comes

### ISSUE THREAD

**Issue by abhi2412shek** [Appboy/appboy-ios-sdk#288]
* [ ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios 
 Platform Version        | e.g. 14
 SDK Version             | e.g. 4.0.0
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 12.4
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once
 
## Steps to reproduce
I have a view which displays featured ContentCards along with buttons of different categories.
The moment I launch the view and immediately click the category the UI sticks unless the featured response appears.

**Comment by chshapiro** [comment]
Hey @abhi2412shek,

Are you doing full customization for content cards? If you are, please provide that code - you can send it to support@braze.com.
Additionally, please let us know how you're integrating and what version of the SDK you're using.

**Comment by hokstuff** [comment]
Closing out this issue due to inactivity. Please contact support@braze.com with more information if you are still experiencing this issue. Thanks!
