### ISSUE TITLE
Bug: SDWebImage is not accessible through the xcframework

### ISSUE THREAD

**Issue by jesusmateos1234** [Appboy/appboy-ios-sdk#291]
SDWebImage dependency is not accessible through xcframework.

Please check this.

Thanks for all

**Comment by Bucimis** [comment]
Hi @jesusmateos1234,

SDWebImage is not bundled together with our xcframeworks. We recommend importing it as a dependency through Swift Package Manager or Cocoapods.

For completeness, we do bundle SDWebImage with our framework integration option, which may be an option for you (see Appboy_iOS_SDK.framework.zip
)
