### ISSUE TITLE
BUG: XCFramework

### ISSUE THREAD

**Issue by jesusmateos1234** [Appboy/appboy-ios-sdk#292]
using 4.0.2 precompiled framework "https://github.com/Appboy/appboy-ios-sdk/releases/download/4.0.2/AppboyKitLibrary.xcframework.zip" in build time i get this error:

Undefined symbols for architecture x86_64:
"_OBJC_CLASS_$_ABKModalWebViewController", referenced from:
      objc-class-ref in libAppboyKitLibrary.a(ABKURLUtilities.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 

Please check this

**Comment by Bucimis** [comment]
Hi @jesusmateos1234,

Using XCFrameworks in a manual integration is not supported right now. For manual integration, download `Appboy_iOS_SDK.zip`, which uses static libraries.

If possible, we recommend using our Swift Package Manager or Cocoapods integrations, which do use XCFrameworks.

**Comment by jesusmateos1234** [comment]
Hi @Bucimis could you include manual integration from precompiled assets like other repositories (FaceBook for ex)?
Appboy_iOS_SDK.zip doesn't work because depends on private search path sdwebimage installed with cocoapods.

**Comment by Bucimis** [comment]
@jesusmateos1234 Thanks for the feedback, we're taking a look into overhauling our manual+SDWebImage integration. In the meantime, our framework option (See `Appboy_iOS_SDK.framework.zip` in https://github.com/Appboy/appboy-ios-sdk/releases/tag/4.0.2) may work for you - you can simply add the Appboy and SDWebImage frameworks directly into your Xcode project as embedded frameworks. Note that our frameworks don't contain m1 arm64 slices.

**Comment by jesusmateos1234** [comment]
@Bucimis How much you believe that it could be done?

Thanks for all

**Comment by Bucimis** [comment]
@jesusmateos1234 I'm confident the embedded framework approach works

**Comment by hokstuff** [comment]
Are you still experiencing this issue?

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. If the workaround described above doesn't work for you, feel free to contact us through the Support channels with more information about your integration steps. Thank you!
