### ISSUE TITLE
ABKContentCard.h logContentCardImpression runs on main thread

### ISSUE THREAD

**Issue by bstillitano** [Appboy/appboy-ios-sdk#294]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report
When using a custom view to render content cards, and subsequently using the `card.logContentCardImpression()` function, the app freezes up on the main thread. 

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           iOS
 Platform Version        14.5
 SDK Version               4.0.2
 Integration Method    Cocoapods
 Xcode Version            Xcode 12.5
 Computer Processor  Intel Based
 Repro rate                   100% of the time
 
## What did you do?

```
//Get Cards for Slot
        let brazeCards: [ABKContentCard] = Appboy.sharedInstance()?.contentCards.filter({ (card) -> Bool in
            return card.extras?["slot"] as? String == slot.rawValue
        }) ?? []
        brazeCards.forEach { (card) in
                card.logContentCardImpression()
        }
```

## What did you expect to happen?

I expect that logging should not block the main thread of my app.

## What happened instead?

Logging blocked the main thread of my app

## Steps to reproduce

See code above.

## Code Snippet

See code above

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

N/A

**Comment by hokstuff** [comment]
Hi @bstillitano,

Can you contact support@braze.com about this issue and include these details around your integration:
- The code in your custom view file that renders the content cards, including how it was initialized and presented
- The method(s) that contain the code snippet you provided

Thanks!

**Comment by hokstuff** [comment]
Closing out this thread since it is about a specific custom integration, and the most streamlined way to debug this issue is via the Support channels. Feel free to comment here if there are further concerns or contact our Support team - thanks!
