### ISSUE TITLE
Interacting with IAM causes app to crash

### ISSUE THREAD

**Issue by phatlaunchdeck** [Appboy/appboy-ios-sdk#295]
* [X] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.5
 SDK Version             | 3.33.1
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 12.1
 Computer Processor      | Intel-based
 Repro rate              | All the time (100%)
 
## What did you do?

Test a campaign and got IAM sent to device

## What did you expect to happen?

Tapping on the IAM should just simply close it

## What happened instead?

The app crashed

## Steps to reproduce

For IAM, I believe I did not need to do anything since on the React Native docs, they say everything is already in place.

## Code Snippet

<img width="1067" alt="Screen Shot 2021-05-11 at 22 43 40" src="https://user-images.githubusercontent.com/37071140/117846179-6515a080-b2ab-11eb-991a-6aba5537efdb.png">

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No

**Comment by phatlaunchdeck** [comment]
Sorry I accidentally hit submit issue without finishing writing yet so I closed it but updated the post now.

**Comment by chshapiro** [comment]
Hey @phatlaunchdeck,

Unfortunately we haven't been able to repro this issue. Are you doing any customization for your in-app messages? Is this crash happening every time you display an in-app message or only sporadically?

**Comment by phatlaunchdeck** [comment]
I'm kinda positive that I did not do any customization to the IAM since the React Native doc indicates that the IAM will show up automatically. Oh one thing I forgot to mention that you need to test it with a real device to get the crash, it seems to work when I'm on Simulators.

**Comment by chshapiro** [comment]
Hey @phatlaunchdeck,

Can you also turn on [verbose logging](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/#braze-log-level) and send us the logs from when you open the app until the crash occurs? If you're not comfortable posting them here, you can email them to support@braze.com.

**Comment by phatlaunchdeck** [comment]
Okay so I will turn that on, copy the stack trace as I did before and share with you via the email? Do I need to indicate any ticket number when I do that?

**Comment by chshapiro** [comment]
You can reference this issue. And please include the device logs as well as the stack trace in the email. Thanks!

**Comment by phatlaunchdeck** [comment]
Hey @chshapiro sorry to ask this, but I'm seeing a lot of logs for my device and not sure which one should I send to you guys? There are a few for today (May 13th) but as I see none is related to our app (Truckster) or saying Braze/Appboy or something.

<img width="1466" alt="Screen Shot 2021-05-13 at 21 31 12" src="https://user-images.githubusercontent.com/37071140/118140436-8e146d80-b432-11eb-89ad-cc00338a322d.png">

**Comment by phatlaunchdeck** [comment]
But in the meantime, here's the latest stack trace with verbose mode is on: https://codeshare.io/aVJvJQ

**Comment by chshapiro** [comment]
Hey @phatlaunchdeck,

You can use these [directions](https://docs.buddybuild.com/troubleshooting/getting_device_logs_from_xcode.html) to get the logs follwing the steps in the `Using Xcode` section?

**Comment by phatlaunchdeck** [comment]
I actually followed that page to get a device log, but seems like it was for an older version of XCode, there is no more "small arrow at the bottom left corner" anymore on my XCode 12. However, I was able to retrieve the logs now, took a few hours for it to show up on my end.

**Comment by chshapiro** [comment]
Hey @phatlaunchdeck,

Our team has potentially identified the issue. Do you have any UI element (first or third party) that could compete with Braze's in-app message window? We force our In-app message window to be _key and visible_ when presented, it's possible that another `UIWindow` in your code is doing the same thing, leading to the crash.

**Comment by phatlaunchdeck** [comment]
Hey @chshapiro, I have tried really hard to determine which library does that but all I can find in the whole node_modules is RCTLogBox and Alert, but they are core modules of React Native so those couldn't cause it right?

<img width="836" alt="Screen Shot 2021-05-14 at 03 10 08" src="https://user-images.githubusercontent.com/37071140/118181425-f3cc1e00-b461-11eb-9791-3f0057b17f63.png">

**Comment by phatlaunchdeck** [comment]
@chshapiro if it helps, I've just discovered that I don't interact at all with the IAM and let it closes itself after x amount of seconds, then it will not cause any crash.

**Comment by chshapiro** [comment]
Hey @phatlaunchdeck,

We're still unable to repro in our React Native sample app. Are you trying to show an alert at the same time that the in-app message is displayed?

**Comment by phatlaunchdeck** [comment]
@chshapiro I'm 100% sure that I do not do such. Last night when you asked me to look into whatever library doing "makeKeyAndVisible" I tried to remove everything from the screen that is suspicious from Modal to Toast (which is just a React Native View btw), but as soon as the Braze's IAM came in, it just crashed the app.

I even tried to bring out the IAM as soon as the app opens to avoid any possible libraries being loaded up and it still crashed the app.

**Comment by phatlaunchdeck** [comment]
Hey @chshapiro, this matter has become very urgent on our end as we paid Braze primarily to work with the IAMs and they're not working for us. Is there any chance that we can hop onto a real-time session so you can see and/or debug things directly into our source code? We are willing to pay for your time.

**Comment by Bucimis** [comment]
@phatlaunchdeck we'll be in touch with your team to schedule a call

**Comment by lowip** [comment]
Fixed in [Appboy-iOS-SDK 4.2.0](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#changed).
