### ISSUE TITLE
Push notification events not being triggered through Segment integration

### ISSUE THREAD

**Issue by kevinfarst-earnin** [Appboy/appboy-ios-sdk#296]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

We integrate the `Appboy-iOS-SDK` with `Segment` using the [Segment-Appboy](https://github.com/Appboy/appboy-segment-ios) Cocoapod, currently on version 3.5.0. We recently upgraded the SDK from version 3.29.1 to 4.0.2 without any other changes to either the `Segment` or `Segment-Appboy` Cocoapods.  After the upgrade, the `Push Notification Tapped` event triggered through the `Segment` SDK began to plummet in app versions containing the 4.0.2 SDK version. After rolling back to version 3.29.1 of the SDK, the `Push Notification Tapped` events recovered without any other changes to our application's configuration or modification of any other SDKs integrated within our app.

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.4
 SDK Version             | 4.0.2
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 12.5
 Computer Processor      | Intel-based
 Repro rate              |  All the time (100%)
 
## What did you do?

Upgraded the SDK from version 3.29.1 to 4.0.2.

## What did you expect to happen?

Segment's `Push Notification Tapped` event would continue to be logged as in previous versions.

## What happened instead?

The `Push Notification Tapped` event began to plummet in app versions containing the SDK update.

## Steps to reproduce

Example:
- Add `pod 'Segment-Appboy'` version 3.5.0 to the Podspec file.
- Run `pod update Appboy-iOS-SDK` update the installed SDK version if latest version was not installed.

- Add the following configuration to the `application:didFinishLaunchingWithOptions:` method in `AppDelegate.m`.
```
NSString *const SEGMENT_WRITE_KEY = @" ... ";
SEGAnalyticsConfiguration *config = [SEGAnalyticsConfiguration configurationWithWriteKey:SEGMENT_WRITE_KEY];

[config use:[SEGAppboyIntegrationFactory instance]];

[SEGAnalytics setupWithConfiguration:config];
```
- Run the app.
- Send a push notification to the device with a Braze campaign.
- Observe the `Push Notification Tapped` event triggered through Segment to the Braze project.

**Comment by chshapiro** [comment]
Hey @kevinfarst-earnin,

Can you try updating your `Segment-Appboy` version to the most current version?
Can you also turn on [verbose logging](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/#braze-log-level) and send us the logs of an instance where you expect to see the event triggered and it's not triggering?

**Comment by hokstuff** [comment]
Hi @kevinfarst-earnin, are you still experiencing this issue?

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. Feel free to reopen or contact our Support channels if you still have concerns. Thanks!
