### ISSUE TITLE
Crash with iOS 9

### ISSUE THREAD

**Issue by rakesthedon** [Appboy/appboy-ios-sdk#299]
Hi!

We update to version 4.1.0 and we encounter the following crash on iOS 9:
```-[UIButtonLabel setAdjustsFontForContentSizeCategory:]: unrecognized selector sent to instance 0x188c1930```

all you have to do to reproduce the crash is to send an in app message test of type slideup modal or fullscreen.

Thanks!

**Comment by hokstuff** [comment]
Hi @rakesthedon,

Thanks for reporting this issue! We have been able to repro the crash and are preparing a fix to address it.

Best,
Daniel

**Comment by rakesthedon** [comment]
Thanks for the feedback @hokstuff it's really appreciated!

**Comment by hokstuff** [comment]
Hi @rakesthedon,

We have released [SDK version 4.2.0](https://github.com/Appboy/appboy-ios-sdk/releases/tag/4.2.0) which fixes this crash.

Thanks for bringing it to our attention!

**Comment by Bucimis** [comment]
Hi @rakesthedon, just a heads up that we have a crashing iOS Content Cards regression in 4.2.0. If you are not using our out-of-the-box Content Cards UI, you won't be affected, but otherwise please stand by for a patch release coming in the next few days.

**Comment by rakesthedon** [comment]
does this crash occurs only ios 9?

**Comment by Bucimis** [comment]
@rakesthedon repro'd on iOS 14.5, so not limited to iOS 9

**Comment by rakesthedon** [comment]
@Bucimis can we have more details? We only use banner card view in our in app debug screen. As I understand this only occur in the provided view controller right?

**Comment by Bucimis** [comment]
@rakesthedon the crash occurs in the provided view controller when using a classic card with an image.

**Comment by marcinkornek** [comment]
why is this issue closed if it's still crashing app with "classic" content card?

**Comment by hokstuff** [comment]
Hi @marcinkornek,

The original iOS 9 issue and the regression noted above in `4.2.0` were two separate issues. Both of them have been fixed in [version 4.3.0](https://github.com/Appboy/appboy-ios-sdk/releases/tag/4.3.0). Sorry for the confusion!

Best,
Daniel
