### ISSUE TITLE
Missing > 4.0.0 versions in Cocoapods Spec repo

### ISSUE THREAD

**Issue by omarzl** [Appboy/appboy-ios-sdk#304]
Hello, versions over 4.0.0 for example 4.1.0, 4.2.0, 4.3.0 are missing an update in the [podspec](https://github.com/Appboy/appboy-ios-sdk/blob/master/Appboy-Push-Story.podspec) and are not being pushed to Cocoapods Spec repo -> https://github.com/CocoaPods/Specs/tree/master/Specs/b/e/9/Appboy-Push-Story

Therefore we can't use latest versions:
```
[!] CocoaPods could not find compatible versions for pod "Appboy-Push-Story":
  In Podfile:
    Appboy-Push-Story (= 4.3.0)
```

**Comment by lowip** [comment]
Hi @omarzl,

The version of Appboy-Push-Story currently available on CocoaPods (4.0.0) is the latest version. This differs slightly from our Swift Package Manager versioning (4.3.0) as SPM relies on tagged version. Rest assured that Appboy-Push-Story 4.0.0 is identical to the 4.3.0 SPM equivalent. We will make sure to update the CocoaPods version if any change is made to that framework.

Feel free to re-open this issue if this doesn't answer your question.

Thanks,
