### ISSUE TITLE
SIGSEGV -[ABKEventLog copyWithZone:] ABKEventLog.m, line 39

### ISSUE THREAD

**Issue by apan06** [Appboy/appboy-ios-sdk#307]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report
Hi, I'm just passing to you some info from our AppCenter. It's a very tiny crasher, but maybe a useful stack for you.  
Maybe related: https://github.com/Appboy/appboy-ios-sdk/issues/173
As it's from our AppCenter I don't have any repro steps 😞 

Cheers!

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 14.6
 SDK Version             | 4.3.0
 Integration Method      | SPM
 Xcode Version           | 12.5
 Repro rate              | 0
 Crash rate | very low, 4 users at prod 

## Stacktrace
![Screenshot 2021-07-13 at 08 58 53](https://user-images.githubusercontent.com/1150803/125405983-9fd5ab00-e3b8-11eb-9222-24cd67dbbf00.png)

**Comment by lowip** [comment]
Hi @apan06,

Thank you for this report, we're tracking that issue internally and will update here once we have released a fix.
I'm closing this issue for now, but feel free to reopen or comment here if you obtain more details or steps to reproduce.

**Comment by samsiner** [comment]
@lowip Is there any update on when this issue fix will be on the roadmap? We're seeing it in production too - not a large amount of crashes - so I'm curious. Thanks!
