### ISSUE TITLE
Bitcode enabled library is available?

### ISSUE THREAD

**Issue by AnilVarghese** [Appboy/appboy-ios-sdk#31]
Is the current version Appboy sdk supports bitcode, seems like it doesnt. Getting error when i enabled bitcode for my project in Xcode 7.

**Comment by briancaw** [comment]
Hi @AnilVarghese 

The current Appboy iOS SDK does support bitcode.  Can you let us know:

1)  How are you integrating Appboy?  i.e. via CocoaPods or manual integration?
2)  What is the error you are seeing? 
3)  What version of Appboy are you using?  Our release version 2.15.0 supports bitcode.

Thanks,
Brian

**Comment by AnilVarghese** [comment]
Thanks @briancaw . I was using an old version. Updated to 2.15.0 and error gone.
