### ISSUE TITLE
Xcode 13 BETA 5: Can't download the framework

### ISSUE THREAD

**Issue by marcusziade** [Appboy/appboy-ios-sdk#311]
* [x ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           macOS
 Platform Version        11.5.2
 SDK Version             4.3.1
 Integration Method      SPM
 Xcode Version           Xcode 13 Beta 5
 Computer Processor      Apple M1
 Repro rate             100%
 
## What did you do?

Trying to download the framework inside Xcode

## What did you expect to happen?

For the framework to install itself with SPM

## What happened instead?

It didn't download. I got the error `Invalid Resource 'headers/AppboyKitLibrary/ZipArchive_LICENSE.txt': File not found`

## Steps to reproduce

1. Quit Xcode
2. Delete Xcode derived data
3. Open the project in Xcode. 
4. Fresh downloads start

**Comment by lowip** [comment]
Hi @marcusziade,

Thanks for this report, this will be fixed in the next release. We will update here once the fix is available.

**Comment by marcusziade** [comment]
@lowip Any ETA?

**Comment by hokstuff** [comment]
Hi @marcusziade,

We have released this fix as a part of our [4.3.3 version](https://github.com/Appboy/appboy-ios-sdk/releases/tag/4.3.3). Thanks!
