### ISSUE TITLE
Empty feed view is not shown after deleting all content cards

### ISSUE THREAD

**Issue by peruginni** [Appboy/appboy-ios-sdk#312]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           |  iOS
 Platform Version        | 14.0
 
## What did you do?

- Send some content cards to your user
- Open `ABKContentCardsTableViewController`
- Expect to see several content cards
- Dismiss each of cards

## What did you expect to happen?

I expect message "We have no updates. Please check again later." to be shown.

## What happened instead?

No empty message is shown, because the `emptyFeedView` is not visible.

## Possible fix

- Seems that in `- (void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath {` 
- if `self.cards.count == 0`
- then should be called  `updateAndDisplayCardsFromCache` so that empty view is shown

**Comment by lowip** [comment]
Hi @peruginni,

Thank you for reporting this issue and for the proposed solution. We will update here once the fix released.

Best,

**Comment by hokstuff** [comment]
Hi @peruginni,

We have released a fix for this in our [4.3.3 version](https://github.com/Appboy/appboy-ios-sdk/releases/tag/4.3.3). Thanks for reporting!

**Comment by peruginni** [comment]
Thank you for quick fix!
