### ISSUE TITLE
InAppMessages KeyWindow 

### ISSUE THREAD

**Issue by SgSarm** [Appboy/appboy-ios-sdk#314]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.
<br class="Apple-interchange-newline">

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | > 10.3+
 SDK Version             | 4.33.0
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 13.0
 Computer Processor      | Intel-based 
 Repro rate              | All the time (100%)
 
## What did you do?

Implement BRAZE-SDK following the tutorial and try to open deeplinks from InAppMessages. 

## What did you expect to happen?

If I send an InAppMessage with Button and a Deeplink I would like to get redirected to the page according to the Deeplink.

## What happened instead?

InAppMessage sets rootViewController -> we don't get redirected to the target ViewController.

## Steps to reproduce

In our Deeplink Handling we need the rootViewController. Since before an InAppMessage is displayed, `displayInAppMessageViewWithAnimation` in `ABKInAppMessageWindowController` gets called an the rootViewController is set to   `self.inAppMessageWindow.rootViewController = self;` (Line 304) we don't have that Information anymore because the InAppMessage is the new rootViewController and we're not getting deeplinked. 

Do you have any ideas how we can solve this problem?

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?

No Customizations should related to that. We change Fonts and CornerRadius.

## Project that demonstrates the issue

Dont have one.

Thanks in advance

**Comment by hokstuff** [comment]
Hi @SgSarm,

I'm just checking in about this issue. Since your integration is more particular and involves other Deeplink dependencies, it would be best to email support@braze.com if you run into more issues so we can take a more in-depth look.

Due to inactivity and what appears to be a workaround for your situation, I will close out this issue. Feel free to comment or contact Support if you believe this was done in error - thank you!
