### ISSUE TITLE
Cordova iOS build is failed `/AppboyUI.ContentCards.bundle" not found`

### ISSUE THREAD

**Issue by SeongwoonHong** [Appboy/appboy-ios-sdk#315]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | macOS Catalina 
 Platform Version        | 10.15.7
 SDK Version             | 4.3.2
 Integration Method      | Manually
 Xcode Version           | 12.4 (12D4e)
 Computer Processor      | Intel-based
 Repro rate              | 100%
 
## What did you do?

Integrate Braze SDK with my cordova app

1. `cordova plugin add https://github.com/appboy/appboy-cordova-sdk#master` in my terminal
2. `cordova build ios`
3. didn't work
4. so I tried removing/adding ios again by `cordova platform remove ios`
5.  `cordova platform add ios`
6. `cordova build ios`
7. didn't work

## Code Snippet

package.json

**Comment by hokstuff** [comment]
Hi @SeongwoonHong,

Thanks for filing this issue. I'm just acknowledging here for others following since we have an ongoing thread with your team via the Braze Support channel. We are investigating on our end and will post back here once we reach a resolution.

Best,
Daniel
