### ISSUE TITLE
Release artifacts not include a LICENSE file

### ISSUE THREAD

**Issue by thii** [Appboy/appboy-ios-sdk#317]
Release artifacts aren't including a LICENSE file, so we're having to query GitHub or vendor the LICENSE file for the compliance purpose.

Please include a copy of the LICENSE file (https://github.com/Appboy/appboy-ios-sdk/blob/master/LICENSE) into each release artifact.

**Comment by davidbielik** [comment]
Hi @thii we've filed this internally. Thanks for submitting.

**Comment by lowip** [comment]
Hy @thii,

Just letting you know that our new [Swift SDK](https://github.com/braze-inc/braze-swift-sdk) includes Braze's and other third party licenses in the application.

See:
- [`Braze.license`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/license/)
- [`Braze.acknowledgments`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/acknowledgments)

Unfortunately, SwiftPM does not support distributing resources inside statically linked xcframeworks so these licenses cannot be included in the release artifacts.
