### ISSUE TITLE
XCFramework with Carthage for "Core" integration

### ISSUE THREAD

**Issue by marcelofabri** [Appboy/appboy-ios-sdk#318]
> The Core integration does not support XCFrameworks, and you can use the original .framework files as before.

Any reason for that @hokstuff? That's the integration we've been using and would love to keep using it.

_Originally posted by @marcelofabri in https://github.com/Appboy/appboy-ios-sdk/issues/293#issuecomment-952365598_

**Comment by marcelofabri** [comment]
@hokstuff Any updates here? Braze is our last dependency that doesn't support M1 Macs and we really want to stop using Rosetta.

**Comment by hokstuff** [comment]
Hi @marcelofabri,

Thanks for checking in! Pending any changes, we actually are planning to release Carthage Core XCFramework support in our next release which is planned fairly soon. We will update on this thread once it is ready - thanks for your patience!

**Comment by hokstuff** [comment]
Hi @marcelofabri,

We have released [iOS SDK version 4.4.1](https://github.com/Appboy/appboy-ios-sdk/releases/tag/4.4.1) which contains XCFramework support for the Carthage Core integration as well as the Core XCFramework artifact, which contains the relevant non-UI resources. Let us know if you run into any issues - thank you!

Best,
Daniel
