### ISSUE TITLE
Braze Campaigns received on devices with Notifications turned OFF

### ISSUE THREAD

**Issue by SarannyaSalim** [Appboy/appboy-ios-sdk#319]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS 
 Platform Version        | 14.5
 SDK Version             | 3.31.2
 Integration Method      |  Cocoapods
 Xcode Version           | Xcode 12.5
 Computer Processor      | Intel-based 
 Repro rate              | All the time (100%) 
 
## What did you do?

- Disabled notifications on device settings (iPhone XS)

## What did you expect to happen?

- Braze campaign shouldn't be received

## What happened instead?

- Braze campaigns are received

## Steps to reproduce

- Integrate Braze into your app
- Create a campaign for your users for an app event on your app's Braze dashboard
- Disable notifications for your app in device settings
- Run the app

**Comment by Bucimis** [comment]
@SarannyaSalim hi, which types of campaigns were received with notifications turned off at the device level? iOS enforces these settings and there's no way around them, so we would expect push notifications to never display in that case unless iOS itself had a bug.

However, other types of Braze campaigns, such as in-app messages and Content Cards, are unaffected by push settings (generally speaking) and would show regardless of device push settings.

**Comment by SarannyaSalim** [comment]
Hey @Bucimis Thank you for answering. I was assuming the in-app messages are affected by the push settings. Thank you for clearing this. Great help!
