### ISSUE TITLE
The message is not showing up, when implementing 

### ISSUE THREAD

**Issue by YourDaddy2000** [Appboy/appboy-ios-sdk#320]
* [ ] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 14.5
 SDK Version             | 4.4.0
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 13.1
 Computer Processor      | 2,9 GHz Intel Core i7
 Repro rate              | All the time (100%)
 
## What did you do?
Use slideup code from example: https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/in-app_messaging/in-app_message_delivery/#real-time-in-app-message-creation--display

## What did you expect to happen?
the slideup message with "YOUR_CUSTOM_SLIDEUP_MESSAGE" message appears and disappears after 2.5 secs.

## What happened instead?
The slide up message is not shown

## Steps to reproduce
- Add pod 'Appboy-iOS-SDK' to the Podspec file and install via Cocoapods
- Add Appboy.start(withApiKey: key, in: application, withLaunchOptions: launchOptions) method in 'application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]?) -> Bool' function
- Set setInAppMessageUIDelegate in 'application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]?) -> Bool' function
- Set 'Appboy.sharedInstance()!.inAppMessageController.delegate' in 'application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]?) -> Bool' function
- Add ABKInAppMessageControllerDelegate implementation
- Define 'displayInAppMessageLater' in 'before(inAppMessageDisplayed:)' method
- Add Appboy.sharedInstance()!.inAppMessageController.add(customInAppMessage)
- Call Appboy.sharedInstance()!.inAppMessageController.displayNextInAppMessage()

## Code Snippet

  let customInAppMessage = ABKInAppMessageSlideup.init()
  customInAppMessage.message = "YOUR_CUSTOM_SLIDEUP_MESSAGE"
  customInAppMessage.duration = 2.5
  customInAppMessage.extras = ["key": "value"]
  Appboy.sharedInstance()!.inAppMessageController.add(customInAppMessage)

## Additional Info
the customInAppMessage is showing up only if in ABKInAppMessageControllerDelegate's 'before(inAppMessageDisplayed: ABKInAppMessage)' method the return type is 'displayInAppMessageNow'. the message is never shown with 'displayInAppMessageLater' and calling 'displayNextInAppMessage()' where needed

**Comment by hokstuff** [comment]
Hi @YourDaddy2000,

Thanks for filing this issue. The option `ABKDisplayInAppMessageLater` is designed not to display the in-app message immediately and instead puts it on a stack, [as described here](https://github.com/Appboy/appboy-ios-sdk/blob/fed071000722673754da288cace15c1ff8aca432/AppboyKit/include/ABKInAppMessageControllerDelegate.h#L8). This allows you to control if or when to display the in-app message at a later time. For the purposes of displaying the in-app message immediately (as what you expected to see happen), please return `ABKDisplayInAppMessageNow` in your `before(inAppMessageDisplayed:)`.

If you have any further integration questions, feel free to reach out to support@braze.com if there is a more in-depth investigation needed.

Thank you!

**Comment by YourDaddy2000** [comment]
Hi @hokstuff,

Thanks for your reply.

> `ABKDisplayInAppMessageLater` is designed not to display the in-app message immediately

this is what I am trying to achieve. I need to postpone the appearance of this message until the certain conditions are met. but the problem is that the message does NOT appear when I call `Appboy.sharedInstance()!.inAppMessageController.displayNextInAppMessage()`

Is it the way it is supposed to be?

Thanks.

**Comment by hokstuff** [comment]
Hi @YourDaddy2000,

Can you send over your verbose logs to the Braze Support team (support@braze.com)? That way the team can take a closer look in more depth as to what is happening in your app. There can be a few reasons why the IAM isn't displaying, including if the keyboard is currently presented at the time of display.

Also, note that the call `Appboy.sharedInstance()!.inAppMessageController.add(customInAppMessage)` adds to the in-app message stack and automatically tries to present it immediately after. Calls to `displayNextInAppMessage` will simply attempt to display if there is a message on the stack.
