### ISSUE TITLE
Push Notifications not working on iOS 15 devices (BadDeviceToken) but working on iOS 14 and lower

### ISSUE THREAD

**Issue by mkeremkeskin** [Appboy/appboy-ios-sdk#326]
* I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name          | iOS 
 Platform Version       | 15.*
 SDK Version              | 4.4.0 & 4.4.1
 Integration Method  | Cocoapods
 Xcode Version          | Xcode 13.1
 
## What did you do?
We have sent test push notifications from Braze portal. 

## What did you expect to happen?
We expected to receive push notifications for all our users.

## What happened instead?
**Users with iOS 15 devices can't get push notifications**. But iOS 14 and lower devices can get them successfully.

We are getting `BadDeviceToken` error on iOS 15 devices.
<img width="599" alt="BadDeviceToken" src="https://user-images.githubusercontent.com/4717926/145961869-ee4efc69-0c2c-43a6-9ca5-c8050b24fba8.png">

## Some more info
* The documentation says `BadDeviceToken` error can be related to faulty certificates. But this isn't the case for use since iOS 14 and lower devices can get push notifications.
* This is our first version with Xcode 13. 
    * Our previous version (which is on AppStore) was built with Xcode 12 and Braze 4.3.2. Previous version works well with all iOS versions. 
* In new version we have implemented Time Sensitive notifications also. (I do not think this would break something)

**Comment by Bucimis** [comment]
@mkeremkeskin We haven't seen this with other customers so this should be an isolated situation. What happens if you temporarily disable Time Sensitive notifications?

**Comment by mkeremkeskin** [comment]
@Bucimis actually it is related to **Time Sensitive Notifications**. 

He have found that push notifications not working after installing release version onto development version. Until iOS 15 we didn't encounter this situation. As we observed push notifications are working after uninstalling development version and installing release version. 

Maybe somehow Development and Production device tokens mixing up and giving `BadDeviceToken`. Nonetheless the problem is not related to Xcode version, Braze iOS SDK version or Time Sensitive Notification. Maybe it can be related to how Braze backend works.

**Comment by Bucimis** [comment]
@mkeremkeskin It seems likely that your push credentials on the dashboard don't match the app's build type, or if you're using a universal p8 cert, that you're sending to the wrong gateway for your app's build type

**Comment by hokstuff** [comment]
Hi @mkeremkeskin,

Based on the thread above, it sounds like the issues around push notifications not displaying on your device have to do with the push credentials configuration on the dashboard. If you are still experiencing issues or need additional help debugging, please reach out to support@braze.com. I am closing out this issue because reaching out via the Support channels will be more helpful in this case. Thanks!
