### ISSUE TITLE
In app message is not working in case of  :binary => true

### ISSUE THREAD

**Issue by waqssultan** [Appboy/appboy-ios-sdk#329]
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. iOS
 Platform Version        | e.g. 15.1
 SDK Version             | e.g. 4.3.2
 Integration Method      | Cocoapods 
 Xcode Version           | Xcode 12.5
 Computer Processor      | ntel-based
 Repro rate              |  All the time (100%)
 
## What did you do?
In app message is not working if you set cocoapods binary true. 

## What did you expect to happen?
After clicking on push notification. In app message should come 

## What happened instead?
In app message didnt appear

## Steps to reproduce
Install pods with binary true for app boy and than test in app message. You will get notification but in app message will not show. 

## Are you doing any feature customizations that may relate to the issue? Can you share the code snippet?
Nothing

## Project that demonstrates the issue
Hungerstation app 

https://user-images.githubusercontent.com/78684356/148030781-3c067d11-14d2-41c4-9224-e33e12f34f62.MP4

**Comment by Bucimis** [comment]
@waqssultan thanks for filing and sorry to hear you are running into issues.

Could you fill in the steps to repro and expected/observed behavior a bit more thoroughly to help us debug? If you have a Podfile, like to any third-party build libraries used (e.g. https://github.com/leavez/cocoapods-binary), stacktrace, or logs illustrating the issue, that would be helpful too.

**Comment by waqssultan** [comment]
I have updated my comments

**Comment by Bucimis** [comment]
@waqssultan Thanks. I took a look at the video but I think you'll want to reach out to our support team for more tailored guidance - could you reach out to support@braze.com with your issue, including verbose logs (See https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/#braze-log-level)

**Comment by waqssultan** [comment]
Sure but i feel this issue is similar to this issue. Where binary is not working in Carthage 
https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/pull/29

**Comment by techinpark** [comment]
Any solutions? 

I have same issues. and i figure out what is different
```
- FRAMEWORK_SEARCH_PATHS
- OTHER_FLAGS
- OTHER_LDFLAGS
```
When using `binary: true`  flags It'll be entered twice.

Using cocoapod only 
```
CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = NO
CONFIGURATION_BUILD_DIR = ${PODS_CONFIGURATION_BUILD_DIR}/Appboy-iOS-SDK
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Appboy-iOS-SDK/AppboyKit"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_XCFRAMEWORKS_BUILD_DIR}/Appboy-iOS-SDK/Core/Headers"
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_XCFRAMEWORKS_BUILD_DIR}/Appboy-iOS-SDK/Core"
OTHER_LDFLAGS = $(inherited) -ObjC -l"AppboyKitLibrary" -l"z" -framework "CoreText" -framework "ImageIO" -framework "QuartzCore" -framework "SystemConfiguration" -framework "WebKit" -weak_framework "CoreTelephony" -weak_framework "UserNotifications"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PODS_TARGET_SRCROOT = ${PODS_ROOT}/Appboy-iOS-SDK
PODS_XCFRAMEWORKS_BUILD_DIR = $(PODS_CONFIGURATION_BUILD_DIR)/XCFrameworkIntermediates
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES = YES

```

- Using cocoapod-binary
```
CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = NO
CONFIGURATION_BUILD_DIR = ${PODS_CONFIGURATION_BUILD_DIR}/Appboy-iOS-SDK
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Appboy-iOS-SDK/AppboyKit" "${PODS_ROOT}/Appboy-iOS-SDK/_Prebuilt"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_XCFRAMEWORKS_BUILD_DIR}/Appboy-iOS-SDK/Core/Headers"
LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_XCFRAMEWORKS_BUILD_DIR}/Appboy-iOS-SDK/Core"
OTHER_LDFLAGS = $(inherited) -ObjC -l"AppboyKitLibrary" -l"z" -framework "CoreText" -framework "ImageIO" -framework "QuartzCore" -framework "SystemConfiguration" -framework "WebKit" -weak_framework "CoreTelephony" -weak_framework "UserNotifications"
PODS_BUILD_DIR = ${BUILD_DIR}
PODS_CONFIGURATION_BUILD_DIR = ${PODS_BUILD_DIR}/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}
PODS_TARGET_SRCROOT = ${PODS_ROOT}/Appboy-iOS-SDK
PODS_XCFRAMEWORKS_BUILD_DIR = $(PODS_CONFIGURATION_BUILD_DIR)/XCFrameworkIntermediates
PRODUCT_BUNDLE_IDENTIFIER = org.cocoapods.${PRODUCT_NAME:rfc1034identifier}
SKIP_INSTALL = YES
USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES = YES

```
