### ISSUE TITLE
[Feature]: Allow to set padding in the ABKCaptionedImageContentCardCell

### ISSUE THREAD

**Issue by pchelnikov** [Appboy/appboy-ios-sdk#336]
### What problem are you facing?

I was trying to adjust some inner padding on the content cards and found out that I can't do that on the `ABKCaptionedImageContentCardCell`. Specifically for `titleLabel`, `descriptionLabel`, and `linkLabel`. 

It's possible to adjust padding on the other cards, `ABKClassicImageContentCardCell` for example. But it's hardcoded for the `ABKCaptionedImageContentCardCell` (see this file: https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyUI/ABKContentCards/ViewControllers/Cells/ABKCaptionedImageContentCardCell.m#L163)

### Workarounds

no

### Ideal Solution

Would it be possible to allow us to adjust text padding on the ABKCaptionedImageContentCardCell by introducing some property/properties?

**Comment by Bucimis** [comment]
@pchelnikov thanks for filing this. We agree this is a shortcoming and have filed a story internally to fix. Are you able to use any workarounds or use the default padding for now?

**Comment by pchelnikov** [comment]
@Bucimis thanks for answering. I didn't find any workaround, so using the default padding for now.

**Comment by hokstuff** [comment]
Hi @pchelnikov,

We have released [iOS SDK version 4.4.3](https://github.com/Appboy/appboy-ios-sdk/releases/tag/4.4.3) that addresses this issue. Thanks for filing!
