### ISSUE TITLE
[Bug]: `-[Appboy logCustomEvent:withProperties:]` doesn't log events with empty properties

### ISSUE THREAD

**Issue by HeEAaD** [Appboy/appboy-ios-sdk#337]
### Platform

iOS

### Platform Version

iOS 15.3

### Braze SDK Version

4.4.2

### Xcode Version

Xcode 13.2.1

### Integration Method

Carthage

### Computer Processor

Apple (M1)

### Repro Rate

100% of the time

### Steps To Reproduce

1. Integrate the SDK via Carthage by adding `binary "https://raw.githubusercontent.com/Appboy/appboy-ios-sdk/master/appboy_ios_sdk_core.json" ~> 4.4.2` to the Cartfile
2. Set the log level to 0 (e.g. via Info.plist)
3. Start the SDK by calling `Appboy.start(withApiKey:in:withLaunchOptions:withAppboyOptions:)`.
5. Log an event with **empty** (non nil) properties: `Appboy.sharedInstance()?.logCustomEvent("foo", withProperties: [:])`

### Expected Behavior

The following log message appears in the console:
`[APPBOY][DEBUG] -[Appboy logCustomEvent:withProperties:] Logging custom event with event name foo.`

### Actual Incorrect Behavior

The following log message appears in the console:
`[APPBOY][WARN] -[Appboy logCustomEvent:withProperties:] Not logging custom event with event name: foo. Reason: invalid properties`

### Additional Information

We integrate Braze via mParticle. Here is the call that mParticle makes: https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/blob/44a01d93d5a4ee38fb7490abe65c8ad2c9850bbb/Sources/mParticle-Appboy/MPKitAppboy.m#L158

Therefore, using `logCustomEvent()` or calling `logCustomEvent(withProperties:)` with `nil` properties is not an option.

**Comment by hokstuff** [comment]
Hi @HeEAaD,

Thanks for filing this issue. We have been able to reproduce this issue and are planning to release a fix sometime soon.

**Comment by hokstuff** [comment]
Hi @HeEAaD,

We have released [iOS SDK version 4.4.3](https://github.com/Appboy/appboy-ios-sdk/releases/tag/4.4.3) that addresses this issue. Thanks for filing!
