### ISSUE TITLE
[Bug]: In-app message (Full Screen, Modal) not displayed using Braze SDK 4.4.2 with SPM

### ISSUE THREAD

**Issue by hervouinc** [Appboy/appboy-ios-sdk#338]
### Platform

iOS

### Platform Version

15.3.1

### Braze SDK Version

4.4.2

### Xcode Version

13.0

### Integration Method

Swift Package Manager

### Computer Processor

Intel

### Repro Rate

100%

### Steps To Reproduce

- add SDKv 4.4.2 with SPM using either https://github.com/braze-inc/braze-ios-sdk or https://github.com/Appboy/appboy-ios-sdk (tried both)
- create a campaign "in-app message" from Braze dashboard
- select either Full Screen, Modal or slide-up
- add appropriate content
- go to "test" tab
- enter test user uuid or email

-> the push notification "Tap to see Test in-app message" is well received. 
-> But clicking on it doesn't make the message/view appear on the screen.

### Expected Behavior

The view (modal, full-screen, slide-up) appears over the current app screen

### Actual Incorrect Behavior

The view (modal, full-screen, slide-up) DO NOT appear over the current app screen

### Additional Information

Notes: 
- The issue also happen after launching the campaign.
- Push notifications are well delivered.

Also created an issue on https://github.com/braze-inc/braze-ios-sdk/issues/11

**Comment by lowip** [comment]
Hi @hervouinc, thanks for opening this issue.

Can you verify that you are linking `AppboyUI` and not `AppboyKit`?

<details>
<summary>Xcode configuration page</summary>

<img width="1072" alt="Screen Shot 2022-03-15 at 10 45 16 AM" src="https://user-images.githubusercontent.com/503337/158403837-29d5962a-67b3-4ff2-98b3-79c395a90d82.png">

</details>

If this doesn't resolve the issue, would you mind providing [verbose logs](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/initial_sdk_setup/other_sdk_customizations/) of a session exhibiting the issue?

Thanks,
