### ISSUE TITLE
Is not support Today Extension?

### ISSUE THREAD

**Issue by topkim993** [Appboy/appboy-ios-sdk#339]
### What problem are you facing?

Hello. We are using a custom event log in our main app.

This time, we are going to add custom event log in Today Extension (Old widget).

After adding Cocoa Pod dependency to Today Extension, the following error occurs when building.

'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

Is there any way to solve it?

Thanks for reading.

### Workarounds

Not resolved yet

**Comment by Bucimis** [comment]
@topkim993 Hi, are you attempting to use the Braze SDK inside of an App Extension? The Braze SDK doesn't support running inside of an App Extension.

**Comment by topkim993** [comment]
Yes, Thank you. I will close the issue
