### ISSUE TITLE
[Feature]: Modal In-app message could be dismissed also by tapping on blurred background

### ISSUE THREAD

**Issue by peruginni** [Appboy/appboy-ios-sdk#342]
### What problem are you facing?

As user 
- I will receive [modal in-app message](https://www.braze.com/docs/user_guide/message_building_by_channel/in-app_messages/creative_details/modal/)
- To dismiss I have to tap on cross icon in top right corner. 

It is sometimes little annoying to focus finger on close icon.

### Workarounds

User have to press X (cancel) icon in top right corner. 

### Ideal Solution

Enable tap on blurred background to dismiss in app message.

### Other Information

Feel free to close issue if it is expected wanted behavior.

**Comment by lowip** [comment]
Hi @peruginni,

This behavior is configurable via the [`enableDismissModalOnOutsideTap`](https://appboy.github.io/appboy-ios-sdk/docs/interface_a_b_k_in_app_message_controller.html#a14b85008f82f4fb3b83b856405dbb378) property.

e.g.:
```objc
[Appboy sharedInstance].inAppMessageController.enableDismissModalOnOutsideTap = YES;
```

**Comment by peruginni** [comment]
Aha! Thanks for pointing out the property. I didn't noticed it before. 🎉
