### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SweatSzemis** [Appboy/appboy-ios-sdk#344]
### Platform

iOS

### Platform Version

iOS 13 +

### Braze SDK Version

4.3.0

### Xcode Version

Xcode 13.4

### Integration Method

Cocoapods

### Computer Processor

Intel

### Repro Rate

100%

### Steps To Reproduce

We use bit-rise to automate the iOS deployment process and one of those steps is  xcode-archive

This process worked for Appboy-iOS-SDK version 4.4.2 however not for the latest version 4.4.3

Here is the error message I receive:
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1316.0.21.2.3_0' Reader: '1300.0.29.3_0')', using libLTO version 'LLVM version 13.0.0, (clang-1300.0.29.3)' for architecture arm64

So currently we use version 4.4.2

### Expected Behavior

Automatic Archiving in Bit-rise runs successfully

### Actual Incorrect Behavior

Automatic Archiving in Bit-rise fails

### Verbose Logs

```shell
▸ Linking Appboy_iOS_SDK
❌  ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '1316.0.21.2.3_0' Reader: '1300.0.29.3_0')', using libLTO version 'LLVM version 13.0.0, (clang-1300.0.29.3)' for architecture arm64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by hokstuff** [comment]
Hi @SweatSzemis,

It looks like the bitcode error you're getting is related to the Xcode version being used. The Braze SDK version 4.4.3 was released with Xcode Version 13.4 (13F17a). Can you double check that the version Bitrise is using in your CI is Xcode 13.4?

Thanks!

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. If you are still experiencing issues, please reopen or reach out to support@braze.com directly - thanks!

**Comment by SweatSzemis** [comment]
I was using the Bitrise step Xcode Archive & Export for iOS. However based on your feedback I noticed that the Stack setting for the workflow was defaulted to Xcode 13.0.x 

Updating The Stack setting to Xcode 13.4.x enabled the archiving to complete successfully.
