### ISSUE TITLE
[Bug]: Blank UIWindow when IAM received

### ISSUE THREAD

**Issue by jseidman95** [Appboy/appboy-ios-sdk#346]
### Platform

iOS

### Platform Version

iOS 15.5

### Braze SDK Version

4.4.3

### Xcode Version

13.4.1

### Integration Method

Cocoapods

### Computer Processor

Apple (M1)

### Repro Rate

100% of the time

### Steps To Reproduce

Example:
  1. Set up IAM
  2. Open app and receive IAM
  3. Screen is unresponsive

### Expected Behavior

IAM should show and allow interaction

### Actual Incorrect Behavior

IAM UIWindow shows but is blank and blocks touches to the other UIWindows

### Additional Information

![Screen Shot 2022-08-22 at 3 32 02 PM](https://user-images.githubusercontent.com/24965132/186175263-e3162c30-f211-4e84-a955-0f7b06048fc0.png)
![Screen Shot 2022-08-22 at 3 32 11 PM](https://user-images.githubusercontent.com/24965132/186175269-2b5eb6e9-2491-49b6-8053-73ea1795b3a4.png)

**Comment by hokstuff** [comment]
Hi @jseidman95,

We are unable to reproduce this issue on our end. Can you provide more information around any customization you are doing in the UI layer and the campaign(s) that are affected? To get quicker support on this issue, please raise this concern via our Support channels to get more focused help by emailing support@braze.com.

Thanks!

**Comment by hokstuff** [comment]
I'm closing out this issue due to inactivity. It looks like there may be some customization around this code or else the rootViewController is not as expected / recommended. Please reach out to our Support team with more info if you have further questions.

Thanks!
