### ISSUE TITLE
[Bug]: ABKUIUtils.activeWindowScene sometimes is wrong

### ISSUE THREAD

**Issue by richard-ww** [Appboy/appboy-ios-sdk#351]
### Platform

iOS

### Platform Version

iOS 16.1

### Braze SDK Version

4.5.1

### Xcode Version

Xcode 14.1(14B47b)

### Integration Method

Cocoapods

### Computer Processor

Apple (M1)

### Repro Rate

< 10%

### Steps To Reproduce

1. Turn on the iPhone's mirror feature and make it mirror to your TV
2. Create a In-app message, MESSAGE TYPE = Modal, then send it to target user or device
3. The In-app message was displayed on the TV, and because phones cannot click the close button on Modal, it remained displayed on the TV

### Expected Behavior

It shouldn't show up on the TV, it should show up on the phone for me to click on

### Actual Incorrect Behavior

It sometimes shows up on TV, and maybe once in 10 tries it will have this issue

### Additional Information

After debugging, I think the cause of the problem should be in the following code, two issues here:
1. [self application].connectedScenes - all the state of the scene in the array does not meet the UISceneActivationStateForegroundActive
2. Since the scene in the active state is not found and the last element of the array is taken directly, the scene belonging to the phone should be searched again

+ (UIWindowScene *)activeWindowScene {
  UIWindowScene *windowScene;
  UIWindowScene *activeWindowScene;
  
  // Loop over the connected window scenes to find the last foreground active
  // one. If no scene is currently in foreground state, fallback to last window
  // scene in hierarchy.
  for (UIScene *scene in [self application].connectedScenes) {
    if (![scene isKindOfClass:[UIWindowScene class]]) {
      continue;
    }
    
    windowScene = (UIWindowScene *)scene;
    if (scene.activationState == UISceneActivationStateForegroundActive) {
      activeWindowScene = windowScene;
    }
  }
  return activeWindowScene ?: windowScene;
}

![image](https://user-images.githubusercontent.com/19380564/204238279-551c98e1-695d-4b00-ad67-6d1005a856c2.png)

**Comment by hokstuff** [comment]
Hi @richard-ww,

Apologies for the late reply, and thanks for linking to the code [in ABKUIUtils.m](https://github.com/Appboy/appboy-ios-sdk/blob/dcd1a23f34e0c777dcb68f62c00af8bebe2a31ef/AppboyUI/ABKUIUtils/ABKUIUtils.m#L76)! It sounds like this issue has to do with the iPhone's mirror feature with a TV when displaying a modal in-app message. Are you experiencing this issue with other in-app message types?

I'm also curious if you are experiencing this issue when using our [new Braze Swift SDK](https://github.com/braze-inc/braze-swift-sdk/) which has been written from scratch and may solve the issue you are facing. With the [5.8.0 release](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.8.0) and the associated [Appboy-iOS-SDK migration guide](https://braze-inc.github.io/braze-swift-sdk/documentation/braze/appboy-migration-guide/), the hope is that the migration to the new SDK should be smooth.

**Comment by hokstuff** [comment]
Are you still experiencing this issue?

**Comment by hokstuff** [comment]
I'm closing out this ticket due to inactivity. For others running into a similar issue, we recommend migrating to the Swift SDK which has completely rewritten logic for the UI layer.
