### ISSUE TITLE
[Bug]: Appboy 4.5.2 has been crashed when try to use method "logPurchse:"

### ISSUE THREAD

**Issue by SangChan** [Appboy/appboy-ios-sdk#353]
### Platform

iOS

### Platform Version

iOS 16.2, iOS 16.1.1, iOS 15.5, iOS 14.7

### Braze SDK Version

4.5.2

### Xcode Version

Xcode 14.2, Xcode 14.0.1

### Integration Method

Swift Package Manager

### Computer Processor

Apple (M1),  Apple (Intel)

### Repro Rate

100%

### Steps To Reproduce

1. From Xcode, resolve package and update lastest package
2. Add Appboy.sharedInstance()?.logPurchase(, inCurrency: , atPrice: , withQuantity: , andProperties: ) method in just normal Swift files.
3. properties are typed by [String:Any], and price, currency, quantity are typecasted by known type through docs.
4. Run app from Release mode (not sure with Debug mode also happens)

### Expected Behavior

4.5.2 version is crashed but prior version's not.
Might be problems from variable ,that named "properties", are type by [String: Any] so can't be easy to process but it's not happens until 4.5.1.

### Actual Incorrect Behavior

I saw release note from 4.5.2, and it has validate steps for event trigger so, I think it can cause this happen.

### Verbose Logs

```shell
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1295b4 __exceptionPreprocess
1  libobjc.A.dylib                0x287a8 objc_exception_throw
2  CoreFoundation                 0x2ca9c -[NSOrderedSet initWithSet:copyItems:]
3  CoreFoundation                 0x12c10c ___forwarding___
4  CoreFoundation                 0x12e6b0 _CF_forwarding_prep_0
5  Foundation                     0x129298 getObjectValue
6  Foundation                     0x33258 -[NSNumberFormatter getObjectValue:forString:errorDescription:]
7  Foundation                     0x33154 -[NSNumberFormatter numberFromString:]
8  Yanolja                        0x203b228 -[ABKTriggerPropertyFilter validatePropertyValueType:] + 194 (ABKTriggerPropertyFilter.m:194)
9  Yanolja                        0x203b3e0 -[ABKTriggerPropertyFilter validatedValue:] + 204 (ABKTriggerPropertyFilter.m:204)
10 Yanolja                        0x203a63c -[ABKTriggerPropertyFilter matchValue:] + 78 (ABKTriggerPropertyFilter.m:78)
11 Yanolja                        0x203a5c4 -[ABKTriggerPropertyFilter matchProperties:] + 72 (ABKTriggerPropertyFilter.m:72)
12 Yanolja                        0x20a88cc __38-[ABKPropertyTrigger matchProperties:]_block_invoke_2 + 49 (ABKPropertyTrigger.m:49)
13 CoreFoundation                 0xa741c __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
14 CoreFoundation                 0x1d44 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:]
15 Yanolja                        0x20a87d8 __38-[ABKPropertyTrigger matchProperties:]_block_invoke + 54 (ABKPropertyTrigger.m:54)
16 CoreFoundation                 0xa741c __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__
17 CoreFoundation                 0x2270 -[__NSArrayI enumerateObjectsWithOptions:usingBlock:]
18 Yanolja                        0x20a8650 -[ABKPropertyTrigger matchProperties:] + 45 (ABKPropertyTrigger.m:45)
19 Yanolja                        0x208489c -[ABKCustomEventPropertyTrigger match:] + 21 (ABKCustomEventPropertyTrigger.m:21)
20 Yanolja                        0x2094f64 -[ABKTriggeredAction respondsToTriggerEvent:] + 196 (ABKTriggeredAction.m:196)
21 Yanolja                        0x20686c8 -[ABKTriggerManager topPriorityTriggerActionForEvent:] + 212 (ABKTriggerManager.m:212)
22 Yanolja                        0x2068580 -[ABKTriggerManager triggerActionWithFallbacksForEvent:] + 201 (ABKTriggerManager.m:201)
23 Yanolja                        0x20698d4 -[ABKTriggerManager processTriggerEvent:] + 364 (ABKTriggerManager.m:364)
24 Yanolja                        0x20696d0 -[ABKTriggerManager processPendingTriggerEvents] + 349 (ABKTriggerManager.m:349)
25 Yanolja                        0x2068458 __51-[ABKTriggerManager handleTriggerFromNotification:]_block_invoke + 184 (ABKTriggerManager.m:184)
26 Foundation                     0x131f78 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
27 Foundation                     0x1f848 -[NSBlockOperation main]
28 Foundation                     0x1343a0 __NSOPERATION_IS_INVOKING_MAIN__
29 Foundation                     0x1f4d0 -[NSOperation start]
30 Foundation                     0x134e44 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__
31 Foundation                     0x1348d0 __NSOQSchedule_f
32 libdispatch.dylib              0x13454 _dispatch_block_async_invoke2
33 libdispatch.dylib              0x47ec _dispatch_client_callout
34 libdispatch.dylib              0x7cc4 _dispatch_continuation_pop
35 libdispatch.dylib              0x7410 _dispatch_async_redirect_invoke
36 libdispatch.dylib              0x15fb0 _dispatch_root_queue_drain
37 libdispatch.dylib              0x167a8 _dispatch_worker_thread2
38 libsystem_pthread.dylib        0x3768 _pthread_wqthread
39 libsystem_pthread.dylib        0xa74c start_wqthread
```

**Comment by hokstuff** [comment]
Hi @SangChan,

In your step 3 3) of your steps to repro, it sounds like your application is doing the unsafe command of typecasting an unknown field to the incorrect type, which causes our SDK to crash. In version 4.5.2, we added improved validation for trigger properties to ensure that our SDK properly handles those fields.

> 3. properties are typed by [String:Any], and price, currency, quantity are typecasted by known type through docs.

What class are you typecasting those fields to in your code? Based on the stack trace, the SDK expects an `NSString` during validation, which appears to be why the application is crashing. Can you remove any typecasts from your code and try testing again?

**Comment by hokstuff** [comment]
Hi @SangChan,

We have identified a fix on the Appboy SDK that should address the root cause of your issue, which should allow you to continue using your current implementation. We will post back here once the patch is released.

**Comment by SangChan** [comment]
Hi @hokstuff , nice to hear that.
I glad to wait for next release but I already had a hard time to find way how to reproduce this for helping you guys.. ;(
 
I found clear steps to reproduce this issue for, will write below then.

If all of my team put this code on appdelegate's did finish launch event, app will crash on it.
no matter they already sent or not.

Not sure, but if I change event name from "composition_order_complete" to another, like "1" or "test", it's never crashed.
Hopes, you guy solve this issue for it!


//////////////////////////////////////// --
let dict : Dictionary = [
            "CouponAmount":0.0,
            "PointAmount":0.0,
            "cart_category":"호텔",
            "cart_category_cnt":1,
            "cart_package_discount":0.0,
            "category":"호텔",
            "check_in_date":"2023-01-30",
            "check_out_date":"2023-01-31",
            "composite_order_id":"Y230118XRPLB",
            "cust_count":2,
            "dayuse_included":false,
            "has_children":false,
            "is_earlybird":true,
            "item_detail_id":"141849",
            "item_detail_name":"Standard",
            "item_id":"10006056",
            "item_name":"QA 문 호텔2",
            "paid_amount":30000,
            "property_category":"HOTEL",
            "use_type":"OVER_NIGHT",
            "visitType":"도보"
        ] as [String : Any]
        
 Appboy.sharedInstance()?.logCustomEvent("composition_order_complete", withProperties:dict)
//////////////////////////////////////////////// --

**Comment by Jaechan-So** [comment]
Hello, we also got similar(and almost same) issue in our app. In addition to the information that @SangChan already provided, we noticed that the message in the exception `Fatal Exception: NSInvalidArgumentException` was 
```text
-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance {some_memory_address}
```
 (which was displayed in Firebase Crashlytics). Hope this is helpful for solving issue! 🙏

**Comment by jerielng** [comment]
@SangChan @Jaechan-So Thanks for this extra information! This will be helpful in testing out the fix to ensure that it covers your cases as well!

**Comment by jerielng** [comment]
Hi all, we've just released version `4.5.3`, which should resolve these crashes!

**Comment by Jaechan-So** [comment]
Our team checked that the crash did not occur with version `4.5.3`. Thank you for quick respond! 😊

**Comment by SangChan** [comment]
Look like it seems gone, Many thanks! 🙏
