### ISSUE TITLE
swift and cocoapods `use_frameworks!` "use of unresolved identifier Appboy"

### ISSUE THREAD

**Issue by kylefritz** [Appboy/appboy-ios-sdk#36]
My cocoapods setup has `use_frameworks!` set because we're using pods written in swift. I added Appboy to my bridging header but I can't get the Appboy symbols to after I build.

Here's a repo that demonstrates the issue: https://github.com/kylefritz/appboy-swift-use-frameworks

![screen shot 2015-10-14 at 3 12 30 pm](https://cloud.githubusercontent.com/assets/95741/10496332/40ea6e6a-728e-11e5-9d57-180754f8b5c9.png)

**Comment by briancaw** [comment]
Hi @kylefritz 

Can you let us know what version of CocoaPods and XCode you're using?  We're actively investigating and will update as soon as we have more information.

Thanks,
Brian

**Comment by briancaw** [comment]
Hi @kylefritz 

Can you add the following to your Podfile and let us know if it resolves your issue:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "Appboy-iOS-SDK"
        config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
      end
    end
  end
end
```

Thanks,
Brian

**Comment by kylefritz** [comment]
still seeing the issue after adding the `post_install` hook:

cocoapods version: 0.39.0
xcode: Version 7.0 (7A218)

**Comment by briancaw** [comment]
Hey @kylefritz 

I added `import Appboy_iOS_SDK` to the top of your AppDelegate.swift and got it working.  Please let us know if that fixes the issue for you.

Thanks,
Brian

**Comment by kylefritz** [comment]
Works for me. Thanks a lot @briancaw!!

**Comment by Natelegreat1** [comment]
+1
