### ISSUE TITLE
Dynamic Framework Support

### ISSUE THREAD

**Issue by justin** [Appboy/appboy-ios-sdk#38]
It'd be nice if you bundled and offered a dynamic framework (preferably also via Carthage) instead of a static library. It'd make manual integration much easier, and would make me sleep better at night with the Swift ABI changing so often.

**Comment by Wenzhi** [comment]
Hi Justin,

Dynamic framework is only available for iOS 8, and we are still supporting back iOS 6, so static library strategy will keep living for awhile. 

However, dynamic framework is on our roadmap. Thank you for your suggestion!

Thanks,
Wenzhi
