### ISSUE TITLE
Provide nullability annotations for Swift callers

### ISSUE THREAD

**Issue by keith** [Appboy/appboy-ios-sdk#39]
It would be awesome if you could annotate your source with the new [nullability annotations](https://developer.apple.com/swift/blog/?id=25) for those of us using Appboy from Swift. We've just tracked down a crash where `Appboy.sharedInstance()` returns nil, and since there is no annotation it's interpreted as an implicitly unwrapped optional, causing our app to crash.

**Comment by Wenzhi** [comment]
Hi keith,

Thank you for the suggestion! It's something we want to do too, and is not hard to implement. We should be able to do it soon, and will let you know when we release it.

**Comment by justin** [comment]
+1. I asked this if our appboy contact yesterday.

**Comment by Wenzhi** [comment]
Hi @keith and @justin,

The new iOS SDK (version 2.18.0) now has nullability annotations, Please check it out and let us know if you see any issues or have any questions.

Thanks,
Wenzhi

**Comment by justin** [comment]
Thank you! I'll give it a whirl and provide some feedback in a separate ticket if i run into anything.

**Comment by keith** [comment]
Looks like this added some new warnings for some missing identifiers:

<img width="262" alt="screen shot 2016-01-29 at 11 12 03" src="https://cloud.githubusercontent.com/assets/283886/12685422/2b3bfa18-c679-11e5-8fa9-fc8fce931817.png">
<img width="1182" alt="screen shot 2016-01-29 at 11 12 08" src="https://cloud.githubusercontent.com/assets/283886/12685423/2b3caab2-c679-11e5-9f4d-870715ff9788.png">

**Comment by Wenzhi** [comment]
Hi @keith,
 
I just release version 2.18.1 on both the repo and Cocoapods. It should fix the warnings. Do you mind checking that version and telling me if it fixes the warnings?

Thanks,

**Comment by keith** [comment]
That fixed it, thanks!
