### ISSUE TITLE
Can`t access news feed .

### ISSUE THREAD

**Issue by delarge77** [Appboy/appboy-ios-sdk#40]
I can`t access news feed for a corporate app , since App Transport Security has blocked a cleartext HTTP (http://). I can`t allow http since I don`t have an url from appboy.

**Comment by billmag** [comment]
@delarge77

Can you please clarify a bit more? Do you have the rest of Appboy working and you're having trouble with the news feed? All Appboy traffic runs over https, so there's not reason you should need to allow http for Appboy. Also, please make sure that you're not linking any news feed cards or in app messages to http URLs as the click-through will not be supported.

Separately, can you make sure you've gone through our [ATS Documentation](http://documentation.appboy.com/iOS/#app-transport-securityats)?

-Bill

**Comment by delarge77** [comment]
@billmag Our mistake , some of our employees were linking news to http:// ... Anyway, when there is an error , the message label was not in the right context. (Probably not using auto layout). Thanks a lot anyway .

**Comment by billmag** [comment]
Hey @delarge77 - No problem, thanks for the followup so we can help people with similar problems in the future.
