### ISSUE TITLE
Dynamic framework support

### ISSUE THREAD

**Issue by sashabelonogov** [Appboy/appboy-ios-sdk#43]
Can you please already support #use_frameworks! option for CocoaPods.
In my current project we have currently 20 dependencies and only yours doesn't support it, it disallows us to use frameworks written in Swift. 
I'm sure that your analytics show not so big amount of iOS 6-7 users. Anyhow it's not nice to not support and disallow your users to use technologies that was released 2 years ago.

**Comment by Wenzhi** [comment]
Hi @sashabelonogov,

We do support `use_frameworks!` for Cocoapods. From our [documentation](https://documentation.appboy.com/iOS/#step-2-constructing-the-podfile):

If you are using `use_frameworks!` in your Podfile, please also add following to your Podfile:
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name == "Appboy-iOS-SDK"
        config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
      end
    end
  end
end
```

I'm going to close this issue for now. Please let us know if you have any other quetions or issues.

**Comment by sashabelonogov** [comment]
thanks, Wenzhi! Will do, seems like I can't read the documentation well

**Comment by Wenzhi** [comment]
No worries! The documentation was added recently, maybe that's why you missed it :)

**Comment by sashabelonogov** [comment]
Thanks for updating the documentation, keep up good work!
