### ISSUE TITLE
Open-source AppBoy Framework

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-ios-sdk#44]
Hey there,

We're looking into AppBoy for the newsfeed integration. We've had several bad experiences in the past with closed-source solutions and were wondering if there was any plan to open source your SDK. This would be extremely useful when tracking down bugs and avoid potential integration issues.

Thanks!

**Comment by briancaw** [comment]
Hi @ldiqual 

We have plans to open source much of our UI code, though they are not near enough that we'd be able to offer you a timeline that you'd be able to action on.  I'm happy to update this issue when things are finalized.  

I should mention that our open sourcing of UI code is driven more by enabling maximum flexibility than some of the motivations you mentioned - we aim to build a bug-free, easy-to-integrate, fully flexible SDK, so while we definitely understand some of the benefits of providing open source code, we hope that wouldn't be a deciding factor in choosing Appboy.

Please let us know if you have any more comments/questions.

Thanks,
Brian

**Comment by chshapiro** [comment]
Hey @ldiqual,

As of version 3.5.0, all of our UI code has been open sourced.

I will close this issue for now, but feel free to reopen or open a new issue if you have any further questions.

Thanks,
Chava
