### ISSUE TITLE
Add nullability to SDK

### ISSUE THREAD

**Issue by jgrandelli** [Appboy/appboy-ios-sdk#48]
For better swift interop and compiler checks it would be great to have nullability on all of the properties, method params & returns. Currently everything is an implicitly unwrapped optional. This is because when obj-c code is prepared for swift usage, if there is no nullability specified the compiler doesn't know whether its an optional or not.

> Because the Swift compiler can’t be sure whether a particular `NSView *` is optional or not, the type is brought into Swift as an implicitly unwrapped optional, `NSView!`.

https://developer.apple.com/swift/blog/?id=25

**Comment by Wenzhi** [comment]
Hi @jgrandelli ,

The latest version of the SDK(2.18.1) already has the nullability annotation in all public headers. Could you update the SDK and see if it's working for you?

For reference, there is a closed issue for this: #39. Please let us know if you have any issues or questions.

Thanks,
Appboy iOS team

**Comment by jgrandelli** [comment]
Well shit @Wenzhi! Thanks for the lightening fast response. And now I feel like a dolt.

**Comment by Wenzhi** [comment]
No worries! It's a very new release so you might just miss it. :)

Please kee `pod update` so you always having the hottest Appboy SDK!
