### ISSUE TITLE
Allow theming of card header background (gradient)

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-ios-sdk#50]
Hey there!

I'd like to customize the background of card headers in the news feed:

![image](https://cloud.githubusercontent.com/assets/941453/13589811/b05984a2-e48f-11e5-8d85-4f1ecd9bef34.png)

Is there a way to do this at the moment (couldn't find anything in the NUI properties), and if not, is that something that could be implemented easily?

Thanks and have a great day!

**Comment by Wenzhi** [comment]
Hi @ldiqual

You can customize that view with NUI name `ABKFeedItemTitleBackgroundView`. It supports following NUI properties:
`background-color`
`background-image`
`border-color`
`border-width`
`corner-radius`
`width`

Please let us know if it works for you, or you have any other questions.

Thanks,
Wenzhi

**Comment by ldiqual** [comment]
@Wenzhi Thanks! That worked. This was not in the doc though: https://documentation.appboy.com/iOS/#full-list-customizable-elements--associated-properties

**Comment by Wenzhi** [comment]
@ldiqual Thanks for reporting it! I already have a pull request for it and the documentation will be updated soon.
