### ISSUE TITLE
Document User Header Search Path step for cocoapods with swift integration 

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-ios-sdk#51]
I had to add the following user search path for a complete cocoapods integration, otherwise the bridging header couldn't find `AppboyKit.h`:

```
$(SRCROOT)/Pods/Appboy-iOS-SDK
```

![image](https://cloud.githubusercontent.com/assets/941453/13589958/e79cdecc-e490-11e5-8370-6a1249810ef4.png)

Is that something you could add to your documentation?

Let me know if you need anything from me to investigating on the underlying issue.

**Comment by briancaw** [comment]
Hi @ldiqual 

You should be able to do the import of `AppboyKit.h` like  `#import <Appboy_iOS_SDK/AppboyKit.h>` without modifying the header search path.  It looks like our documentation says how to import for manual integration but not Cocoapods - we'll update that ASAP.  

If you can confirm that this style of import works for you it'd be greatly appreciated.  Thanks for reporting!

- Brian

**Comment by ldiqual** [comment]
@briancaw Thanks for the followup!

If I remove the path from `User Search Path`, and add `#import <Appboy_iOS_SDK/AppboyKit.h>` to my bridging header, I get

 > file:path: Use of undeclared type 'ABKFeedViewControllerModalContext'

Referenced file contains:

```
class SCNewsFeedVC: ABKFeedViewControllerModalContext {}
```

I don't get any error in the bridging header (so it seems to find the header properly).

Cocoapods 0.39.0

Podfile:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

link_with 'App'

pod 'Appboy-iOS-SDK', '2.19.0'
pod 'Segment-Appboy', '1.0.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == "Appboy-iOS-SDK"
                target.build_configurations.each do |config|
                    config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
                end
            end
        end
    end
end
```

**Comment by briancaw** [comment]
Hey @ldiqual 

Do you have `import Appboy_iOS_SDK` at the top of your file that contains that class?  That would be required for it to resolve.

Also - if you are using Appboy through Segment, Appboy will be included automatically via the `Segment-Appboy` inclusion and you should remove the `Appboy-iOS-SDK` declaration in your Podfile (and also update to 1.0.1).  If you are just using Appboy separately from Segment,  you don't need the `Segment-Appboy` in your Podfile.

Thanks,
Brian

**Comment by ldiqual** [comment]
@briancaw Using `import Appboy_iOS_SDK` worked without modifying the user header path and without importing anything in the bridging header. This is what confused me in the doc:

https://documentation.appboy.com/iOS/#step-4-updating-your-app-delegate
 > Swift: If you do not have a bridging header file, create one and [...] add `#import "AppboyKit.h"`

 Turns out you do not need to create that file (or import `AppBoyKit.h`) with cocoapods 0.39.0.
You might want to remove this from your docs.

Thanks for the help!

**Comment by briancaw** [comment]
Hey @ldiqual 

Glad things are working, and thanks again for the feedback - we'll have the documentation updated today.

Brian
