### ISSUE TITLE
When a new Appboy item is available, the app itself should badge (not just the tab within the app)

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-ios-sdk#52]

**Comment by briancaw** [comment]
Hi again @ldiqual, 

Just to make sure I have it right - you want the app badge count to get updated to the number of unread News Feed cards?  Can you take a look at https://documentation.appboy.com/iOS/#requesting-unread-card-count and let us know if that is sufficient for your user case?  If not, please let us know how your use case differs.

Thanks,
Brian

**Comment by ldiqual** [comment]
@briancaw Ooops, that was not meant to be opened on this repo at all. Very sorry about this.

**Comment by briancaw** [comment]
No worries @ldiqual, happy to see your integration moving along!
