### ISSUE TITLE
unreadCardCountForCategories returns 0 after calling changeUser with new user ID

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-ios-sdk#53]
I'm using Segment-Appboy 1.0.0 with Appboy-iOS-SDK 2.19.0.

Here's the workflow I'm implementing:
 - User A signs in and looks at the news feed. Unread count falls to 0
 - User A signs out. As per the Segment integration, this action does *not* call `Appboy.changeUser()`
 - User B creates an account. This calls `Appboy.changeUser()` with the new ID.
 - `feedController.unreadCardCountForCategories(.All)` is still 0 (even though there are 6 cards in the news feed that user B never saw)

```
// segment.identify() called explicitly
// Appboy.sharedInstance()?.changeUser() called implicitly
// Appboy.sharedInstance()?.feedController.requestFeedRefresh() called explicitly
// Breakpoint is in a handler of ABKFeedUpdatedNotification

(lldb) po feedController.unreadCardCountForCategories(.All)
0

(lldb) po Appboy.sharedInstance()?.user.userID
▿ Optional("2be78c76-9ed4-4ac1-b3fd-22e0587d743a")
  - Some : "2be78c76-9ed4-4ac1-b3fd-22e0587d743a" // Different from User A's ID
```

By introspecting the cards themselves, I figured that all of them have `viewed = true`, which makes me think that either your servers return something wrong, or the instance of `ABKFeedViewControllerModalContext` (which is in a tab, initted but not visible -- `awakeFromNib` is called but not `viewDidLoad`) overrides that value before my handler gets called.

Any thoughts on where the issue lies?

**Comment by Wenzhi** [comment]
Hi @ldiqual 

Thanks for reporting. After the investigation, it seems like it's an SDK bug of unread card count when changing a known user to another user.

I'm working on a fix for it, but we don't have an estimated date for the next release for now. I'll let you know as soon as we have a plan for the release date, which may be as early as the end of next week, but it could also take a couple of weeks. We will release it as soon as possible.

Thanks,
Wenzhi

**Comment by ldiqual** [comment]
@Wenzhi Thanks!

**Comment by Wenzhi** [comment]
Hi @ldiqual,

The new release(version 2.19.1) fixes this issue. If you could test and confirm it resolves your issue it'd be greatly appreciated.

Thanks,
Wenzhi

**Comment by ldiqual** [comment]
@Wenzhi It solved the issue! Thanks so much for tackling this.
