### ISSUE TITLE
Carthage integration

### ISSUE THREAD

**Issue by hovox** [Appboy/appboy-ios-sdk#55]

**Comment by briancaw** [comment]
Hi @hovox,

Thanks for giving us this signal - we'll strategize around Carthage support and update with a timeline ASAP.

Brian

**Comment by justin** [comment]
I would like this too. We asked for it when we were on boarding, but never really got a timeline.

**Comment by rskuja** [comment]
I was also in need for Carthage support so i made a fork and published release with Carthage support.
Available here: https://github.com/fullcontact/appboy-ios-sdk

This is only temporary until AppBoy team will add official support.

Only thing required to add basic Carthage support is publish release along with zipped framework so Carthage can download it. Example here: https://github.com/fullcontact/appboy-ios-sdk/releases

**Comment by billmag** [comment]
@rskuja -- apologies for the delays on our side, but thank you for doing this! We'll aim to fold this into official support for the next point release we do.

**Comment by davidblaesing** [comment]
@billmag When are you planning to make a new release including shared carthage scheme?

**Comment by briancaw** [comment]
Hey All,

We are planning on releasing Carthage support in our next release, which will come out this week.  We had intended to put this in 2.19.3 but the release timeline for 2.19.3 was moved forward and this had to be pushed out a release - apologies again for the delay.

Support will be in the form of a zipped framework attached to the release.  Please let us know if there are any further comments/questions.

Thanks,
Brian

**Comment by Wenzhi** [comment]
Hey @hovox, @justin and @davidblaesing,

Appboy SDK version 2.20.0 has been released with Carthage support. Please let us know if you have any further comments, questions or suggestions. Thank you very much for helping improve the Appboy's SDK!

Also, special thanks to @rskuja for the help here!

Thanks,
Wenzhi

**Comment by shanev** [comment]
@Wenzhi I'm getting the following error after switching to Carthage:

```
dyld: Library not loaded: @rpath/SDWebImage.framework/SDWebImage
  Referenced from: ../Frameworks/Appboy_iOS_SDK.framework/Appboy_iOS_SDK
  Reason: image not found
```

SDWebImage is also installed via Carthage, but the framework name is WebImage.framework, not SDWebImage.

**Comment by Wenzhi** [comment]
Hi @shanev, 

Your issue looks similar to this issue:https://github.com/Carthage/Carthage/issues/616. Could you confirm that:
- In your Build Settings, the "Framework Search Paths" includes: `$(PROJECT_DIR)/Carthage/Build/iOS` (and the directory is the correct one)
- Also in your Build Settings, the "Runpath Search Paths" includes: `$(inherited)` and `@executable_path/Frameworks`
- In your Build Phases, there is "Embedded Framework". If not, you can follow @ikesyo's comments in https://github.com/Carthage/Carthage/issues/615#issuecomment-120927579: 
```
you should add a new "Copy Files Phase," then select "Frameworks" for Destination, add frameworks to the list, and check "Code Sign On Copy" checkboxes.
 ```

I see you also mentioned you installed the SDWebImage via Carthage. Could you send us your `Cartfile` so we can try to repo the issue?


Thanks,
Wenzhi

**Comment by davidblaesing** [comment]
@shanev We have one problem with "SDWebImage.framework".
Are you using https://github.com/rs/SDWebImage as dependency? Because we are getting a "WebImage.framework" from https://github.com/rs/SDWebImage on v3.7.6
This causes that we have duplicated functions in frameworks. Can you please update that dependency?

best,
David

**Comment by briancaw** [comment]
Hey all,

It's not entirely clear why SDWebImage modified their name for their Framework build - some other folks have called this out as an issue; see https://github.com/rs/SDWebImage/issues/1467.  As for our Carthage support, we bundle SDWebImage in the release zip with the proper name, i.e. `SDWebImage.framework` which works with the Framework we release.  @davidblaesing @shanev Are you able to use the SDWebImage Framework that we bundle into our release?

Please let us know any further questions/comments.

Thanks,
Brian

**Comment by justin** [comment]
Speaking for @shanev, we were able to switch to the bundled SDWebImage. Still hoping for #46 to land so we can remove our dependency on SDWebImage entirely.

**Comment by Wenzhi** [comment]
Hey All,

We released Carthage support this past May in version 2.20.0. I'm going to close this issue. Please let us know if you have more questions or issues regarding Carthage integration. 

Thanks,
Wenzhi
