### ISSUE TITLE
In-app messaging silently fails if SDWebImage isn't installed

### ISSUE THREAD

**Issue by shanev** [Appboy/appboy-ios-sdk#58]
At least output an error message to the console, or add a debug mode.

**Comment by Wenzhi** [comment]
Hi @shanev,
 
Thanks for the suggestion! We definitely should log an error message in that case. We will add it to the SDK.

Thank you,
Wenzhi

**Comment by briancaw** [comment]
Hi @shanev 

This is updated now in release version 2.19.2 that just went live.  I'm guessing you already have SDWebImage installed, but if you come across this again please let us know.  Thanks again for reporting.
