### ISSUE TITLE
-[ABKSession setLastKnownTime:] crash

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-ios-sdk#60]
Hey there,

We just got a crash report in `ABKSession`. So far it's said to be affecting only one user, but since it happens on app start, there might be a lot more that just didn't send (crashlytics sends crashes on app start, so the network call might not have enough time to complete).

```
Appboy_iOS_SDK
-[ABKSession setLastKnownTime:]
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000800
```

![image](https://cloud.githubusercontent.com/assets/941453/14051395/c7ae75b0-f27f-11e5-9540-40dbbcdd7d87.png)

There's nothing worth mentioning in AppDelegate.swift:20, it's just 

```
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate { // Line 20

    var window: UIWindow?
...
}
```

There is no Appboy related code in the appdelegate either (we integrate via segment).

Appboy 2.19.0

Affected user:

![image](https://cloud.githubusercontent.com/assets/941453/14051477/75c9af7a-f280-11e5-92d7-4ed470e4e55b.png)

**Comment by briancaw** [comment]
Thanks @ldiqual,

We don't have a real strong intuition for what might be causing this - that method has been unchanged for a long time, we've never seen any similar/related issues, and the actual functionality there is fairly simple.  

Do you have any indication that this might be happening more frequently? i.e. do you see any dramatic drop in sessions/users or have you had any further reports of crashes?  We'll continue to inspect this functionality on our end; any more information would be greatly appreciated.

Thanks,
Brian

**Comment by ldiqual** [comment]
@briancaw Thanks for the followup. So far, only one crash report. No dramatic changes in our analytics so it seems under control. Please feel free to share the underlying code if you need more eyes on this. Cheers

**Comment by briancaw** [comment]
Hey @ldiqual 

We haven't been able to track this down yet with the information available.  Have you seen it again?  If so is there any new information regarding the crash?

Thanks,
Brian

**Comment by ldiqual** [comment]
@briancaw Thanks for getting back to me. We only had one occurrence of this crash, and the current version of our app isn't affected. I'll just close the issue and reopen if it happens again. Thanks!
