### ISSUE TITLE
Put the pod name in the documentation

### ISSUE THREAD

**Issue by jessejamesrichard** [Appboy/appboy-ios-sdk#62]
Maybe I missed it somewhere, but it'd be helpful if you put **pod 'Appboy-iOS-SDK'** somewhere in the readme. Just makes things faster. Friendly suggestion.

**Comment by briancaw** [comment]
Hey @jessejamesrichard 

Our README links out to our technical docs https://documentation.appboy.com/ which has that integration info and our repo also has the podspec in the root where it can be found...generally I'd prefer to have folks integrating focus on the technical documentation as there are details there that are essential for integration and I'd prefer to have integration information centralized in one spot.

I did just drop a quick reference to our pod name in the README, though I did it in the sample app description so it's not jumping out at folks.  Hopefully that's enough for people doing quick testing and are familiar with CocoaPods...etc. to quickly see the pod name but won't steer folks away from our technical docs.

Please let me know if you have further thoughts on this given this info, and thanks very much for the suggestion.
