### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/4EDA6C7E-C204-460D-BF4D-3107E7D6ADFA/Fetchr.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle> (not yet loaded)' with name 'ABKInAppMessageFullViewController'

### ISSUE THREAD

**Issue by senthilkumariosdev** [Appboy/appboy-ios-sdk#66]
Pls give the solution for this issue. We are using 2.19.2 version of cocoapods.

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0x182db6e38 __exceptionPreprocess
1  libobjc.A.dylib                0x18241bf80 objc_exception_throw
2  CoreFoundation                 0x182db6d80 -[NSException initWithCoder:]
3  UIKit                          0x1883d70f0 -[UINib instantiateWithOwner:options:]
4  UIKit                          0x1883d9870 -[NSBundle(UINSBundleAdditions) loadNibNamed:owner:options:]
5  Appboy_iOS_SDK                 0x1011350e0 -[ABKInAppMessageFullViewController loadView] (ABKInAppMessageFullViewController.m:120)
6  UIKit                          0x187f007ec -[UIViewController loadViewIfRequired]
7  UIKit                          0x187f00744 -[UIViewController view]
8  Appboy_iOS_SDK                 0x10108b3cc -[ABKInAppMessageWindowController viewDidLoad] (ABKInAppMessageWindowController.m:73)
9  UIKit                          0x187f00b40 -[UIViewController loadViewIfRequired]
10 UIKit                          0x187f00744 -[UIViewController view]
11 UIKit                          0x187f0749c -[UIWindow addRootViewControllerViewIfPossible]
12 UIKit                          0x187f04988 -[UIWindow _setHidden:forced:]
13 Appboy_iOS_SDK                 0x10108d88c __71-[ABKInAppMessageWindowController displayInAppMessageViewWithAnimation]_block_invoke (ABKInAppMessageWindowController.m:222)
14 libdispatch.dylib              0x1828014bc _dispatch_call_block_and_release
15 libdispatch.dylib              0x18280147c _dispatch_client_callout
16 libdispatch.dylib              0x182806b84 _dispatch_main_queue_callback_4CF
17 CoreFoundation                 0x182d6cdd8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
18 CoreFoundation                 0x182d6ac40 __CFRunLoopRun
19 CoreFoundation                 0x182c94d10 CFRunLoopRunSpecific
20 GraphicsServices               0x18457c088 GSEventRunModal
21 UIKit                          0x187f69f70 UIApplicationMain
22 Fetchr                         0x10039b730 main (AppDelegate.swift:21)
23 libdispatch.dylib              0x1828328b8 (Missing)

**Comment by Wenzhi** [comment]
Hi @senthilkumariosdev,

We suspect that your issue may be caused by an improper Appboy.bundle integration. Does this issue happen every time you try to display a full in-app message? Could you share more information about how you integrate Appboy?

It will help us troubleshoot faster if you would also check and confirm that:
(1) you can see Appboy.bundle in the "Copy Bundle Resources" within your Pods project,
![image](https://cloud.githubusercontent.com/assets/996652/15016718/81d9f160-11e0-11e6-9dc1-0aeb6a03e926.png)
(2) You have "Copy Pods Resources" in your project's "Build Phases" tab.
![image](https://cloud.githubusercontent.com/assets/996652/15016756/ae9e21d0-11e0-11e6-8ea3-a281e75e1a4b.png)

Thanks,
Wenzhi

**Comment by senthilkumariosdev** [comment]
Hi @Wenzhi
 Thanks for your prompt response.
 We are installed the sdk through cocoapods . Here below i have attached the screenshot
<img width="872" alt="screen shot 2016-05-05 at 10 56 09 am" src="https://cloud.githubusercontent.com/assets/15072949/15036669/0d9062aa-12b0-11e6-9c27-df769f64ad7c.png">
<img width="869" alt="screen shot 2016-05-05 at 10 56 28 am" src="https://cloud.githubusercontent.com/assets/15072949/15036670/0deb3c16-12b0-11e6-9309-cf911810259f.png">

**Comment by Wenzhi** [comment]
Hi @senthilkumariosdev,

I double checked our sample apps, in both objective-C and Swift, but failed to reproduce the issue. After Googling, I noticed that some other people have the same issue while using the Cocoapods.  

(1) It can occur when the nib is removed by accident. Could you go to your Pods Project -> "Pods" -> "Resources" -> "Appboy.bundle", and see if you can find ABKInAppMessageFullViewController.nib in it? If you can find it, could you tell me whether "Appboy-iOS-SDK" is selected in the "Target Membership" in the file inspector?

(2) Can you display any other Appboy UI page, like news feed, feedback, or another type of in-app messages?

(3) Could you show me your Podfile? If possible, could you also send me a sample workspace to reproduce the issue?

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
@senthilkumariosdev, 

Any updates? Do you still have the issue?

Thanks,
Wenzhi

**Comment by briancaw** [comment]
Hi @senthilkumariosdev 

We've been unable to reproduce this on our end and haven't had any other people report this issue.  Without further information we'll have trouble continuing our debugging, so we're going to close for now.

If you are still having this issue and are able to provide further information please reopen this and we'll continue investigating ASAP.

Thanks,
Brian
