### ISSUE TITLE
Enable bitcode link error

### ISSUE THREAD

**Issue by gintechsystems** [Appboy/appboy-ios-sdk#70]
Receiving the following error when building with the latest version:

libAppboy-iOS-SDK.a(ABKIdentifierForAdvertisingProvider.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I am using the sdk without facebook support.

**Comment by Wenzhi** [comment]
Hi @gintechsystems, 

Thanks for reporting this. May I have more information:
* How do you integrate Appboy, through Cocoapods, Carthage or manual integration? 
* What is the Appboy SDK version you are using? 

Thanks,
Wenzhi

**Comment by gintechsystems** [comment]
@Wenzhi Sure. I am using Cocoapods and using 2.9.6 SDK version. Is there any work around, maybe going to a lower version?

**Comment by gintechsystems** [comment]
@Wenzhi hi Hey so I was using the following in my pod file:

pod 'Appboy-iOS-SDK'

This was downloading only 2.9.6, not sure why. Using Cocoapods 1.0. I then switched to using:

pod 'Appboy-iOS-SDK', :git => 'https://github.com/Appboy/appboy-ios-sdk.git'

This downloaded the latest version of the SDK and I was able to build successfully.

**Comment by gintechsystems** [comment]
@Wenzhi I noticed the SDK setup was updated under the documentation. I am using Xcode 7+ so I didn't realize a version had to be specified. This is not a bug and can be closed. Sorry for the inconvenience.

**Comment by Wenzhi** [comment]
Hi @gintechsystems,

Glad to hear the issue is solved!

In general, if you run `pod update`, Cocoapods should automatically pull down the latest version without a specified version. If `pod update` doesn't do that, It seems to me that there is something wrong with the Cocoapods cache. You can try `pod cache clean`. You can also try uninstall and then re-install cocoapods.

Thanks,
Wenzhi
