### ISSUE TITLE
Updating SDWebImage

### ISSUE THREAD

**Issue by JonathanBouaziz** [Appboy/appboy-ios-sdk#71]
Hey guys,

We need to use `SDWebImage` 3.8+ because of swift 2.0 but your SDK requires ~> 3.7. Is there any reason why you're not updating it?

For some reasons it installs the Appboy-iOS-SDK 2.9.6 when running a `pod install`, it's probably related to the dependency.

Cheers,
Jonathan

**Comment by briancaw** [comment]
Hi @JonathanBouaziz

We're currently strategizing around adopting SDWebImage 3.8 and will get back to you ASAP (the update to deployment target of 7.0 and QA/testing are the major items we're addressing).

In the meantime, SDWebImage 3.7+ should be compatible with Swift 2.0 - what error/conditions are forcing you to use 3.8?

Thanks,
Brian

**Comment by JonathanBouaziz** [comment]
Hi @briancaw,

It's great to hear. We're using `SDWebImage/WebP` and there were some errors when building it using `use_frameworks!`.

Do you know why I'm getting the version 2.9.6 when installing 'Appboy-iOS-SDK/AppboyKitWithoutFacebookSupport'?

Best,
Jonathan

**Comment by briancaw** [comment]
Hi @JonathanBouaziz 

We updated the Cocoapods integration to not have the Facebook support subspec in 2.10.0 and that's why you'd be getting an older version.  Per our current instructions you can just do `pod 'Appboy-iOS-SDK'` in your `Podfile`.

With the most recent SDK are you still getting issues with SDWebImage on 3.7+?

Thanks,
Brian

**Comment by JonathanBouaziz** [comment]
When I force the new version of your SDK, I'm getting the following errors:
```sh
[!] Unable to satisfy the following requirements:

- `SDWebImage (~> 3.7.0)` required by `Appboy-iOS-SDK (2.20.1)`

Specs satisfying the `SDWebImage (~> 3.7.0)` dependency were found, but they required a higher minimum deployment target.
```

So then I try to rollback `SDWebImage` to 3.7.x but I'm getting Xcode errors because of the WebP library in `SDWebImage/WebP`.
![image](https://cloud.githubusercontent.com/assets/8112574/16110633/016743f2-33af-11e6-87ce-f565e86c75f3.png)

That's why we need `SDWebImage` 3.8 and onwards.

**Comment by JonathanBouaziz** [comment]
Hi @briancaw,
I was about to submit a new app for review but since we're using an old version of you SDK, [this issue](https://github.com/Appboy/appboy-ios-sdk/issues/35) resurfaced. Meaning that we can't submit a new version of the app. How soon do you think this could be resolved?
Thanks

**Comment by billmag** [comment]
Hey Jonathan-

Apologies for the slower than usual resolution here, our iOS team has been
at WWDC all week. We'll have an answer for you today (Pacific time).

Apologies again.

-Bill

**Comment by billmag** [comment]
Hey Jonathan-

Quick aside - our initial investigation suggested that your issue is likely
the same as this one: https://github.com/rs/SDWebImage/issues/1444

It is caused by a functionality change in Cocoapods 1.0.0. A workaround is
here, if you want to give that a shot in the meantime:
https://github.com/kenmaz/SDWebImage/commit/5034c334be50765dfe4e97c48bcb74ef64175188

Wenzhi or Brian can provide guidance on a more permanent fix later today,
but wanted to get you that workaround potential ASAP.

Sorry again for the trouble.

-Bill

**Comment by JonathanBouaziz** [comment]
Hey @billmag,

I've just specified to use [kenmaz](https://github.com/kenmaz/SDWebImage) repo instead as you suggested, it seems to be working!

Could you please let me know when you update your SDK tu support `SDWebImage 3.8.x`?

Thanks!
Jonathan

**Comment by billmag** [comment]
Aaa, great, I'm glad that workaround worked.

@briancaw or @Wenzhi will update you with the plan for SDWebImage upgrades.

**Comment by nahlam** [comment]
Any updates about this part i'm still getting this

[!] Unable to satisfy the following requirements:

- `SDWebImage (~> 3.8.1)` required by `Podfile`
- `SDWebImage (~> 3.7.0)` required by `Appboy-iOS-SDK (2.20.1)`

**Comment by briancaw** [comment]
Hi @nahlam 

Are you able to use the same solution as above as a temporary workaround - i.e. using https://github.com/kenmaz/SDWebImage/commit/5034c334be50765dfe4e97c48bcb74ef64175188?

We'll be dropping iOS6 support in the near future (weeks) and with that change we'll be updating to the latest SDWebImage.  Please let us know any further comments or questions.

Thanks,
Brian

**Comment by JonathanBouaziz** [comment]
Hey @briancaw, 

I thought that I did get back to you, sorry about that. The workaround works for now.

Please let me know once you update the framework.

Best,
Jonathan

**Comment by briancaw** [comment]
Hi @JonathanBouaziz @nahlam 

We've updated our SDWebImage dependency to support the latest version (which should fix this issue).  If you could confirm that this is fixed it would be much appreciated.  If updating doesn't solve things for you, please reopen the issue.

Thanks,
Brian
