### ISSUE TITLE
Podfile issue running sample code, 1.0.1

### ISSUE THREAD

**Issue by gemmakbarlow** [Appboy/appboy-ios-sdk#74]
Following the instructions for your sample-code

> Example - Contains the Stopwatch Sample App which contains integration examples for the iOS SDK.
> The Stopwatch Sample App uses our CocoaPods integration (Appboy-iOS-SDK), so you must :
> Install CocoaPods
> Run pod install in the Example directory
> Open the Stopwatch.xcworkspace to open the project. 

 using CocoaPods 1.0.1 I receive the following error:

> Re-creating CocoaPods due to major version update.
> Analyzing dependencies
> [!] The dependency `Appboy-iOS-SDK` is not used in any concrete target.
> The dependency `NUI (from `https://github.com/tombenner/nui.git`)` is not used in any concrete target.
> The dependency `KKColorListPicker (from `git@github.com:leoru/KKColorListPicker.git`)` is not used in any concrete target.

A quick Google Search would suggest that a specific target needs to be specified in your Podfile

http://stackoverflow.com/questions/34556991/pod-install-displaying-error-in-cocoapods-version-1-0-0-beta-1

Happy to put up a PR to assist; let me know 😄

**Comment by Wenzhi** [comment]
Hey @gemmakbarlow,

Thanks for reporting the issue! We will have the fix in our next release, but a PR is also very welcome! 

Thanks for helping us improving our product :)
Wenzhi

**Comment by mosquitolwz** [comment]
Hey @gemmakbarlow ,

This issue is fixed in the newly release. I'm going to close the issue for now. Please feel free to re-open it if you still see the problem!

Thank you so much for reporting :)
Wenzhi

**Comment by Wenzhi** [comment]
Hey @gemmakbarlow, 

This issue is fixed in the latest release. I'm going to close the issue for now, but please feel free to re-open it if you still see the problem.

Thank you for the report! :)
Wenzhi

**Comment by gemmakbarlow** [comment]
Fantastic - thanks !
