### ISSUE TITLE
2.21.0 fails to copy resources

### ISSUE THREAD

**Issue by keith** [Appboy/appboy-ios-sdk#76]
When trying to build with version 2.21.0 installed via CocoaPods, these errors are produced when attempting to copy the resources into the built product:

```
Appboy_iOS_SDK.framework/Appboy.bundle/
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKBannerCardCell.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKCrossPromotionCardCell.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKFeedNoConnectionView.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKFeedbackContentView.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKFeedbackEmailViewPortrait.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKFeedbackNavBar.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKInAppMessageFullViewController_iPad.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKInAppMessageHTMLFullViewController.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKInAppMessageModalViewController_iPad.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKSpinnerView.nib" failed: Directory not empty (66)
rsync: delete_file: rmdir ".../Foo.app/Frameworks/Appboy_iOS_SDK.framework/Appboy.bundle/ABKTextAnnouncementCardCell.nib" failed: Directory not empty (66)
```

This ends up causing the build to fail.

**Comment by Wenzhi** [comment]
Hey @keith, 

Thanks for reporting this! We are investigating it right now.

May I ask what version of Cocoapods are you using? I assume you also use `use_frameworks!`?

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
Hey @keith, 

We are having trouble reproducing the issue in our swift sample apps. Could you let us know:
- What version of Cocoapods you are using?
- What your Podfile looks like?

I see the errors are from an app called Foo. I assume that's a sample app? Could you send that sample app to wenzhi@appboy.com for us to look at? 

Thanks,
Wenzhi

**Comment by keith** [comment]
We're using CocoaPods `1.0.1` and `use_frameworks!`. Our Podfile doesn't have anything else relevant to Appboy besides the single include.

I removed our app name from the log, I don't have a sample app that reproduces this.

**Comment by Wenzhi** [comment]
Hey @keith 

I tried with 1.0.1 Cocoapods and still cannot reproduce. Could you download our sample project [here](https://github.com/Appboy/appboy-ios-sdk/tree/master/HelloSwift) and see if the project works for you?

The issue seems related to when Cocoapods tries to copy the resource files to build the framework. Could you also try to clean the build folder and the project, and see if that fixes the issue? 

Thanks,
Wenzhi

**Comment by keith** [comment]
This works with a clean build, so I guess it's just an artifact the upgrade ¯\\_(ツ)_/¯

As an aside, if we're not using any Appboy UI directly, is it safe to *not* include the `.bundle` in our project?

**Comment by Wenzhi** [comment]
Hi @keith,

If you are not using Appboy UI at all, removing the .bundle from the project should be fine. However, if someone sends a campaign that involves Appboy UI by accident, it will cause the app to crash. I would recommend not removing it for this reason, especially if you want to eventually send UI campaigns

thanks 
Wenzhi

**Comment by keith** [comment]
It would be great if these portions could be separated into subspecs. As discussed here https://github.com/Appboy/appboy-ios-sdk/issues/46

**Comment by Wenzhi** [comment]
Hi @keith

That is definitely something we’re aiming to do in the not too distant future.  It’s a fairly large task though and we’ve got aggressive goals on other features we want to ship, so we don’t have a solid timeline for that right now.  Apologies for the delay, and thanks very much for the signal here.

Thanks for the patience here! :)

Wenzhi

**Comment by keith** [comment]
No worries! Thanks!
