### ISSUE TITLE
Request newsfeed content for specific language

### ISSUE THREAD

**Issue by davidblaesing** [Appboy/appboy-ios-sdk#77]
Is it possible to request newsfeed content for a specific language?
I am using `Appboy.sharedInstance()?.requestFeedRefresh()` to get the content. Looking for a function like `Appboy.sharedInstance()?.requestFeedRefresh(forLanguage: "de-DE")`.
Maybe its possible to set the country manually before I request the content?

The users should be able to to see the content in other languages without changing the personal assigned country in profile.

best,
David

**Comment by briancaw** [comment]
Hi @davidblaesing 

Currently we do not have a function that requests the News Feed for a given language.  What you can do is set a country or a language in the standard user profile and template on that in the News Feed card.  If you don't want to change a standard user attribute, you can set a custom attribute and template on that.

See https://www.appboy.com/academy/Dashboard_Features/#sending-messages-based-on-language-and-most-recent-locale for guidance on how to do that.  

Please let me know if you have any further comments/questions.

Thanks,
Brian

**Comment by briancaw** [comment]
Hi again @davidblaesing 

Going to close this for now - if you have further thoughts on our recommended solution (i.e. setting a custom attribute) and/or more information about the functionality you're aiming to provide we'd very much appreciate hearing them as we'll consider this again as we make updates to our News Feed.

Thanks,
Brian
