### ISSUE TITLE
-[ABKManager requestDataRefresh] crash on 2.21.0

### ISSUE THREAD

**Issue by ldiqual** [Appboy/appboy-ios-sdk#79]
Crashlytics: http://crashes.to/s/3dd9e002ace

Let me know if you have any question

**Comment by Wenzhi** [comment]
Hi @ldiqual ,

Thanks for reporting the crash! As the line numbers in trace track doesn't match the actual line number in our code, I have some follow-up questions:
- How frequently the crash happens?
- Are you able to reproduce the crash? If you can, what are the steps?
- Do you have the user ID for this user in the crash report? Could you pass it to us?

Thanks,
Wenzhi

**Comment by briancaw** [comment]
Hi @ldiqual 

Are you still seeing this issue?  Do you have any info regarding @Wenzhi's questions?

Thanks,
Brian

**Comment by ldiqual** [comment]
@briancaw @Wenzhi Sorry for the delay, I completely missed @Wenzhi 's question. Only happened once, I think it's safe to close. Thanks!
