### ISSUE TITLE
Issues when not using SDWebImage when sending image from AppBoy Campaigns

### ISSUE THREAD

**Issue by anna-sakhlyan** [Appboy/appboy-ios-sdk#82]
We want to stop using SDWebImage and instead create our own custom controllers for in app modal notifications. However, no notifications are being sent when we do not use SDWebImage. And we are getting the following error when trying to send image from AppBoy Campaigns: " [APPBOY] Cannot find class SDWebImageManager, please make sure you include SDWebImage.framework. "

Could you, please, provide us with a solution regarding this matter?

**Comment by Wenzhi** [comment]
Hey @anna-sakhlyan,

To use your own controller for in-app messages, you can implement the [delegate method](https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyKit/headers/AppboyKitLibrary/ABKInAppMessageControllerDelegate.h#L75) `- (ABKInAppMessageDisplayChoice)beforeInAppMessageDisplayed:(ABKInAppMessage *)inAppMessage withKeyboardIsUp:(BOOL)keyboardIsUp`. Inside the method, you can grab the in-app message data model and return `ABKDiscardInAppMessage`, so Appboy won't display the in-app messsage for you.

For more information about implementing the delegate methods, please check out our documentation [here](https://www.appboy.com/documentation/iOS/#setting-a-delegate). 

Please let us know if you have any other questions or issues.

Thanks,
Wenzhi

**Comment by briancaw** [comment]
Hi @anna-sakhlyan,

Have you been able to resolve this issue?  If we don't hear back on it in the near future we'll close it out - but please feel free to reopen if you're still seeing problems.

Thanks,
Brian
