### ISSUE TITLE
userNotificationCenter:didReceive:withCompletionHandler completionHandler is not optional

### ISSUE THREAD

**Issue by BarakRL** [Appboy/appboy-ios-sdk#83]
The documentation states:

> @param completionHandler A block passed in from the didReceiveNotificationResponse:withCompletionHandler: call. Appboy will call
     * it at the end of the method if one is passed in. If you prefer to handle the completionHandler youself, please pass nil to Appboy

but the function does not take a nil:
`open func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Swift.Void)`

**Comment by Wenzhi** [comment]
Hey @BarakRL ,

Thanks for reporting this! We fixed it by releasing a new version (2.24.1) with nullability annotation to the method. Could you try it and confirm that the new SDK solves this issue?

Thanks,
Wenzhi

**Comment by briancaw** [comment]
Hi @BarakRL,

Please feel free to reopen this issue if you find it's still present in our latest release.  Thanks very much for reporting!
