### ISSUE TITLE
Question Deeplink In-App Message.

### ISSUE THREAD

**Issue by nothing2lose** [Appboy/appboy-ios-sdk#84]
In-App Messaging deeplink implemented by `UIApplication.openURL` method?

**Comment by Wenzhi** [comment]
@nothing2lose,

We check the deep link using UIApplication's `canOpenURL` method before passing it to the `openURL` method. Could you confirm that the deep link scheme is in the plist's whitelist? Please see our documentation [here](https://www.appboy.com/documentation/iOS/#ios-9-adding-a-scheme-whitelist).

Thanks,
Wenzhi

**Comment by nothing2lose** [comment]
Thanks for answer. 

I resolved issue.

**Comment by briancaw** [comment]
Thanks for reporting this @nothing2lose!  Closing now.
