### ISSUE TITLE
Version 2.24 via Cocoapods not compatible with Xcode 7

### ISSUE THREAD

**Issue by lacyrhoades** [Appboy/appboy-ios-sdk#87]
Using Appboy iOS SDK version 2.24 (installed via Cocoapods) causes compiler error about not being able to find UserNotification framework. (UserNotification framework doesn't exist before Xcode 8.)

Downgrading to version 2.22 works fine with Xcode 7 targeting iOS 8.

Ostensibly another solution is to upgrade to Xcode 8.

**Comment by tiffanylu** [comment]
Hi @lacyrhoades,

Thanks for reaching out! As documented in our [CHANGELOG](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#2240), Appboy iOS SDK version 2.24 updates the SDK to require Xcode 8. Those requiring Xcode 7 may integrate Appboy iOS SDK version 2.23. An alternative, as you mentioned, is to upgrade to Xcode 8.

Please let us know if you have any other questions or concerns.

Best,
Tiff
