### ISSUE TITLE
ABKFeedViewController Data Source

### ISSUE THREAD

**Issue by davidblaesing** [Appboy/appboy-ios-sdk#90]
We want to make limitations for `ABKFeedViewController` like _new users are not able to see old newsfeed cards_.
Is there any chance to give some rules to the controller by checking against creation date? Any chance to modify the datasource?

If not, do we have to request them from 
`GET https://api.appboy.com/feed/list` 
[https://www.appboy.com/documentation/REST_API/#news-feed-export](url)
and create our own view controller presenting the news feed cards?

**Comment by Wenzhi** [comment]
Hey @davidblaesing, 

I want to confirm that users shouldn't see cards created before their first session, is that correct? If so, when you are creating a news feed card, you can add a filter in the "Target Users" section:
![image](https://cloud.githubusercontent.com/assets/996652/19500995/fbd269bc-956f-11e6-8a71-678019f991f5.png)
The date of the filter should be the date the news feed card is created. By doing so, users who join the app after the card is created won't see the card.

Please let us know if this answers your question.

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
hey @davidblaesing, 

Have you been able to resolve this issue? If we don't hear back on it in the near future we'll close it out - but please feel free to reopen if you're still seeing problems.

Thanks,
Wenzhi
