### ISSUE TITLE
Calls to logCardClicked do not work

### ISSUE THREAD

**Issue by dmkmedina** [Appboy/appboy-ios-sdk#98]
I'm building a custom news feed and have noticed that manual click throughs are not being propagated: 
 
`RCT_EXPORT_METHOD(logCardImpression:(NSString *)idString) {
    NSArray *cards = [[Appboy sharedInstance].feedController getNewsFeedCards];
    
    for (id card in cards) {
        ABKCard *castedCard = (ABKCard *)card;
        if ([castedCard.idString isEqualToString:idString]) {
            [castedCard logCardImpression];
            break;
        }
    }
}`

The click is not propagated to Appboy. [card logCardImpression] works as expected, but click throughs never show up in the dashboard.

**Comment by Wenzhi** [comment]
@dmkmedina,

Thanks for bringing the issue to our attention. Currently, only when a card has the `url` property with a valid value, the SDK will log clicks on the card. The url can be set either on our dashboard or on the cards from our SDK. 

Could you confirm that your cards have a valid `url` and if the `logCardClicked` method works in that case? 

Thanks,
Wenzhi

**Comment by laaxlabs** [comment]
Ah! It works perfectly now. Apologies, I hadn't seen that documented anywhere but it makes sense. Appreciate the quick response.

**Comment by dmkmedina** [comment]
Ah! It works perfectly now. Apologies, I hadn't seen that documented anywhere but it makes sense. Appreciate the quick response.

**Comment by Wenzhi** [comment]
Hey @dmkmedina,

Glad to know that the issue is solved! I'll also update our documentation for the cards on click behavior. Sorry for the confusion. 

Thanks for reporting this again. 

Happy new year!

Best,
Wenzhi
