### ISSUE TITLE
Orientation for ABKInAppMessageController not working

### ISSUE THREAD

**Issue by MarcFerry** [Appboy/appboy-ios-sdk#99]
Hi, 

I am currently trying to force in app-messages to be displayed in portrait orientation.
I tried doing this by setting the supportedOrientationMasks & supportedOrientations properties like this  : 
```
Appboy.start(withApiKey: appboyId, in: options.application, withLaunchOptions: options.launchOptions)
Appboy.sharedInstance()?.inAppMessageController.supportedOrientationMasks == .portrait
Appboy.sharedInstance()?.inAppMessageController.supportedOrientations == .portrait
```

However, the message view is still able to rotate to landscape.
The issue was reproduced on iPhone iOS 10.2 with AppBoy SDK v2.25.0.

**Comment by Wenzhi** [comment]
Hi @MarcFerry,

Thank you very much for letting us know about the issue. We are looking into it and will provide more information ASAP.

Thanks,
Wenzhi

**Comment by Wenzhi** [comment]
Hey @MarcFerry, 

If you change the `==` to `=`, it should work. Could you try the following code and let us know if it solves the issue for you?
```
Appboy.sharedInstance()?.inAppMessageController.supportedOrientationMasks = .portrait
Appboy.sharedInstance()?.inAppMessageController.supportedOrientations = .portrait
```

Thanks,
Wenzhi

**Comment by MarcFerry** [comment]
Yes indeed, it works better this way :)
Thanks for the quick update.
